//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSDate, NSNumber, NSString, TNDRMessage, TNDRMoment, TNDRMomentLikeID;

@interface _TNDRMomentLike : NSManagedObject
{
}

+ (id)entityInManagedObjectContext:(id)arg1;
+ (id)entityName;
+ (id)insertInManagedObjectContext:(id)arg1;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property(readonly, nonatomic) TNDRMomentLikeID *objectID;
- (BOOL)primitiveViewedValue;
- (void)setPrimitiveViewedValue:(BOOL)arg1;
@property BOOL viewedValue;

// Remaining properties
@property(retain, nonatomic) NSDate *date; // @dynamic date;
@property(retain, nonatomic) NSString *likeID; // @dynamic likeID;
@property(retain, nonatomic) NSString *likedBy; // @dynamic likedBy;
@property(retain, nonatomic) TNDRMessage *message; // @dynamic message;
@property(retain, nonatomic) TNDRMoment *moment; // @dynamic moment;
@property(retain, nonatomic) NSString *momentID; // @dynamic momentID;
@property(retain, nonatomic) NSNumber *viewed; // @dynamic viewed;

@end

