//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSDate, NSNumber, NSSet, NSString, TNDRMessage, TNDRMomentID, TNDRMomentPhoto, TNDRUser;

@interface _TNDRMoment : NSManagedObject
{
}

+ (id)entityInManagedObjectContext:(id)arg1;
+ (id)entityName;
+ (id)insertInManagedObjectContext:(id)arg1;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property int cameraValue;
@property BOOL failedChoiceValue;
@property int likeCountValue;
@property BOOL likedValue;
- (id)likesSet;
@property(readonly, nonatomic) TNDRMomentID *objectID;
- (int)primitiveCameraValue;
- (BOOL)primitiveFailedChoiceValue;
- (int)primitiveLikeCountValue;
- (BOOL)primitiveLikedValue;
- (int)primitiveProgressValue;
- (BOOL)primitiveTutorialValue;
@property int progressValue;
- (void)setPrimitiveCameraValue:(int)arg1;
- (void)setPrimitiveFailedChoiceValue:(BOOL)arg1;
- (void)setPrimitiveLikeCountValue:(int)arg1;
- (void)setPrimitiveLikedValue:(BOOL)arg1;
- (void)setPrimitiveProgressValue:(int)arg1;
- (void)setPrimitiveTutorialValue:(BOOL)arg1;
@property BOOL tutorialValue;

// Remaining properties
@property(retain, nonatomic) NSNumber *camera; // @dynamic camera;
@property(retain, nonatomic) NSDate *created; // @dynamic created;
@property(retain, nonatomic) NSString *edits; // @dynamic edits;
@property(retain, nonatomic) NSNumber *failedChoice; // @dynamic failedChoice;
@property(retain, nonatomic) NSString *filter; // @dynamic filter;
@property(retain, nonatomic) NSNumber *likeCount; // @dynamic likeCount;
@property(retain, nonatomic) NSNumber *liked; // @dynamic liked;
@property(retain, nonatomic) NSSet *likes; // @dynamic likes;
@property(retain, nonatomic) NSString *localURL; // @dynamic localURL;
@property(retain, nonatomic) TNDRMessage *message; // @dynamic message;
@property(retain, nonatomic) NSString *momentID; // @dynamic momentID;
@property(retain, nonatomic) TNDRMomentPhoto *photo; // @dynamic photo;
@property(retain, nonatomic) NSString *photoID; // @dynamic photoID;
@property(retain, nonatomic) NSNumber *progress; // @dynamic progress;
@property(retain, nonatomic) NSString *text; // @dynamic text;
@property(retain, nonatomic) NSString *textAlignment; // @dynamic textAlignment;
@property(retain, nonatomic) NSString *textOriginY; // @dynamic textOriginY;
@property(retain, nonatomic) NSString *textSize; // @dynamic textSize;
@property(retain, nonatomic) NSNumber *tutorial; // @dynamic tutorial;
@property(retain, nonatomic) TNDRUser *user; // @dynamic user;

@end

