//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSDate, NSNumber, NSOrderedSet, NSSet, NSString, TNDRMatch, TNDRUserID;

@interface _TNDRUser : NSManagedObject
{
}

+ (id)entityInManagedObjectContext:(id)arg1;
+ (id)entityName;
+ (id)insertInManagedObjectContext:(id)arg1;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
- (void)addPhotos:(id)arg1;
- (void)addPhotosObject:(id)arg1;
@property short commonFriendCountValue;
- (id)commonFriendsSet;
@property short commonLikeCountValue;
- (id)commonLikesSet;
@property float distanceMilesValue;
@property BOOL failedChoiceValue;
@property BOOL genderValue;
- (void)insertObject:(id)arg1 inPhotosAtIndex:(unsigned int)arg2;
- (void)insertPhotos:(id)arg1 atIndexes:(id)arg2;
@property BOOL isCurrentUserValue;
@property BOOL isTravelingValue;
@property BOOL likedValue;
- (id)momentsSet;
@property(readonly, nonatomic) TNDRUserID *objectID;
- (id)photosSet;
- (short)primitiveCommonFriendCountValue;
- (short)primitiveCommonLikeCountValue;
- (float)primitiveDistanceMilesValue;
- (BOOL)primitiveFailedChoiceValue;
- (BOOL)primitiveGenderValue;
- (BOOL)primitiveIsCurrentUserValue;
- (BOOL)primitiveIsTravelingValue;
- (BOOL)primitiveLikedValue;
- (float)primitiveTravelDistanceMilesValue;
- (void)removeObjectFromPhotosAtIndex:(unsigned int)arg1;
- (void)removePhotos:(id)arg1;
- (void)removePhotosAtIndexes:(id)arg1;
- (void)removePhotosObject:(id)arg1;
- (void)replaceObjectInPhotosAtIndex:(unsigned int)arg1 withObject:(id)arg2;
- (void)replacePhotosAtIndexes:(id)arg1 withPhotos:(id)arg2;
- (void)setPrimitiveCommonFriendCountValue:(short)arg1;
- (void)setPrimitiveCommonLikeCountValue:(short)arg1;
- (void)setPrimitiveDistanceMilesValue:(float)arg1;
- (void)setPrimitiveFailedChoiceValue:(BOOL)arg1;
- (void)setPrimitiveGenderValue:(BOOL)arg1;
- (void)setPrimitiveIsCurrentUserValue:(BOOL)arg1;
- (void)setPrimitiveIsTravelingValue:(BOOL)arg1;
- (void)setPrimitiveLikedValue:(BOOL)arg1;
- (void)setPrimitiveTravelDistanceMilesValue:(float)arg1;
@property float travelDistanceMilesValue;

// Remaining properties
@property(retain, nonatomic) NSString *bio; // @dynamic bio;
@property(retain, nonatomic) NSDate *birthdate; // @dynamic birthdate;
@property(retain, nonatomic) NSNumber *commonFriendCount; // @dynamic commonFriendCount;
@property(retain, nonatomic) NSSet *commonFriends; // @dynamic commonFriends;
@property(retain, nonatomic) NSNumber *commonLikeCount; // @dynamic commonLikeCount;
@property(retain, nonatomic) NSSet *commonLikes; // @dynamic commonLikes;
@property(retain, nonatomic) NSNumber *distanceMiles; // @dynamic distanceMiles;
@property(retain, nonatomic) NSDate *downloaded; // @dynamic downloaded;
@property(retain, nonatomic) NSNumber *failedChoice; // @dynamic failedChoice;
@property(retain, nonatomic) NSString *firstName; // @dynamic firstName;
@property(retain, nonatomic) NSNumber *gender; // @dynamic gender;
@property(retain, nonatomic) NSNumber *isCurrentUser; // @dynamic isCurrentUser;
@property(retain, nonatomic) NSNumber *isTraveling; // @dynamic isTraveling;
@property(retain, nonatomic) NSString *lastViewedPhotoID; // @dynamic lastViewedPhotoID;
@property(retain, nonatomic) NSNumber *liked; // @dynamic liked;
@property(retain, nonatomic) NSDate *markedForRewind; // @dynamic markedForRewind;
@property(retain, nonatomic) TNDRMatch *match; // @dynamic match;
@property(retain, nonatomic) NSSet *moments; // @dynamic moments;
@property(retain, nonatomic) NSOrderedSet *photos; // @dynamic photos;
@property(retain, nonatomic) NSDate *ping; // @dynamic ping;
@property(retain, nonatomic) NSNumber *travelDistanceMiles; // @dynamic travelDistanceMiles;
@property(retain, nonatomic) NSString *travelLocationName; // @dynamic travelLocationName;
@property(retain, nonatomic) NSString *userID; // @dynamic userID;
@property(retain, nonatomic) NSString *userLocationName; // @dynamic userLocationName;

@end

