//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSDate, NSNumber, NSSet, NSString, TNDRMatchmakerMatchID;

@interface _TNDRMatchmakerMatch : NSManagedObject
{
}

+ (id)entityInManagedObjectContext:(id)arg1;
+ (id)entityName;
+ (id)insertInManagedObjectContext:(id)arg1;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
- (id)friendsSet;
@property(readonly, nonatomic) TNDRMatchmakerMatchID *objectID;
@property BOOL pendingValue;
- (BOOL)primitivePendingValue;
- (void)setPrimitivePendingValue:(BOOL)arg1;

// Remaining properties
@property(retain, nonatomic) NSDate *created; // @dynamic created;
@property(retain, nonatomic) NSSet *friends; // @dynamic friends;
@property(retain, nonatomic) NSString *matchID; // @dynamic matchID;
@property(retain, nonatomic) NSString *message; // @dynamic message;
@property(retain, nonatomic) NSNumber *pending; // @dynamic pending;

@end

