//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSDate, NSNumber, NSString, TNDRMatch, TNDRMessageID, TNDRMoment, TNDRMomentLike;

@interface _TNDRMessage : NSManagedObject
{
}

+ (id)entityInManagedObjectContext:(id)arg1;
+ (id)entityName;
+ (id)insertInManagedObjectContext:(id)arg1;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property BOOL hasErrorValue;
@property(readonly, nonatomic) TNDRMessageID *objectID;
- (BOOL)primitiveHasErrorValue;
- (BOOL)primitiveViewedValue;
- (void)setPrimitiveHasErrorValue:(BOOL)arg1;
- (void)setPrimitiveViewedValue:(BOOL)arg1;
@property BOOL viewedValue;

// Remaining properties
@property(retain, nonatomic) NSDate *clientCreated; // @dynamic clientCreated;
@property(retain, nonatomic) NSDate *created; // @dynamic created;
@property(retain, nonatomic) NSString *fromUserID; // @dynamic fromUserID;
@property(retain, nonatomic) NSNumber *hasError; // @dynamic hasError;
@property(retain, nonatomic) NSString *localImageURL; // @dynamic localImageURL;
@property(retain, nonatomic) TNDRMatch *match; // @dynamic match;
@property(retain, nonatomic) TNDRMoment *moment; // @dynamic moment;
@property(retain, nonatomic) TNDRMomentLike *momentLike; // @dynamic momentLike;
@property(retain, nonatomic) NSString *photoURL; // @dynamic photoURL;
@property(retain, nonatomic) NSString *text; // @dynamic text;
@property(retain, nonatomic) NSNumber *viewed; // @dynamic viewed;

@end

