//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "A2DynamicDelegate.h"

@interface A2DynamicClassDelegate : A2DynamicDelegate
{
    Class _proxiedClass;
}

- (void).cxx_destruct;
- (id)blockImplementationForClassMethod:(SEL)arg1;
- (Class)class;
- (id)description;
- (void)forwardInvocation:(id)arg1;
- (unsigned int)hash;
- (void)implementClassMethod:(SEL)arg1 withBlock:(id)arg2;
- (BOOL)isClassProxy;
- (BOOL)isEqual:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
@property(retain, nonatomic) Class proxiedClass; // @synthesize proxiedClass=_proxiedClass;
- (void)removeBlockImplementationForClassMethod:(SEL)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;

@end

