//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ABMultiValue.h"

@interface ABMutableMultiValue : ABMultiValue
{
}

- (void *)_mutableRef;
- (BOOL)addMultiValue:(id)arg1;
- (BOOL)addValue:(id)arg1 withLabel:(id)arg2 identifier:(int *)arg3;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)initWithPropertyType:(unsigned int)arg1;
- (BOOL)insertValue:(id)arg1 withLabel:(id)arg2 atIndex:(unsigned int)arg3 identifier:(int *)arg4;
- (BOOL)removeValueAndLabelAtIndex:(unsigned int)arg1;
- (BOOL)replaceLabelAtIndex:(unsigned int)arg1 withLabel:(id)arg2;
- (BOOL)replaceValueAtIndex:(unsigned int)arg1 withValue:(id)arg2;

@end

