//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BFAppLinkReturnToRefererViewDelegate.h"

@class BFAppLinkReturnToRefererView, BFURL, NSString, NSURL, UINavigationController;

@interface BFAppLinkReturnToRefererController : NSObject <BFAppLinkReturnToRefererViewDelegate>
{
    BFURL *_lastShownBFUrl;
    NSURL *_lastShownUrl;
    BFAppLinkReturnToRefererView *_view;
    id <BFAppLinkReturnToRefererControllerDelegate> _delegate;
    UINavigationController *_attachedToNavController;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UINavigationController *attachedToNavController; // @synthesize attachedToNavController=_attachedToNavController;
- (void)closeViewAnimated:(BOOL)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <BFAppLinkReturnToRefererControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)init;
- (id)initForDisplayAboveNavController:(id)arg1;
- (void)moveNavigationBar;
- (void)openRefererAppLink:(id)arg1;
- (void)orientationDidChange:(id)arg1;
- (void)removeFromNavController;
- (void)returnToRefererViewDidTapInsideCloseButton:(id)arg1;
- (void)returnToRefererViewDidTapInsideLink:(id)arg1 link:(id)arg2;
@property(retain, nonatomic) BFAppLinkReturnToRefererView *view; // @synthesize view=_view;
- (void)showViewForRefererAppLink:(id)arg1;
- (void)showViewForRefererURL:(id)arg1;
- (void)statusBarFrameDidChange:(id)arg1;
- (void)statusBarFrameWillChange:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

