//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CCActionInstant.h"

@interface CCActionFlipY : CCActionInstant
{
    BOOL _flipY;
}

+ (id)actionWithFlipY:(BOOL)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithFlipY:(BOOL)arg1;
- (id)reverse;
- (void)update:(double)arg1;

@end

