//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CCActionInterval.h"

@class NSString;

@interface CCActionTween : CCActionInterval
{
    NSString *_key;
    float _from;
    float _to;
    float _delta;
}

+ (id)actionWithDuration:(double)arg1 key:(id)arg2 from:(float)arg3 to:(float)arg4;
- (void).cxx_destruct;
- (id)initWithDuration:(double)arg1 key:(id)arg2 from:(float)arg3 to:(float)arg4;
- (id)reverse;
- (void)startWithTarget:(id)arg1;
- (void)update:(double)arg1;

@end

