//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CCActionInterval.h"

#import "NSCopying.h"

@interface CCActionScaleTo : CCActionInterval <NSCopying>
{
    float _scaleX;
    float _scaleY;
    float _startScaleX;
    float _startScaleY;
    float _endScaleX;
    float _endScaleY;
    float _deltaX;
    float _deltaY;
}

+ (id)actionWithDuration:(double)arg1 scale:(float)arg2;
+ (id)actionWithDuration:(double)arg1 scaleX:(float)arg2 scaleY:(float)arg3;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithDuration:(double)arg1 scale:(float)arg2;
- (id)initWithDuration:(double)arg1 scaleX:(float)arg2 scaleY:(float)arg3;
- (void)startWithTarget:(id)arg1;
- (void)update:(double)arg1;

@end

