//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CCActionCardinalSplineTo.h"

@interface CCActionCardinalSplineBy : CCActionCardinalSplineTo
{
    struct CGPoint _startPosition;
}

- (id)reverse;
- (void)startWithTarget:(id)arg1;
- (void)updatePosition:(struct CGPoint)arg1;

@end

