//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@interface CCAction : NSObject <NSCopying>
{
    id _originalTarget;
    id _target;
    int _tag;
}

+ (id)action;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
- (id)init;
- (BOOL)isDone;
@property(readonly, nonatomic) id originalTarget; // @synthesize originalTarget=_originalTarget;
@property(nonatomic) int tag; // @synthesize tag=_tag;
- (void)startWithTarget:(id)arg1;
- (void)step:(double)arg1;
- (void)stop;
@property(readonly, nonatomic) id target; // @synthesize target=_target;
- (void)update:(double)arg1;

@end

