//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CCActionEaseRate.h"

#import "NSCopying.h"

@interface CCActionEaseIn : CCActionEaseRate <NSCopying>
{
}

- (void)update:(double)arg1;

@end

