//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CCActionInterval.h"

#import "NSCopying.h"

@class CCColor;

@interface CCActionTintTo : CCActionInterval <NSCopying>
{
    CCColor *_to;
    CCColor *_from;
}

+ (id)actionWithDuration:(double)arg1 color:(id)arg2;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithDuration:(double)arg1 color:(id)arg2;
- (void)startWithTarget:(id)arg1;
- (void)update:(double)arg1;

@end

