//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CCActionCardinalSplineTo.h"

@interface CCActionCatmullRomTo : CCActionCardinalSplineTo
{
}

+ (id)actionWithDuration:(double)arg1 points:(id)arg2;
- (id)initWithDuration:(double)arg1 points:(id)arg2;

@end

