//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CCSchedulerTarget.h"

@class CCBSequence, CCNode, CCScheduler, NSMutableArray, NSMutableDictionary, NSObject<CCBAnimationManagerDelegate>, NSString;

@interface CCAnimationManager : NSObject <CCSchedulerTarget>
{
    NSMutableDictionary *_nodeSequences;
    NSMutableDictionary *_baseValues;
    int _animationManagerId;
    CCBSequence *_runningSequence;
    CCBSequence *_lastSequence;
    CDUnknownBlockType block;
    CCScheduler *_scheduler;
    NSMutableArray *_currentActions;
    BOOL _loop;
    _Bool _fixedTimestep;
    _Bool _paused;
    NSObject<CCBAnimationManagerDelegate> *_delegate;
    NSString *_lastCompletedSequenceName;
    float _playbackSpeed;
    NSMutableArray *_sequences;
    int _autoPlaySequenceId;
    CCNode *_rootNode;
    id _owner;
    struct CGSize _rootContainerSize;
}

- (void).cxx_destruct;
- (id)actionForCallbackChannel:(id)arg1;
- (id)actionForSoundChannel:(id)arg1;
- (id)actionFromKeyframe0:(id)arg1 andKeyframe1:(id)arg2 propertyName:(id)arg3 node:(id)arg4;
- (void)addAnimationsWithDictionary:(id)arg1 node:(id)arg2;
- (void)addAnimationsWithFile:(id)arg1 node:(id)arg2;
- (void)addKeyFramesForSequenceNamed:(id)arg1 propertyType:(int)arg2 frameArray:(id)arg3 node:(id)arg4 loop:(BOOL)arg5;
- (void)addNode:(id)arg1 andSequences:(id)arg2;
- (void)addSequenceCallBacks:(int)arg1 tweenDuration:(float)arg2 startTime:(float)arg3;
- (void)animationWithSpriteFrames:(id)arg1 delay:(float)arg2 name:(id)arg3 node:(id)arg4 loop:(BOOL)arg5;
@property(nonatomic) int autoPlaySequenceId; // @synthesize autoPlaySequenceId=_autoPlaySequenceId;
- (id)baseValueForNode:(id)arg1 propertyName:(id)arg2;
- (void)cleanup;
- (void)clearAllActions;
- (struct CGSize)containerSize:(id)arg1;
- (id)createActionForNode:(id)arg1 sequenceProperty:(id)arg2 beginKeyFrame:(int)arg3 endKeyFrame:(int)arg4;
- (void)dealloc;
- (void)debug;
@property(nonatomic) __weak NSObject<CCBAnimationManagerDelegate> *delegate; // @synthesize delegate=_delegate;
- (id)easeAction:(id)arg1 easingType:(int)arg2 easingOpt:(float)arg3;
- (id)findFrames:(float)arg1 sequenceProperty:(id)arg2;
@property(nonatomic) _Bool fixedTimestep; // @synthesize fixedTimestep=_fixedTimestep;
- (void)fixedUpdate:(double)arg1;
- (id)init;
- (void)jumpToSequenceNamed:(id)arg1 time:(float)arg2;
@property(readonly, nonatomic) NSString *lastCompletedSequenceName; // @synthesize lastCompletedSequenceName=_lastCompletedSequenceName;
- (void)moveAnimationsFromNode:(id)arg1 toNode:(id)arg2;
- (void)onEnter;
@property(nonatomic) id owner; // @synthesize owner=_owner;
- (void)parseVersion1:(id)arg1 node:(id)arg2;
- (void)parseVersion2:(id)arg1 node:(id)arg2;
@property(nonatomic) _Bool paused; // @synthesize paused=_paused;
@property(nonatomic) float playbackSpeed; // @synthesize playbackSpeed=_playbackSpeed;
@property(readonly, nonatomic) int priority;
@property(nonatomic) struct CGSize rootContainerSize; // @synthesize rootContainerSize=_rootContainerSize;
@property(nonatomic) CCNode *rootNode; // @synthesize rootNode=_rootNode;
- (void)runActionsForNode:(id)arg1 sequenceProperty:(id)arg2 tweenDuration:(float)arg3 startKeyFrame:(int)arg4;
- (void)runAnimationsForSequenceId:(int)arg1 tweenDuration:(float)arg2;
- (void)runAnimationsForSequenceNamed:(id)arg1;
- (void)runAnimationsForSequenceNamed:(id)arg1 tweenDuration:(float)arg2;
@property(readonly, nonatomic) NSString *runningSequenceName;
- (id)seqForNode:(id)arg1;
- (void)sequenceCompleted;
- (id)sequenceFromSequenceId:(int)arg1;
- (int)sequenceIdForSequenceNamed:(id)arg1;
@property(readonly, nonatomic) NSMutableArray *sequences; // @synthesize sequences=_sequences;
- (void)setAnimatedProperty:(id)arg1 forNode:(id)arg2 toValue:(id)arg3 tweenDuration:(float)arg4;
- (void)setBaseValue:(id)arg1 forNode:(id)arg2 propertyName:(id)arg3;
- (void)setCompletedAnimationCallbackBlock:(CDUnknownBlockType)arg1;
- (void)setKeyFrameForNode:(id)arg1 sequenceProperty:(id)arg2 tweenDuration:(float)arg3 keyFrame:(int)arg4;
- (void)timeSeekForSequenceId:(int)arg1 time:(float)arg2;
- (void)timeSeekForSequenceNamed:(id)arg1 time:(float)arg2;
- (void)timeSeekStaticForSequenceId:(int)arg1 time:(float)arg2;
- (void)update:(double)arg1;
- (void)updateInternal:(double)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

