//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class CCActionSequence;

@interface CCBKeyframe : NSObject <NSCopying>
{
    id _value;
    float _time;
    int _easingType;
    float _easingOpt;
    CCActionSequence *_frameActions;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
@property(nonatomic) float easingOpt; // @synthesize easingOpt=_easingOpt;
@property(nonatomic) int easingType; // @synthesize easingType=_easingType;
@property(retain, nonatomic) CCActionSequence *frameActions; // @synthesize frameActions=_frameActions;
- (id)init;
@property(nonatomic) float time; // @synthesize time=_time;
@property(retain, nonatomic) id value; // @synthesize value=_value;

@end

