//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSCharacterSet, NSString;

@interface CCBMFontConfiguration : NSObject
{
    NSCharacterSet *_characterSet;
    NSString *_atlasName;
    struct _FontDefHashElement *_fontDefDictionary;
    int _commonHeight;
    struct _BMFontPadding _padding;
    struct _KerningHashElement *_kerningDictionary;
}

+ (id)configurationWithFNTFile:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *atlasName; // @synthesize atlasName=_atlasName;
@property(readonly, nonatomic) NSCharacterSet *characterSet; // @synthesize characterSet=_characterSet;
- (void)dealloc;
- (id)description;
- (id)initWithFNTfile:(id)arg1;
- (void)parseCharacterDefinition:(id)arg1 charDef:(struct _BMFontDef *)arg2;
- (void)parseCommonArguments:(id)arg1;
- (id)parseConfigFile:(id)arg1;
- (void)parseImageFileName:(id)arg1 fntFile:(id)arg2;
- (void)parseInfoArguments:(id)arg1;
- (void)parseKerningEntry:(id)arg1;
- (void)purgeFontDefDictionary;
- (void)purgeKerningDictionary;

@end

