//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CCCacheValue : NSObject
{
    NSString *_fullpath;
    float _contentScale;
}

- (void).cxx_destruct;
@property(nonatomic) float contentScale; // @synthesize contentScale=_contentScale;
@property(retain, nonatomic) NSString *fullpath; // @synthesize fullpath=_fullpath;
- (id)initWithFullPath:(id)arg1 contentScale:(float)arg2;

@end

