//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CCCacheEntry : NSObject
{
    id _sharedData;
    id _publicObject;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id publicObject; // @synthesize publicObject=_publicObject;
@property(retain, nonatomic) id sharedData; // @synthesize sharedData=_sharedData;

@end

