//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CCBlendMode, CCRenderer, CCShader, NSArray, NSMutableDictionary, NSString;

@interface CCEffectRenderPass : NSObject
{
    BOOL _needsClear;
    int _renderPassId;
    CCRenderer *_renderer;
    CCBlendMode *_blendMode;
    CCShader *_shader;
    NSMutableDictionary *_shaderUniforms;
    NSArray *_beginBlocks;
    NSArray *_updateBlocks;
    NSArray *_endBlocks;
    NSString *_debugLabel;
    union _GLKMatrix4 _transform;
    union _GLKMatrix4 _ndcToWorld;
    struct CCSpriteVertexes _verts;
}

- (void).cxx_destruct;
- (void)begin:(id)arg1;
@property(copy, nonatomic) NSArray *beginBlocks; // @synthesize beginBlocks=_beginBlocks;
@property(retain, nonatomic) CCBlendMode *blendMode; // @synthesize blendMode=_blendMode;
@property(copy, nonatomic) NSString *debugLabel; // @synthesize debugLabel=_debugLabel;
- (void)end;
@property(copy, nonatomic) NSArray *endBlocks; // @synthesize endBlocks=_endBlocks;
- (void)enqueueTriangles;
- (id)init;
@property(nonatomic) union _GLKMatrix4 ndcToWorld; // @synthesize ndcToWorld=_ndcToWorld;
@property(nonatomic) BOOL needsClear; // @synthesize needsClear=_needsClear;
@property(nonatomic) int renderPassId; // @synthesize renderPassId=_renderPassId;
@property(retain, nonatomic) CCRenderer *renderer; // @synthesize renderer=_renderer;
@property(retain, nonatomic) CCShader *shader; // @synthesize shader=_shader;
@property(retain, nonatomic) NSMutableDictionary *shaderUniforms; // @synthesize shaderUniforms=_shaderUniforms;
@property(nonatomic) union _GLKMatrix4 transform; // @synthesize transform=_transform;
@property(copy, nonatomic) NSArray *updateBlocks; // @synthesize updateBlocks=_updateBlocks;
@property(nonatomic) struct CCSpriteVertexes verts; // @synthesize verts=_verts;
- (void)update;

@end

