//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CCShader, NSArray, NSMutableArray, NSMutableDictionary, NSString;

@interface CCEffect : NSObject
{
    BOOL _firstInStack;
    NSString *_debugName;
    CCShader *_shader;
    NSMutableDictionary *_shaderUniforms;
    id <CCEffectStackProtocol> _owningStack;
    NSMutableArray *_vertexFunctions;
    NSMutableArray *_fragmentFunctions;
    NSArray *_fragmentUniforms;
    NSArray *_vertexUniforms;
    NSArray *_varyingVars;
    NSArray *_renderPasses;
    unsigned int _stitchFlags;
    NSMutableDictionary *_uniformTranslationTable;
}

+ (id)defaultEffectFragmentUniformNames;
+ (id)defaultEffectFragmentUniforms;
+ (id)defaultEffectVertexUniformNames;
+ (id)defaultEffectVertexUniforms;
- (void).cxx_destruct;
- (void)buildEffectShader;
- (void)buildEffectWithFragmentFunction:(id)arg1 vertexFunctions:(id)arg2 fragmentUniforms:(id)arg3 vertexUniforms:(id)arg4 varyings:(id)arg5 firstInStack:(BOOL)arg6;
- (void)buildFragmentFunctions;
- (void)buildRenderPasses;
- (id)buildShaderSourceFromBase:(id)arg1 functions:(id)arg2 uniforms:(id)arg3 varyings:(id)arg4 firstInStack:(BOOL)arg5;
- (void)buildShaderUniforms:(id)arg1 vertexUniforms:(id)arg2;
- (void)buildUniformTranslationTable;
- (void)buildVertexFunctions;
@property(copy, nonatomic) NSString *debugName; // @synthesize debugName=_debugName;
@property(readonly, nonatomic) BOOL firstInStack; // @synthesize firstInStack=_firstInStack;
@property(retain, nonatomic) NSMutableArray *fragmentFunctions; // @synthesize fragmentFunctions=_fragmentFunctions;
@property(retain, nonatomic) NSArray *fragmentUniforms; // @synthesize fragmentUniforms=_fragmentUniforms;
- (id)init;
- (id)initWithFragmentFunction:(id)arg1 fragmentUniforms:(id)arg2 vertexUniforms:(id)arg3 varyings:(id)arg4;
- (id)initWithFragmentFunction:(id)arg1 vertexFunctions:(id)arg2 fragmentUniforms:(id)arg3 vertexUniforms:(id)arg4 varyings:(id)arg5;
- (id)initWithFragmentFunction:(id)arg1 vertexFunctions:(id)arg2 fragmentUniforms:(id)arg3 vertexUniforms:(id)arg4 varyings:(id)arg5 firstInStack:(BOOL)arg6;
- (id)initWithFragmentUniforms:(id)arg1 vertexUniforms:(id)arg2 varyings:(id)arg3;
@property(nonatomic) __weak id <CCEffectStackProtocol> owningStack; // @synthesize owningStack=_owningStack;
- (unsigned int)prepareForRendering;
@property(readonly, nonatomic) BOOL readyForRendering;
- (id)renderPassAtIndex:(unsigned int)arg1;
@property(retain, nonatomic) NSArray *renderPasses; // @synthesize renderPasses=_renderPasses;
@property(readonly, nonatomic) unsigned int renderPassesRequired;
@property(retain, nonatomic) NSMutableDictionary *shaderUniforms; // @synthesize shaderUniforms=_shaderUniforms;
@property(nonatomic) unsigned int stitchFlags; // @synthesize stitchFlags=_stitchFlags;
@property(retain, nonatomic) NSMutableDictionary *uniformTranslationTable; // @synthesize uniformTranslationTable=_uniformTranslationTable;
@property(retain, nonatomic) NSArray *varyingVars; // @synthesize varyingVars=_varyingVars;
- (void)setVaryings:(id)arg1;
@property(retain, nonatomic) NSMutableArray *vertexFunctions; // @synthesize vertexFunctions=_vertexFunctions;
@property(retain, nonatomic) NSArray *vertexUniforms; // @synthesize vertexUniforms=_vertexUniforms;
@property(readonly, nonatomic) CCShader *shader; // @synthesize shader=_shader;
- (BOOL)stitchSupported:(unsigned int)arg1;
@property(readonly, nonatomic) BOOL supportsDirectRendering;

@end

