//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CCESRenderer.h"

@class EAGLContext, NSString;

@interface CCES2Renderer : NSObject <CCESRenderer>
{
    int _backingWidth;
    int _backingHeight;
    unsigned int _samplesToUse;
    BOOL _multiSampling;
    unsigned int _depthFormat;
    unsigned int _pixelFormat;
    unsigned int _defaultFramebuffer;
    unsigned int _colorRenderbuffer;
    unsigned int _depthBuffer;
    unsigned int _msaaFramebuffer;
    unsigned int _msaaColorbuffer;
    EAGLContext *_context;
}

- (void).cxx_destruct;
- (struct CGSize)backingSize;
- (unsigned int)colorRenderBuffer;
@property(readonly, nonatomic) unsigned int colorRenderbuffer; // @synthesize colorRenderbuffer=_colorRenderbuffer;
@property(readonly, nonatomic) EAGLContext *context; // @synthesize context=_context;
- (void)dealloc;
- (unsigned int)defaultFrameBuffer;
@property(readonly, nonatomic) unsigned int defaultFramebuffer; // @synthesize defaultFramebuffer=_defaultFramebuffer;
@property(readonly, copy) NSString *description;
- (id)initWithDepthFormat:(unsigned int)arg1 withPixelFormat:(unsigned int)arg2 withSharegroup:(id)arg3 withMultiSampling:(BOOL)arg4 withNumberOfSamples:(unsigned int)arg5;
- (unsigned int)msaaColorBuffer;
@property(readonly, nonatomic) unsigned int msaaColorbuffer; // @synthesize msaaColorbuffer=_msaaColorbuffer;
- (unsigned int)msaaFrameBuffer;
@property(readonly, nonatomic) unsigned int msaaFramebuffer; // @synthesize msaaFramebuffer=_msaaFramebuffer;
- (BOOL)resizeFromLayer:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

