//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CCNode, CCPhysicsBody, ChipmunkShape, NSArray, NSString;

@interface CCPhysicsShape : NSObject
{
    CCPhysicsShape *_next;
    NSString *_collisionType;
    NSArray *_collisionCategories;
    NSArray *_collisionMask;
}

+ (id)circleShapeWithRadius:(float)arg1 center:(struct CGPoint)arg2;
+ (id)pillShapeFrom:(struct CGPoint)arg1 to:(struct CGPoint)arg2 cornerRadius:(float)arg3;
+ (id)polygonShapeWithPoints:(struct CGPoint *)arg1 count:(unsigned int)arg2 cornerRadius:(float)arg3;
+ (id)rectShape:(struct CGRect)arg1 cornerRadius:(float)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) float area;
@property(nonatomic) __weak CCPhysicsBody *body;
@property(copy, nonatomic) NSArray *collisionCategories;
@property(nonatomic) id collisionGroup;
@property(copy, nonatomic) NSArray *collisionMask;
@property(copy, nonatomic) NSString *collisionType;
@property(nonatomic) float density;
- (void)didRemoveFromPhysicsNode:(id)arg1;
@property(nonatomic) float elasticity;
@property(nonatomic) float friction;
@property(nonatomic) float mass;
@property(retain, nonatomic) CCPhysicsShape *next;
@property(readonly, nonatomic) CCNode *node;
- (id)physicsNode;
- (void)rescaleShape:(struct CGAffineTransform)arg1;
@property(nonatomic) BOOL sensor;
@property(nonatomic) struct CGPoint surfaceVelocity;
@property(readonly, nonatomic) ChipmunkShape *shape;
- (struct CGAffineTransform)shapeTransform;
- (void)willAddToPhysicsNode:(id)arg1 nonRigidTransform:(struct CGAffineTransform)arg2;

@end

