//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface CCProfiler : NSObject
{
    NSMutableDictionary *activeTimers;
}

+ (id)sharedProfiler;
- (void).cxx_destruct;
- (id)createAndAddTimerWithName:(id)arg1;
- (void)displayTimers;
- (id)init;
- (void)releaseAllTimers;
- (void)releaseTimer:(id)arg1;

@end

