//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CCTexturePVR : NSObject
{
    struct CCPVRMipmap _mipmaps[16];
    unsigned int _numberOfMipmaps;
    unsigned int _width;
    unsigned int _height;
    unsigned int _name;
    BOOL _hasAlpha;
    BOOL _hasPremultipliedAlpha;
    BOOL _forcePremultipliedAlpha;
    BOOL _retainName;
    unsigned int _format;
    const struct _ccPVRTexturePixelFormatInfo {
        unsigned int _field1;
        unsigned int _field2;
        unsigned int _field3;
        unsigned int _field4;
        char _field5;
        char _field6;
        unsigned int _field7;
    } *_pixelFormatInfo;
}

+ (id)pvrTextureWithContentsOfFile:(id)arg1;
+ (id)pvrTextureWithContentsOfURL:(id)arg1;
- (BOOL)createGLTexture;
- (void)dealloc;
@property(readonly, nonatomic) BOOL forcePremultipliedAlpha; // @synthesize forcePremultipliedAlpha=_forcePremultipliedAlpha;
@property(readonly, nonatomic) unsigned int format; // @synthesize format=_format;
@property(readonly, nonatomic) BOOL hasAlpha; // @synthesize hasAlpha=_hasAlpha;
@property(readonly, nonatomic) BOOL hasPremultipliedAlpha; // @synthesize hasPremultipliedAlpha=_hasPremultipliedAlpha;
@property(readonly, nonatomic) unsigned int height; // @synthesize height=_height;
- (id)initWithContentsOfFile:(id)arg1;
- (id)initWithContentsOfURL:(id)arg1;
@property(readonly, nonatomic) unsigned int name; // @synthesize name=_name;
@property(readonly, nonatomic) unsigned int numberOfMipmaps; // @synthesize numberOfMipmaps=_numberOfMipmaps;
@property(nonatomic) BOOL retainName; // @synthesize retainName=_retainName;
- (BOOL)unpackPVRv2Data:(char *)arg1 PVRLen:(unsigned int)arg2;
- (BOOL)unpackPVRv3Data:(char *)arg1 PVRLen:(unsigned int)arg2;
@property(readonly, nonatomic) unsigned int width; // @synthesize width=_width;

@end

