//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CCControl.h"

#import "UITextFieldDelegate.h"

@class CCSprite9Slice, CCSpriteFrame, NSString, UITextField;

@interface CCTextField : CCControl <UITextFieldDelegate>
{
    CCSprite9Slice *_background;
    float _scaleMultiplier;
    BOOL _keyboardIsShown;
    float _keyboardHeight;
    UITextField *_textField;
    float _fontSize;
    float _padding;
}

+ (id)textFieldWithSpriteFrame:(id)arg1;
- (void).cxx_destruct;
- (void)addUITextView;
@property(retain, nonatomic) CCSpriteFrame *backgroundSpriteFrame;
- (void)endFocusingOnTextField;
- (void)focusOnTextField;
@property(nonatomic) float fontSize; // @synthesize fontSize=_fontSize;
@property(readonly, nonatomic) float fontSizeInPoints;
- (id)init;
- (id)initWithSpriteFrame:(id)arg1;
- (void)keyboardWasShown:(id)arg1;
- (void)keyboardWillBeHidden:(id)arg1;
- (void)layout;
- (void)onEnter;
- (void)onEnterTransitionDidFinish;
- (void)onExitTransitionDidStart;
@property(nonatomic) float padding; // @synthesize padding=_padding;
- (void)positionTextField;
- (void)registerForKeyboardNotifications;
- (void)removeUITextView;
- (void)setEnabled:(BOOL)arg1;
@property(retain, nonatomic) NSString *string;
@property(readonly, nonatomic) UITextField *textField; // @synthesize textField=_textField;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)unregisterForKeyboardNotifications;
- (void)update:(double)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

