//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ChipmunkConstraint.h"

@interface ChipmunkDampedSpring : ChipmunkConstraint
{
    struct cpDampedSpring _constraint;
}

+ (id)dampedSpringWithBodyA:(id)arg1 bodyB:(id)arg2 anchorA:(struct CGPoint)arg3 anchorB:(struct CGPoint)arg4 restLength:(float)arg5 stiffness:(float)arg6 damping:(float)arg7;
@property(nonatomic) struct CGPoint anchorA;
@property(nonatomic) struct CGPoint anchorB;
- (struct cpConstraint *)constraint;
@property(nonatomic) float damping;
- (id)initWithBodyA:(id)arg1 bodyB:(id)arg2 anchorA:(struct CGPoint)arg3 anchorB:(struct CGPoint)arg4 restLength:(float)arg5 stiffness:(float)arg6 damping:(float)arg7;
@property(nonatomic) float restLength;
@property(nonatomic) float stiffness;

@end

