//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ChipmunkShape;

@interface ChipmunkShapeQueryInfo : NSObject
{
    ChipmunkShape *_shape;
    struct cpContactPointSet _contactPoints;
}

@property(readonly, nonatomic) struct cpContactPointSet *contactPoints;
- (void)dealloc;
- (id)initWithShape:(id)arg1 andPoints:(struct cpContactPointSet *)arg2;
@property(readonly, nonatomic) ChipmunkShape *shape; // @synthesize shape=_shape;

@end

