//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ChipmunkConstraint.h"

@interface ChipmunkGearJoint : ChipmunkConstraint
{
    struct cpGearJoint _constraint;
}

+ (id)gearJointWithBodyA:(id)arg1 bodyB:(id)arg2 phase:(float)arg3 ratio:(float)arg4;
- (struct cpConstraint *)constraint;
- (id)initWithBodyA:(id)arg1 bodyB:(id)arg2 phase:(float)arg3 ratio:(float)arg4;
@property(nonatomic) float phase;
@property(nonatomic) float ratio;

@end

