//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ChipmunkConstraint.h"

@interface ChipmunkSlideJoint : ChipmunkConstraint
{
    struct cpSlideJoint _constraint;
}

+ (id)slideJointWithBodyA:(id)arg1 bodyB:(id)arg2 anchorA:(struct CGPoint)arg3 anchorB:(struct CGPoint)arg4 min:(float)arg5 max:(float)arg6;
@property(nonatomic) struct CGPoint anchorA;
@property(nonatomic) struct CGPoint anchorB;
- (struct cpConstraint *)constraint;
- (id)initWithBodyA:(id)arg1 bodyB:(id)arg2 anchorA:(struct CGPoint)arg3 anchorB:(struct CGPoint)arg4 min:(float)arg5 max:(float)arg6;
@property(nonatomic) float max;
@property(nonatomic) float min;

@end

