//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBPeoplePickerViewController.h"

@class NSArray;

@interface FBFriendPickerViewController : FBPeoplePickerViewController
{
}

+ (id)cacheDescriptor;
+ (id)cacheDescriptorWithUserID:(id)arg1 fieldsForRequest:(id)arg2;
+ (id)cacheIdentity;
+ (double)cacheRefreshDelay;
+ (id)firstRenderLogString;
+ (id)graphAPIName;
+ (unsigned int)graphObjectPagingMode;
- (void)configureUsingCachedDescriptor:(id)arg1;
- (BOOL)delegateIncludesGraphObject:(id)arg1;
- (void)logAppEvents:(BOOL)arg1;
- (void)notifyDelegateDataDidChange;
- (void)notifyDelegateOfError:(id)arg1;
- (void)notifyDelegateSelectionDidChange;
@property(copy, nonatomic) NSArray *selection;

@end

