//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString, UIActivityIndicatorView, UIImage, UIImageView, UILabel;

@interface FBGraphObjectTableCell : UITableViewCell
{
    BOOL _boldTitle;
    BOOL _boldTitleSuffix;
    UIImageView *_pictureView;
    UILabel *_titleSuffixLabel;
    UIActivityIndicatorView *_activityIndicator;
}

+ (float)rowHeight;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(nonatomic) BOOL boldTitle; // @synthesize boldTitle=_boldTitle;
@property(nonatomic) BOOL boldTitleSuffix; // @synthesize boldTitleSuffix=_boldTitleSuffix;
- (void)createTitleSuffixLabel;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
@property(retain, nonatomic) UIImage *picture;
@property(retain, nonatomic) UIImageView *pictureView; // @synthesize pictureView=_pictureView;
@property(copy, nonatomic) NSString *subtitle;
@property(copy, nonatomic) NSString *title;
@property(copy, nonatomic) NSString *titleSuffix;
@property(retain, nonatomic) UILabel *titleSuffixLabel; // @synthesize titleSuffixLabel=_titleSuffixLabel;
- (void)startAnimatingActivityIndicator;
- (void)stopAnimatingActivityIndicator;
- (void)updateFonts;

@end

