//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBGraphObjectDataSourceDataNeededDelegate.h"

@class FBGraphObjectTableDataSource, FBRequestConnection, FBSession, NSString, UITableView;

@interface FBGraphObjectPagingLoader : NSObject <FBGraphObjectDataSourceDataNeededDelegate>
{
    BOOL _isResultFromCache;
    BOOL _skipRoundtripIfCached;
    UITableView *_tableView;
    FBGraphObjectTableDataSource *_dataSource;
    FBSession *_session;
    id <FBGraphObjectPagingLoaderDelegate> _delegate;
    unsigned int _pagingMode;
    NSString *_nextLink;
    FBRequestConnection *_connection;
    NSString *_cacheIdentity;
}

- (void)addResultsAndUpdateView:(id)arg1;
@property(copy, nonatomic) NSString *cacheIdentity; // @synthesize cacheIdentity=_cacheIdentity;
- (void)cancel;
@property(retain, nonatomic) FBRequestConnection *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) FBGraphObjectTableDataSource *dataSource; // @synthesize dataSource=_dataSource;
- (void)dealloc;
@property(nonatomic) id <FBGraphObjectPagingLoaderDelegate> delegate; // @synthesize delegate=_delegate;
- (void)followNextLink;
- (void)graphObjectTableDataSourceNeedsData:(id)arg1 triggeredByIndexPath:(id)arg2;
- (id)initWithDataSource:(id)arg1 pagingMode:(unsigned int)arg2;
@property(readonly, nonatomic) BOOL isResultFromCache; // @synthesize isResultFromCache=_isResultFromCache;
@property(retain, nonatomic) NSString *nextLink; // @synthesize nextLink=_nextLink;
@property(nonatomic) unsigned int pagingMode; // @synthesize pagingMode=_pagingMode;
- (void)requestCompleted:(id)arg1 result:(id)arg2 error:(id)arg3;
- (void)reset;
@property(retain, nonatomic) FBSession *session; // @synthesize session=_session;
@property(nonatomic) BOOL skipRoundtripIfCached; // @synthesize skipRoundtripIfCached=_skipRoundtripIfCached;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void)startLoadingWithRequest:(id)arg1 cacheIdentity:(id)arg2 skipRoundtripIfCached:(BOOL)arg3;
- (void)updateView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

