//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBSession, NSError, NSMutableData, NSMutableDictionary, NSString, NSURLConnection;

@interface FBRequest : NSObject
{
    id <FBRequestDelegate> _delegate;
    NSString *_url;
    NSString *_versionPart;
    NSURLConnection *_connection;
    NSMutableData *_responseText;
    unsigned int _state;
    NSError *_error;
    BOOL _sessionDidExpire;
    id <FBGraphObject> _graphObject;
    BOOL _canCloseSessionOnError;
    BOOL _skipClientToken;
    NSMutableDictionary *_parameters;
    FBSession *_session;
    NSString *_graphPath;
    NSString *_HTTPMethod;
    NSString *_restMethod;
}

+ (id)requestForCustomAudienceThirdPartyID:(id)arg1;
+ (id)requestForDeleteObject:(id)arg1;
+ (id)requestForGraphPath:(id)arg1;
+ (id)requestForMe;
+ (id)requestForMyFriends;
+ (id)requestForPlacesSearchAtCoordinate:(CDStruct_2c43369c)arg1 radiusInMeters:(int)arg2 resultsLimit:(int)arg3 searchText:(id)arg4;
+ (id)requestForPostOpenGraphObject:(id)arg1;
+ (id)requestForPostOpenGraphObjectWithType:(id)arg1 title:(id)arg2 image:(id)arg3 url:(id)arg4 description:(id)arg5 objectProperties:(id)arg6;
+ (id)requestForPostStatusUpdate:(id)arg1;
+ (id)requestForPostStatusUpdate:(id)arg1 place:(id)arg2 tags:(id)arg3;
+ (id)requestForPostWithGraphPath:(id)arg1 graphObject:(id)arg2;
+ (id)requestForUpdateOpenGraphObject:(id)arg1;
+ (id)requestForUpdateOpenGraphObjectWithId:(id)arg1 graphObject:(id)arg2;
+ (id)requestForUpdateOpenGraphObjectWithId:(id)arg1 title:(id)arg2 image:(id)arg3 url:(id)arg4 description:(id)arg5 objectProperties:(id)arg6;
+ (id)requestForUploadPhoto:(id)arg1;
+ (id)requestForUploadStagingResourceWithImage:(id)arg1;
+ (id)requestWithGraphPath:(id)arg1 parameters:(id)arg2 HTTPMethod:(id)arg3;
+ (id)serializeURL:(id)arg1 params:(id)arg2;
+ (id)serializeURL:(id)arg1 params:(id)arg2 httpMethod:(id)arg3;
@property(copy, nonatomic) NSString *HTTPMethod; // @synthesize HTTPMethod=_HTTPMethod;
@property(nonatomic) BOOL canCloseSessionOnError; // @synthesize canCloseSessionOnError=_canCloseSessionOnError;
@property(retain, nonatomic) NSURLConnection *connection;
- (id)createRequestConnection;
- (void)dealloc;
@property(nonatomic) id <FBRequestDelegate> delegate;
- (id)description;
@property(retain, nonatomic) NSError *error;
@property(retain, nonatomic) id <FBGraphObject> graphObject;
@property(copy, nonatomic) NSString *graphPath; // @synthesize graphPath=_graphPath;
@property(copy, nonatomic) NSString *httpMethod;
- (id)init;
- (id)initForPostWithSession:(id)arg1 graphPath:(id)arg2 graphObject:(id)arg3;
- (id)initWithSession:(id)arg1 graphPath:(id)arg2;
- (id)initWithSession:(id)arg1 graphPath:(id)arg2 parameters:(id)arg3 HTTPMethod:(id)arg4;
- (id)initWithSession:(id)arg1 restMethod:(id)arg2 parameters:(id)arg3 HTTPMethod:(id)arg4;
- (BOOL)loading;
- (void)overrideVersionPartWith:(id)arg1;
@property(readonly, retain, nonatomic) NSMutableDictionary *parameters; // @synthesize parameters=_parameters;
@property(retain, nonatomic) NSMutableDictionary *params;
@property(retain, nonatomic) NSMutableData *responseText;
@property(copy, nonatomic) NSString *restMethod; // @synthesize restMethod=_restMethod;
@property(retain, nonatomic) FBSession *session; // @synthesize session=_session;
@property(nonatomic) BOOL sessionDidExpire;
@property(nonatomic) BOOL skipClientToken; // @synthesize skipClientToken=_skipClientToken;
@property(nonatomic) unsigned int state;
@property(copy, nonatomic) NSString *url;
- (id)startWithCompletionHandler:(CDUnknownBlockType)arg1;
@property(readonly) NSString *versionPart;

@end

