//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPUImageTwoInputCrossTextureSamplingFilter.h"

@class GPUImageFramebuffer;

@interface GPUImagePoissonBlendFilter : GPUImageTwoInputCrossTextureSamplingFilter
{
    int mixUniform;
    GPUImageFramebuffer *secondOutputFramebuffer;
    float _mix;
    unsigned int _numIterations;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic) float mix; // @synthesize mix=_mix;
@property(nonatomic) unsigned int numIterations; // @synthesize numIterations=_numIterations;
- (void)renderToTextureWithVertices:(const float *)arg1 textureCoordinates:(const float *)arg2;

@end

