//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GPUImageInput.h"

@class GPUImageFramebuffer, NSString;

@interface GPUImageTextureOutput : NSObject <GPUImageInput>
{
    GPUImageFramebuffer *firstInputFramebuffer;
    BOOL enabled;
    id <GPUImageTextureOutputDelegate> _delegate;
    unsigned int _texture;
}

- (void).cxx_destruct;
@property(nonatomic) id <GPUImageTextureOutputDelegate> delegate; // @synthesize delegate=_delegate;
- (void)doneWithTexture;
@property(nonatomic) BOOL enabled; // @synthesize enabled;
- (void)endProcessing;
- (id)init;
- (struct CGSize)maximumOutputSize;
- (void)newFrameReadyAtTime:(CDStruct_1b6d18a9)arg1 atIndex:(int)arg2;
- (int)nextAvailableTextureIndex;
- (void)setCurrentlyReceivingMonochromeInput:(BOOL)arg1;
- (void)setInputFramebuffer:(id)arg1 atIndex:(int)arg2;
- (void)setInputRotation:(int)arg1 atIndex:(int)arg2;
- (void)setInputSize:(struct CGSize)arg1 atIndex:(int)arg2;
- (BOOL)shouldIgnoreUpdatesToThisTarget;
@property(readonly) unsigned int texture; // @synthesize texture=_texture;
- (BOOL)wantsMonochromeInput;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

