//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPUImageOutput.h"

#import "AVCaptureAudioDataOutputSampleBufferDelegate.h"
#import "AVCaptureVideoDataOutputSampleBufferDelegate.h"

@class AVCaptureAudioDataOutput, AVCaptureDevice, AVCaptureDeviceInput, AVCaptureSession, AVCaptureVideoDataOutput, GLProgram, NSDate, NSString;

@interface GPUImageVideoCamera : GPUImageOutput <AVCaptureVideoDataOutputSampleBufferDelegate, AVCaptureAudioDataOutputSampleBufferDelegate>
{
    unsigned int numberOfFramesCaptured;
    float totalFrameTimeDuringCapture;
    AVCaptureSession *_captureSession;
    AVCaptureDevice *_inputCamera;
    AVCaptureDevice *_microphone;
    AVCaptureDeviceInput *videoInput;
    AVCaptureVideoDataOutput *videoOutput;
    BOOL capturePaused;
    int outputRotation;
    int internalRotation;
    struct dispatch_semaphore_s *frameRenderingSemaphore;
    BOOL captureAsYUV;
    unsigned int luminanceTexture;
    unsigned int chrominanceTexture;
    id <GPUImageVideoCameraDelegate> _delegate;
    AVCaptureDeviceInput *audioInput;
    AVCaptureAudioDataOutput *audioOutput;
    NSDate *startingCaptureTime;
    struct dispatch_queue_s *cameraProcessingQueue;
    struct dispatch_queue_s *audioProcessingQueue;
    GLProgram *yuvConversionProgram;
    int yuvConversionPositionAttribute;
    int yuvConversionTextureCoordinateAttribute;
    int yuvConversionLuminanceTextureUniform;
    int yuvConversionChrominanceTextureUniform;
    int yuvConversionMatrixUniform;
    const float *_preferredConversion;
    BOOL isFullYUVRange;
    int imageBufferWidth;
    int imageBufferHeight;
    BOOL addedAudioInputsDueToEncodingTarget;
    BOOL _runBenchmark;
    BOOL _horizontallyMirrorFrontFacingCamera;
    BOOL _horizontallyMirrorRearFacingCamera;
    NSString *_captureSessionPreset;
    int _outputImageOrientation;
    int _frameRate;
}

+ (BOOL)isBackFacingCameraPresent;
+ (BOOL)isFrontFacingCameraPresent;
- (void).cxx_destruct;
- (BOOL)addAudioInputsAndOutputs;
- (void)addTarget:(id)arg1 atTextureLocation:(int)arg2;
- (float)averageFrameDurationDuringCapture;
- (int)cameraPosition;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
@property(readonly, retain, nonatomic) AVCaptureSession *captureSession; // @synthesize captureSession=_captureSession;
@property(copy, nonatomic) NSString *captureSessionPreset; // @synthesize captureSessionPreset=_captureSessionPreset;
- (void)convertYUVToRGBOutput;
- (void)dealloc;
@property(nonatomic) id <GPUImageVideoCameraDelegate> delegate; // @synthesize delegate=_delegate;
@property int frameRate; // @synthesize frameRate=_frameRate;
- (id)framebufferForOutput;
@property(nonatomic) BOOL horizontallyMirrorFrontFacingCamera; // @synthesize horizontallyMirrorFrontFacingCamera=_horizontallyMirrorFrontFacingCamera;
@property(nonatomic) BOOL horizontallyMirrorRearFacingCamera; // @synthesize horizontallyMirrorRearFacingCamera=_horizontallyMirrorRearFacingCamera;
- (id)init;
- (id)initWithSessionPreset:(id)arg1 cameraPosition:(int)arg2;
@property(readonly) AVCaptureDevice *inputCamera; // @synthesize inputCamera=_inputCamera;
@property(readonly, getter=isBackFacingCameraPresent) BOOL backFacingCameraPresent;
@property(readonly, getter=isFrontFacingCameraPresent) BOOL frontFacingCameraPresent;
@property(nonatomic) int outputImageOrientation; // @synthesize outputImageOrientation=_outputImageOrientation;
- (void)pauseCameraCapture;
- (void)processAudioSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (void)processVideoSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (BOOL)removeAudioInputsAndOutputs;
- (void)removeInputsAndOutputs;
- (void)resetBenchmarkAverage;
- (void)resumeCameraCapture;
- (void)rotateCamera;
@property(nonatomic) BOOL runBenchmark; // @synthesize runBenchmark=_runBenchmark;
- (void)setAudioEncodingTarget:(id)arg1;
- (void)startCameraCapture;
- (void)stopCameraCapture;
- (void)updateOrientationSendToTargets;
- (void)updateTargetsForVideoCameraUsingCacheTextureAtWidth:(int)arg1 height:(int)arg2 time:(CDStruct_1b6d18a9)arg3;
- (id)videoCaptureConnection;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

