//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPUImageFilterGroup.h"

@class GPUImageGaussianBlurFilter, GPUImageLuminanceRangeFilter, GPUImageSaturationFilter;

@interface GPUImageiOSBlurFilter : GPUImageFilterGroup
{
    GPUImageSaturationFilter *saturationFilter;
    GPUImageGaussianBlurFilter *blurFilter;
    GPUImageLuminanceRangeFilter *luminanceRangeFilter;
    float blurRadiusInPixels;
    float saturation;
    float _downsampling;
}

- (void).cxx_destruct;
@property(nonatomic) float blurRadiusInPixels; // @synthesize blurRadiusInPixels;
@property(nonatomic) float downsampling; // @synthesize downsampling=_downsampling;
- (id)init;
@property(nonatomic) float rangeReductionFactor;
@property(nonatomic) float saturation; // @synthesize saturation;
- (void)setInputSize:(struct CGSize)arg1 atIndex:(int)arg2;

@end

