//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface KZPropertyMapper : NSObject
{
}

+ (id)boxValueAsDate:(id)arg1;
+ (id)boxValueAsSelectorOnTarget:(id)arg1 value:(id)arg2 params:(id)arg3;
+ (id)boxValueAsURL:(id)arg1;
+ (id)dateFormatter;
+ (void)logIgnoredValues:(BOOL)arg1;
+ (BOOL)mapValue:(id)arg1 toInstance:(id)arg2 usingDescriptor:(id)arg3 sourceKey:(id)arg4;
+ (BOOL)mapValue:(id)arg1 toInstance:(id)arg2 usingMapping:(id)arg3 sourceKey:(id)arg4;
+ (BOOL)mapValue:(id)arg1 toInstance:(id)arg2 usingMapping:(id)arg3 sourcePropertyName:(id)arg4;
+ (BOOL)mapValue:(id)arg1 toInstance:(id)arg2 usingStringMapping:(id)arg3 sourceKey:(id)arg4;
+ (BOOL)mapValuesFrom:(id)arg1 toInstance:(id)arg2 usingMapping:(id)arg3;
+ (BOOL)mapValuesFrom:(id)arg1 toInstance:(id)arg2 usingMapping:(id)arg3 errors:(id *)arg4;
+ (BOOL)mapValuesFromArray:(id)arg1 toInstance:(id)arg2 usingMapping:(id)arg3;
+ (BOOL)mapValuesFromDictionary:(id)arg1 toInstance:(id)arg2 usingMapping:(id)arg3;
+ (BOOL)setValue:(id)arg1 onInstance:(id)arg2 usingKeyPath:(id)arg3 sourceKey:(id)arg4;
+ (BOOL)validateMapping:(id)arg1 withMappingValue:(id)arg2 onInstance:(id)arg3 sourceKey:(id)arg4;
+ (id)validateMapping:(id)arg1 withValues:(id)arg2;
+ (id)validateMapping:(id)arg1 withValuesArray:(id)arg2;
+ (id)validateMapping:(id)arg1 withValuesDictionary:(id)arg2;

@end

