//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MQTTEncoder, NSData, NSError;

@protocol MQTTEncoderDelegate <NSObject>
- (void)encoder:(MQTTEncoder *)arg1 handleEvent:(int)arg2 error:(NSError *)arg3;
- (void)encoder:(MQTTEncoder *)arg1 sending:(int)arg2 qos:(int)arg3 retained:(BOOL)arg4 duped:(BOOL)arg5 mid:(unsigned short)arg6 data:(NSData *)arg7;
@end

