//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@interface NSDictionary (UMKURLEncoding)
+ (id)umk_dictionaryWithURLEncodedParameterString:(id)arg1;
+ (id)umk_dictionaryWithURLEncodedParameterString:(id)arg1 encoding:(unsigned int)arg2;
- (id)umk_URLEncodedParameterString;
- (id)umk_URLEncodedParameterStringWithEncoding:(unsigned int)arg1;
- (BOOL)umk_isValidURLEncodedParameterDictionary;
- (BOOL)umk_isValidURLEncodedParameterObject;
- (id)umk_parameterPairsWithKey:(id)arg1;
@end

