//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSError.h"

@interface NSError (TNDRPurchaseRequest)
+ (id)purchaseVerificationRequestBadServerResponse;
+ (id)purchaseVerificationRequestCantAssignToCurrentUser;
+ (id)purchaseVerificationRequestClientTimeOut;
+ (id)purchaseVerificationRequestFailedUserPositionInvalid;
+ (id)purchaseVerificationRequestInvalidServerStatus;
+ (id)purchaseVerificationRequestInvalidStatusWithJSON:(id)arg1;
+ (id)purchaseVerificationRequestNoActivePurchases;
+ (id)purchaseVerificationRequestServerTimeOut;
+ (id)purchaseVerificationRequestUnknownServerError:(id)arg1;
+ (id)purchaseVerificationRequestUnknownServerStatusWithJSON:(id)arg1;
+ (id)purchasesRequestBadServerResponse;
+ (id)purchasesRequestCancelledByClientTimeOut;
+ (id)purchasesRequestInvalidStatusWithJSON:(id)arg1;
+ (id)purchasesRequestNoActivePurchases;
+ (id)purchasesRequestServerTimeOut;
+ (id)purchasesRequestUnknownServerError:(id)arg1;
+ (id)verificationFailedUnableToCompleteForRestoreRequest;
+ (id)verificationFailedUnabletoCompleteForPurchaseRequest;
@end

