//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@interface NSManagedObject (Introspective)
+ (id)uniqueAttributeFromContext:(id)arg1;
+ (id)uniqueKeyFromContext:(id)arg1;
+ (id)uniquelyMappedKeyFromContext:(id)arg1;
- (void)addManagedObject:(id)arg1 toCollection:(id)arg2;
- (id)managedObjectMatchingValue:(id)arg1 forKey:(id)arg2 destinationKey:(id)arg3;
- (void)safeSetAttributesForKeysWithDictionary:(id)arg1 dateFormatter:(id)arg2;
- (void)safeSetRelationshipsForKeysWithDictionary:(id)arg1 dateFormatter:(id)arg2;
- (void)safeSetValuesForKeysWithDictionary:(id)arg1 dateFormatter:(id)arg2;
@end

