//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (TNDRMomentModelLikes)
- (id)_formatLikesJSON:(id)arg1 withMomentID:(id)arg2;
- (void)_handleLikesRetrievalSuccessWithJSON:(id)arg1 forMomentWithID:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)retrieveMomentLikesForMomentWithID:(id)arg1 completion:(CDUnknownBlockType)arg2;
@end

