//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURL.h"

@interface NSURL (UMKQueryParameters)
+ (id)umk_URLWithString:(id)arg1 parameters:(id)arg2;
+ (id)umk_URLWithString:(id)arg1 parameters:(id)arg2 relativeToURL:(id)arg3;
- (id)umk_initWithString:(id)arg1 parameters:(id)arg2;
- (id)umk_initWithString:(id)arg1 parameters:(id)arg2 relativeToURL:(id)arg3;
@end

