//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSURL;

@interface OAL_AsyncALBufferLoadOperation : NSOperation
{
    NSURL *url;
    _Bool reduceToMono;
    id target;
    SEL selector;
}

+ (id)operationWithUrl:(id)arg1 reduceToMono:(_Bool)arg2 target:(id)arg3 selector:(SEL)arg4;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithUrl:(id)arg1 reduceToMono:(_Bool)arg2 target:(id)arg3 selector:(SEL)arg4;
- (void)main;

@end

