//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "OALSuspendManager.h"

@class NSArray, NSMutableArray, NSTimer, OALSuspendHandler;

@interface OALAudioTracks : NSObject <OALSuspendManager>
{
    NSMutableArray *tracks;
    _Bool muted;
    _Bool paused;
    NSTimer *deviceTimePoller;
    OALSuspendHandler *suspendHandler;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (void)purgeSharedInstance;
+ (id)sharedInstance;
+ (id)sharedInstanceNoSynch;
+ (id)sharedInstanceSynch;
- (void).cxx_destruct;
- (void)addSuspendListener:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)init;
@property(nonatomic) _Bool interrupted;
@property(nonatomic) _Bool manuallySuspended;
@property(nonatomic) _Bool muted;
- (void)notifyTrackDeallocating:(id)arg1;
- (void)notifyTrackInitializing:(id)arg1;
@property(nonatomic) _Bool paused;
- (void)pollDeviceTime;
- (void)removeSuspendListener:(id)arg1;
- (void)stopAllTracks;
@property(readonly, nonatomic) _Bool suspended;
@property(readonly, retain, nonatomic) NSArray *tracks; // @synthesize tracks;

@end

