//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OALAction.h"

@interface OALEaseAction : OALAction
{
    OALAction *action_;
    CDUnknownFunctionPointerType easeFunction_;
}

+ (id)actionWithShape:(int)arg1 phase:(int)arg2 action:(id)arg3;
+ (CDUnknownFunctionPointerType)easeFunctionForShape:(int)arg1 phase:(int)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) OALAction *action; // @synthesize action=action_;
- (void)dealloc;
@property(nonatomic) CDUnknownFunctionPointerType easeFunction; // @synthesize easeFunction=easeFunction_;
- (id)initWithShape:(int)arg1 phase:(int)arg2 action:(id)arg3;
- (void)prepareWithTarget:(id)arg1;
- (void)startAction;
- (void)stopAction;
- (void)updateCompletion:(float)arg1;

@end

