//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface OALSuspendHandler : NSObject
{
    NSMutableArray *listeners;
    NSMutableArray *manualSuspendStates;
    SEL suspendStatusChangeSelector;
    _Bool manualSuspendLock;
    _Bool interruptLock;
    id suspendStatusChangeTarget;
}

+ (id)handlerWithTarget:(id)arg1 selector:(SEL)arg2;
- (void).cxx_destruct;
- (void)addSuspendListener:(id)arg1;
- (void)dealloc;
- (id)initWithTarget:(id)arg1 selector:(SEL)arg2;
@property(nonatomic) _Bool interrupted;
@property(nonatomic) _Bool manuallySuspended;
- (void)removeSuspendListener:(id)arg1;
@property(nonatomic) id suspendStatusChangeTarget; // @synthesize suspendStatusChangeTarget;
@property(readonly, nonatomic) _Bool suspended;

@end

