//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextView.h"

#import "UITextViewDelegate.h"

@class NSString;

@interface PSPDFTextView : UITextView <UITextViewDelegate>
{
    id <UITextViewDelegate> _realDelegate;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)ensureCaretIsVisibleWithReplacementText:(id)arg1;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (id)initWithFrame:(struct CGRect)arg1 textContainer:(id)arg2;
- (id)methodSignatureForSelector:(SEL)arg1;
@property(nonatomic) __weak id <UITextViewDelegate> realDelegate; // @synthesize realDelegate=_realDelegate;
- (BOOL)respondsToSelector:(SEL)arg1;
- (void)scheduleScrollToVisibleCaretWithDelay:(double)arg1;
- (void)scrollRangeToVisibleConsideringInsets:(struct _NSRange)arg1 animated:(BOOL)arg2;
- (void)scrollRectToVisibleConsideringInsets:(struct CGRect)arg1 animated:(BOOL)arg2;
- (void)scrollToVisibleCaret;
- (void)scrollToVisibleCaretAnimated:(BOOL)arg1;
- (void)setDelegate:(id)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidChangeSelection:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

