//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, SMCalloutBackgroundView, UIButton, UILabel;

@interface SMCalloutView : UIView
{
    BOOL _popupCancelled;
    id <SMCalloutViewDelegate> _delegate;
    NSString *_title;
    NSString *_subtitle;
    UIView *_leftAccessoryView;
    UIView *_rightAccessoryView;
    unsigned int _permittedArrowDirection;
    unsigned int _currentArrowDirection;
    SMCalloutBackgroundView *_backgroundView;
    UIView *_titleView;
    UIView *_subtitleView;
    UIView *_contentView;
    int _presentAnimation;
    int _dismissAnimation;
    UIButton *_containerView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    struct CGPoint _calloutOffset;
    struct UIEdgeInsets _constrainedInsets;
}

+ (id)platformCalloutView;
- (void).cxx_destruct;
- (void)animationDidStart:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (id)animationWithType:(int)arg1 presenting:(BOOL)arg2;
@property(retain, nonatomic) SMCalloutBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
- (void)calloutClicked;
- (float)calloutContainerHeight;
- (float)calloutHeight;
@property(nonatomic) struct CGPoint calloutOffset; // @synthesize calloutOffset=_calloutOffset;
@property(nonatomic) struct UIEdgeInsets constrainedInsets; // @synthesize constrainedInsets=_constrainedInsets;
@property(retain, nonatomic) UIButton *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) unsigned int currentArrowDirection; // @synthesize currentArrowDirection=_currentArrowDirection;
- (id)defaultBackgroundView;
@property(nonatomic) id <SMCalloutViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) int dismissAnimation; // @synthesize dismissAnimation=_dismissAnimation;
- (void)dismissCalloutAnimated:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (float)innerContentMarginLeft;
- (float)innerContentMarginRight;
- (void)layoutSubviews;
- (float)leftAccessoryMargin;
@property(retain, nonatomic) UIView *leftAccessoryView; // @synthesize leftAccessoryView=_leftAccessoryView;
- (struct CGSize)offsetToContainRect:(struct CGRect)arg1 inRect:(struct CGRect)arg2;
@property(nonatomic) unsigned int permittedArrowDirection; // @synthesize permittedArrowDirection=_permittedArrowDirection;
@property(nonatomic) BOOL popupCancelled; // @synthesize popupCancelled=_popupCancelled;
@property(nonatomic) int presentAnimation; // @synthesize presentAnimation=_presentAnimation;
- (void)presentCalloutFromRect:(struct CGRect)arg1 inLayer:(id)arg2 constrainedToLayer:(id)arg3 animated:(BOOL)arg4;
- (void)presentCalloutFromRect:(struct CGRect)arg1 inLayer:(id)arg2 ofView:(id)arg3 constrainedToLayer:(id)arg4 animated:(BOOL)arg5;
- (void)presentCalloutFromRect:(struct CGRect)arg1 inView:(id)arg2 constrainedToView:(id)arg3 animated:(BOOL)arg4;
- (void)rebuildSubviews;
- (void)removeFromParent;
- (float)rightAccessoryMargin;
@property(retain, nonatomic) UIView *rightAccessoryView; // @synthesize rightAccessoryView=_rightAccessoryView;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UIView *subtitleView; // @synthesize subtitleView=_subtitleView;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *titleView; // @synthesize titleView=_titleView;
- (void)shouldHighlight;
- (void)shouldNotHighlight;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)subtitleViewOrDefault;
- (id)titleViewOrDefault;

@end

