//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SMCalloutView.h"

@interface SMClassicCalloutView : SMCalloutView
{
}

- (void)animationDidStart:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (id)animationWithType:(int)arg1 presenting:(BOOL)arg2;
- (float)calloutHeight;
- (float)centeredPositionOfView:(id)arg1 ifSmallerThan:(float)arg2;
- (float)centeredPositionOfView:(id)arg1 relativeToView:(id)arg2;
- (id)defaultBackgroundView;
- (void)dismissCalloutAnimated:(BOOL)arg1;
- (float)innerContentMarginLeft;
- (float)innerContentMarginRight;
- (void)layoutSubviews;
- (struct CGSize)offsetToContainRect:(struct CGRect)arg1 inRect:(struct CGRect)arg2;
- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)presentCalloutFromRect:(struct CGRect)arg1 inLayer:(id)arg2 constrainedToLayer:(id)arg3 animated:(BOOL)arg4;
- (void)presentCalloutFromRect:(struct CGRect)arg1 inLayer:(id)arg2 ofView:(id)arg3 constrainedToLayer:(id)arg4 animated:(BOOL)arg5;
- (void)presentCalloutFromRect:(struct CGRect)arg1 inView:(id)arg2 constrainedToView:(id)arg3 animated:(BOOL)arg4;
- (void)rebuildSubviews;
- (void)removeFromParent;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)subtitleViewOrDefault;
- (id)titleViewOrDefault;

@end

