//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFHTTPSessionManager.h"

@interface SPKHTTPClient : AFHTTPSessionManager
{
}

+ (id)sharedHTTPClient;
- (id)initWithBaseURL:(id)arg1;
- (id)performRequestWithPath:(id)arg1 method:(id)arg2 contents:(id)arg3 completion:(CDUnknownBlockType)arg4 enqueue:(BOOL)arg5;
- (void)sendDeviceInformation:(id)arg1 endpoint:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)sendEvents:(id)arg1 endpoint:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setup;

@end

