//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSArray, NSMutableArray, SVSegmentedThumb, UIColor, UIFont, UIImage;

@interface SVSegmentedControl : UIControl
{
    BOOL _animateToInitialSelection;
    BOOL _crossFadeLabelsOnDrag;
    BOOL _mustSlideToChange;
    BOOL _trackingThumb;
    BOOL _moved;
    BOOL _activated;
    CDUnknownBlockType _changeHandler;
    NSArray *_sectionTitles;
    NSArray *_sectionImages;
    SVSegmentedThumb *_thumb;
    unsigned int _selectedSegmentIndex;
    float _minimumOverlapToChange;
    UIColor *_backgroundTintColor;
    UIImage *_backgroundImage;
    float _height;
    float _cornerRadius;
    UIFont *_font;
    UIColor *_textColor;
    UIColor *_textShadowColor;
    UIColor *_innerShadowColor;
    UIColor *_tintColor;
    NSMutableArray *_thumbRects;
    NSMutableArray *_accessibilityElements;
    unsigned int _snapToIndex;
    float _halfSize;
    float _dragOffset;
    float _segmentWidth;
    float _thumbHeight;
    struct CGSize _textShadowOffset;
    struct UIEdgeInsets _touchTargetMargins;
    struct UIEdgeInsets _thumbEdgeInset;
    struct UIEdgeInsets _titleEdgeInsets;
}

- (void).cxx_destruct;
- (id)accessibilityElementAtIndex:(int)arg1;
- (int)accessibilityElementCount;
@property(retain, nonatomic) NSMutableArray *accessibilityElements; // @synthesize accessibilityElements=_accessibilityElements;
- (void)activate;
@property(nonatomic) BOOL activated; // @synthesize activated=_activated;
@property(nonatomic) BOOL animateToInitialSelection; // @synthesize animateToInitialSelection=_animateToInitialSelection;
@property(retain, nonatomic) UIImage *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(retain, nonatomic) UIColor *backgroundTintColor; // @synthesize backgroundTintColor=_backgroundTintColor;
- (BOOL)beginTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)cancelTrackingWithEvent:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType changeHandler; // @synthesize changeHandler=_changeHandler;
- (BOOL)continueTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
@property(nonatomic) float cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) BOOL crossFadeLabelsOnDrag; // @synthesize crossFadeLabelsOnDrag=_crossFadeLabelsOnDrag;
- (void)crossFadeThumbContent;
@property(nonatomic) float dragOffset; // @synthesize dragOffset=_dragOffset;
- (void)drawInnerGlowWithPaths:(id)arg1 bounds:(struct CGRect)arg2 color:(id)arg3 offset:(struct CGSize)arg4 blur:(float)arg5;
- (void)drawRect:(struct CGRect)arg1;
- (void)endTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
@property(retain, nonatomic) UIFont *font; // @synthesize font=_font;
@property(nonatomic) float halfSize; // @synthesize halfSize=_halfSize;
@property(nonatomic) float height; // @synthesize height=_height;
- (id)imageForSectionIndex:(unsigned int)arg1;
- (int)indexOfAccessibilityElement:(id)arg1;
- (id)initWithSectionTitles:(id)arg1;
@property(retain, nonatomic) UIColor *innerShadowColor; // @synthesize innerShadowColor=_innerShadowColor;
- (id)invertedImageWithMask:(id)arg1 color:(id)arg2;
- (id)maskWithPaths:(id)arg1 bounds:(struct CGRect)arg2;
@property(nonatomic) float minimumOverlapToChange; // @synthesize minimumOverlapToChange=_minimumOverlapToChange;
- (void)moveThumbToIndex:(unsigned int)arg1 animate:(BOOL)arg2;
@property(nonatomic) BOOL moved; // @synthesize moved=_moved;
@property(nonatomic) BOOL mustSlideToChange; // @synthesize mustSlideToChange=_mustSlideToChange;
- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)sectionImage:(id)arg1 withTintColor:(id)arg2;
@property(retain, nonatomic) NSArray *sectionImages; // @synthesize sectionImages=_sectionImages;
@property(retain, nonatomic) NSArray *sectionTitles; // @synthesize sectionTitles=_sectionTitles;
@property(nonatomic) float segmentWidth; // @synthesize segmentWidth=_segmentWidth;
@property(nonatomic) unsigned int selectedIndex;
@property(nonatomic) unsigned int selectedSegmentIndex; // @synthesize selectedSegmentIndex=_selectedSegmentIndex;
- (void)setBounds:(struct CGRect)arg1;
- (void)setCenter:(struct CGPoint)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)setSelectedIndex:(unsigned int)arg1 animated:(BOOL)arg2;
- (void)setSelectedSegmentIndex:(unsigned int)arg1 animated:(BOOL)arg2;
@property(nonatomic) unsigned int snapToIndex; // @synthesize snapToIndex=_snapToIndex;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) UIColor *textShadowColor; // @synthesize textShadowColor=_textShadowColor;
@property(nonatomic) struct CGSize textShadowOffset; // @synthesize textShadowOffset=_textShadowOffset;
@property(retain, nonatomic) SVSegmentedThumb *thumb; // @synthesize thumb=_thumb;
@property(nonatomic) struct UIEdgeInsets thumbEdgeInset; // @synthesize thumbEdgeInset=_thumbEdgeInset;
@property(nonatomic) float thumbHeight; // @synthesize thumbHeight=_thumbHeight;
@property(retain, nonatomic) NSMutableArray *thumbRects; // @synthesize thumbRects=_thumbRects;
- (void)setThumbSecondValuesForIndex:(unsigned int)arg1;
- (void)setThumbValuesForIndex:(unsigned int)arg1;
@property(retain, nonatomic) UIColor *tintColor; // @synthesize tintColor=_tintColor;
@property(nonatomic) struct UIEdgeInsets titleEdgeInsets; // @synthesize titleEdgeInsets=_titleEdgeInsets;
@property(nonatomic) struct UIEdgeInsets touchTargetMargins; // @synthesize touchTargetMargins=_touchTargetMargins;
@property(nonatomic) BOOL trackingThumb; // @synthesize trackingThumb=_trackingThumb;
- (void)setupAccessibility;
- (void)sizeToFit;
- (void)snap:(BOOL)arg1;
- (void)toggle;
- (void)updateSectionRects;
- (void)willMoveToSuperview:(id)arg1;

@end

