//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TNDRDialogViewController.h"

#import "TNDRPaywallManagerDelegate.h"
#import "TNDRRecommendationViewControllerRecsSessionTracking.h"

@class NSAttributedString, NSString, NSTimer, TNDRLikeGamepadButton, TNDRPassportPaywallViewModel;

@interface TNDRRateLimitRoadblockDialogViewController : TNDRDialogViewController <TNDRPaywallManagerDelegate, TNDRRecommendationViewControllerRecsSessionTracking>
{
    NSString *_otherID;
    id <TNDRTinderPlusPaywallViewControllerDelegate> _paywallDelegate;
    NSTimer *_roadblockCountdownTimer;
    TNDRLikeGamepadButton *_heartDrainingView;
    TNDRPassportPaywallViewModel *_paywallViewModel;
}

+ (id)viewControllerNavigationKey;
- (void).cxx_destruct;
- (id)buttonAttributedTitleWithPrice;
- (void)handleTapInView:(id)arg1;
- (void)handleUserDidSelectPurchaseFromDialog:(id)arg1;
@property(retain, nonatomic) TNDRLikeGamepadButton *heartDrainingView; // @synthesize heartDrainingView=_heartDrainingView;
- (BOOL)inboundSegueShouldTriggerRecsSessionEnd;
- (id)initWithOtherID:(id)arg1;
@property(copy, nonatomic) NSString *otherID; // @synthesize otherID=_otherID;
@property(nonatomic) __weak id <TNDRTinderPlusPaywallViewControllerDelegate> paywallDelegate; // @synthesize paywallDelegate=_paywallDelegate;
- (void)paywallPurchaseCancelled;
- (void)paywallPurchaseFailed;
- (void)paywallPurchaseNotAllowed;
- (void)paywallPurchaseSucceeded;
@property(retain, nonatomic) TNDRPassportPaywallViewModel *paywallViewModel; // @synthesize paywallViewModel=_paywallViewModel;
- (void)prepareRoadblockForPresentationWithCompletion:(CDUnknownBlockType)arg1;
- (id)productInfo;
- (void)requestDismissal;
- (void)resizeFooterViewAfterUpdatedButtonHeight;
@property(readonly, nonatomic) NSString *roadBlockBaseDescription;
@property(readonly, nonatomic) NSAttributedString *roadBlockTimeLeft;
- (id)roadBlockTimeLeftWithTimeInterval:(double)arg1;
@property(readonly, nonatomic) NSString *roadBlockTitle;
@property(retain, nonatomic) NSTimer *roadblockCountdownTimer; // @synthesize roadblockCountdownTimer=_roadblockCountdownTimer;
- (id)roadblockTimeLeftAttributedStringForText:(id)arg1;
- (void)setupFooterView;
- (void)setupFooterViewButtonWithPrice;
- (void)setupHeaderView;
- (void)stopUpdateTimer:(id)arg1;
- (void)updateDetailText:(id)arg1;
- (void)updateDetailTextForInvalidDeviceTime;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (id)windowForHUD;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

