//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CLGeocoder, NSArray;

@interface TNDRPassportMapSearchCoordinateViewModel : NSObject
{
    NSArray *_mapSearchResults;
    CLGeocoder *_geocoder;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CLGeocoder *geocoder; // @synthesize geocoder=_geocoder;
- (id)init;
@property(readonly, nonatomic) NSArray *mapSearchResults; // @synthesize mapSearchResults=_mapSearchResults;
- (void)performSearchWithLocation:(id)arg1;
- (void)performSearchWithLocation:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

