//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSIndexPath, NSString, TNDRCardCell, TNDRCardCellManager;

@protocol TNDRCardCellManagerDelegate <NSObject>
- (void)cellManager:(TNDRCardCellManager *)arg1 batchDeleteIndexPaths:(NSArray *)arg2 completion:(void (^)(BOOL))arg3;
- (void)cellManager:(TNDRCardCellManager *)arg1 batchInsertIndexPaths:(NSArray *)arg2 completion:(void (^)(BOOL))arg3;
- (TNDRCardCell *)cellManager:(TNDRCardCellManager *)arg1 cardCellAtIndexPath:(NSIndexPath *)arg2;
- (void)cellManager:(TNDRCardCellManager *)arg1 insertItemAtIndexPath:(NSIndexPath *)arg2;
- (void)cellManager:(TNDRCardCellManager *)arg1 removeItemAtIndexPath:(NSIndexPath *)arg2;
- (void)cellManagerDidFinishChangingContent:(TNDRCardCellManager *)arg1;
- (NSString *)reuseIdentifierForCellManager:(TNDRCardCellManager *)arg1;
@end

