//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CCNodeColor.h"

@class CCRenderTexture, NSMutableArray, NSTimer, UIColor, UIPanGestureRecognizer, UITapGestureRecognizer;

@interface TNDRLineDrawGL : CCNodeColor
{
    NSMutableArray *points;
    NSMutableArray *velocities;
    NSMutableArray *circlesPoints;
    NSMutableArray *colors;
    BOOL connectingLine;
    struct CGPoint prevC;
    struct CGPoint prevD;
    struct CGPoint prevG;
    struct CGPoint prevI;
    float overdraw;
    CCRenderTexture *renderTexture;
    BOOL finishingLine;
    BOOL buttonsAreHiding;
    NSTimer *timerToReshowControls;
    BOOL isErasing;
    NSMutableArray *smoothedPoints;
    NSMutableArray *savedLines;
    BOOL newSegment;
    UIPanGestureRecognizer *localPanGestureRecognizer;
    UITapGestureRecognizer *localTapGestureRecognizer;
    UIColor *_currentColor;
    float _currentLineThickness;
    id <TNDRDrawing> _delegate;
}

+ (id)scene;
- (void).cxx_destruct;
- (void)addPoint:(struct CGPoint)arg1 withSize:(float)arg2;
- (struct _ccColor4F)asCCColor4F:(id)arg1;
- (id)calculateSmoothLinePoints;
@property(retain, nonatomic) UIColor *currentColor; // @synthesize currentColor=_currentColor;
@property(nonatomic) float currentLineThickness; // @synthesize currentLineThickness=_currentLineThickness;
@property(nonatomic) __weak id <TNDRDrawing> delegate; // @synthesize delegate=_delegate;
- (void)draw;
- (void)draw:(id)arg1 transform:(const union _GLKMatrix4 *)arg2;
- (void)drawLines:(id)arg1 withColor:(struct _ccColor4F)arg2;
- (void)endDrawing;
- (void)endLineAt:(struct CGPoint)arg1 withSize:(float)arg2;
- (void)eraseDrawing;
- (float)extractSize:(id)arg1;
- (void)fillLineEndPointAt:(struct CGPoint)arg1 direction:(struct CGPoint)arg2 radius:(float)arg3 andColor:(struct _ccColor4F)arg4;
- (void)fillLineTriangles:(struct _LineVertex *)arg1 count:(unsigned int)arg2 withColor:(struct _ccColor4F)arg3;
- (void)handlePanGesture:(id)arg1;
- (void)handleTapGesture:(id)arg1;
- (id)init;
- (id)previousColor;
- (void)reset;
- (void)startDrawing;
- (void)startNewLineFrom:(struct CGPoint)arg1 withSize:(float)arg2;
- (void)startTimer;
- (void)timerFired:(id)arg1;
- (void)unDo;

@end

