//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_TNDRLocation.h"

#import "TNDRParsable.h"

@class CLLocation, MKPlacemark, NSString;

@interface TNDRLocation : _TNDRLocation <TNDRParsable>
{
}

+ (id)createLocationFromLocation:(id)arg1 placemark:(id)arg2 inContext:(id)arg3;
+ (id)locationWithPlacemark:(id)arg1;
@property(readonly, nonatomic) CDStruct_2c43369c coordinate;
@property(readonly, nonatomic) CLLocation *location;
@property(readonly, nonatomic) NSString *niceLocationName;
@property(readonly, nonatomic) MKPlacemark *placemark;
- (void)setCoordinate:(CDStruct_2c43369c)arg1;
@property(readonly, nonatomic) NSString *shortLocationName;
- (void)updateFromDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

