//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TNDRCardCell, TNDRUser;

@protocol TNDRCardCellStackControl <NSObject>
- (void)dismissCardCellWithSwipeLeft:(TNDRCardCell *)arg1 showStamp:(BOOL)arg2;
- (void)dismissCardCellWithSwipeRight:(TNDRCardCell *)arg1 showStamp:(BOOL)arg2;
- (void)returnCardCellToCenter:(TNDRCardCell *)arg1;
- (void)returnRecommendationToCenterForRateLimiting:(TNDRUser *)arg1;
@end

