//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TNDRCardCellMediatorDelegate.h"
#import "TNDRRecommendationViewControllerCardCellInteractionHandler.h"
#import "UICollectionViewDataSource.h"

@class NSString;

@interface TNDRCardCellManager : NSObject <UICollectionViewDataSource, TNDRCardCellMediatorDelegate, TNDRRecommendationViewControllerCardCellInteractionHandler>
{
    id <TNDRCardCellManagerDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <TNDRCardCellManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

