//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIWebViewDelegate.h"

@class NSString, NSURL, UIActivityIndicatorView, UINavigationBar, UIWebView;

@interface TNDRWebViewController : UIViewController <UIWebViewDelegate>
{
    NSURL *_url;
    UIWebView *_webView;
    UINavigationBar *_navigationBar;
    float _topOffset;
    UIActivityIndicatorView *_spinner;
    BOOL _isModal;
    id _delegate;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(retain, nonatomic) id delegate; // @synthesize delegate=_delegate;
- (void)didReceiveMemoryWarning;
- (void)doneButtonTapped;
- (id)initWithURL:(id)arg1;
@property(retain, nonatomic) UINavigationBar *navigationBar; // @synthesize navigationBar=_navigationBar;
- (void)setupNavBar;
- (void)setupWebView;
- (void)showURL;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

