//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SMCalloutView.h"

@interface TNDRPassportMapViewCalloutView : SMCalloutView
{
}

- (id)initWithFrame:(struct CGRect)arg1;
- (id)subtitleViewOrDefault;
- (id)titleViewOrDefault;

@end

