//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TNDRDialogViewController.h"

@class NSAttributedString, TNDRUser, TTTAttributedLabel, UIButton, UIImage;

@interface TNDRUserReportedDialogViewController : TNDRDialogViewController
{
    TNDRUser *_user;
    NSAttributedString *_titleText;
    NSAttributedString *_detailText;
    TTTAttributedLabel *_titleTextLabel;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) UIButton *confirmationButton;
@property(retain, nonatomic) NSAttributedString *detailText; // @synthesize detailText=_detailText;
- (void)handleConfirmationButtonTap;
@property(readonly, nonatomic) UIImage *reportIcon;
@property(retain, nonatomic) NSAttributedString *titleText; // @synthesize titleText=_titleText;
@property(retain, nonatomic) TNDRUser *user; // @synthesize user=_user;
- (void)setupControls;
- (void)setupTitleAndDetail;
- (void)setupViews;
@property(readonly, nonatomic) TTTAttributedLabel *titleTextLabel; // @synthesize titleTextLabel=_titleTextLabel;
- (void)viewDidLoad;

@end

