//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CALayer, NSTimer, UIImageView, UILabel;

@interface TNDRNoRecommendationsView : UIView
{
    NSTimer *_timer;
    CALayer *_containerLayer;
    UIImageView *_avatarImageView;
    BOOL _avatarLoaded;
    BOOL _nobodyAvailable;
    UILabel *_nobodyLabel;
}

- (void).cxx_destruct;
- (void)animateIn:(CDUnknownBlockType)arg1;
- (void)animateOut:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (void)handleApplicationDidEnterBackgroundNotification:(id)arg1;
- (void)handleNobodyNearbyNotification:(id)arg1;
- (void)handleTap:(id)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, getter=isNobodyAvailable) BOOL nobodyAvailable; // @synthesize nobodyAvailable=_nobodyAvailable;
- (void)layoutSubviews;
- (void)loadAvatarURL:(id)arg1;
@property(retain, nonatomic) UILabel *nobodyLabel; // @synthesize nobodyLabel=_nobodyLabel;
- (void)ping:(id)arg1;
- (void)resetAvatar:(id)arg1;
- (void)setup;
- (void)setupNotifications;
- (void)startPingTimer;
- (void)stopPingTimer;
- (void)updateAvatar:(id)arg1;

@end

