//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TNDRURLNavigableProtocol.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextViewDelegate.h"

@class NSIndexPath, NSString, TNDRMatch, TNDRMoment, TNDRUser, UIBarButtonItem, UIImageView, UINavigationBar, UITableView, UITextView;

@interface TNDRReportViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UITextViewDelegate, TNDRURLNavigableProtocol>
{
    NSIndexPath *_lastCheckedIndexPath;
    UITextView *_placeholderTextView;
    BOOL _otherExplainSelected;
    id _delegate;
    TNDRMatch *_match;
    TNDRMoment *_moment;
    TNDRUser *_user;
    int _reportFromType;
    UITableView *_tableView;
    UIBarButtonItem *_reportBarButtonItem;
    UIImageView *_otherReasonInputView;
    UITextView *_otherReasonTextView;
    UINavigationBar *_navigationBar;
}

+ (id)viewControllerNavigationKey;
- (void).cxx_destruct;
- (void)cancelButtonTapped:(id)arg1;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
- (void)didReceiveMemoryWarning;
- (id)init;
@property(retain, nonatomic) TNDRMatch *match; // @synthesize match=_match;
@property(retain, nonatomic) TNDRMoment *moment; // @synthesize moment=_moment;
@property(retain, nonatomic) UINavigationBar *navigationBar; // @synthesize navigationBar=_navigationBar;
- (int)numberOfSectionsInTableView:(id)arg1;
@property(retain, nonatomic) UIImageView *otherReasonInputView; // @synthesize otherReasonInputView=_otherReasonInputView;
@property(retain, nonatomic) UITextView *otherReasonTextView; // @synthesize otherReasonTextView=_otherReasonTextView;
- (int)preferredStatusBarStyle;
@property(retain, nonatomic) UIBarButtonItem *reportBarButtonItem; // @synthesize reportBarButtonItem=_reportBarButtonItem;
- (void)reportButtonTapped:(id)arg1;
@property(nonatomic) int reportFromType; // @synthesize reportFromType=_reportFromType;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) TNDRUser *user; // @synthesize user=_user;
- (void)setup;
- (void)setupNavigationBar;
- (void)showExplainOtherView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (void)textViewDidChange:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

