//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIColor, UIImageView;

@interface TNDRReportTableCell : UITableViewCell
{
    UIImageView *_backgroundView;
    UIImageView *_selectedBackgroundView;
    UIImageView *_chevronView;
    UIColor *_normalTextColor;
    UIColor *_lightTextColor;
    int _reportReason;
}

- (void).cxx_destruct;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
@property(nonatomic) int reportReason; // @synthesize reportReason=_reportReason;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setup;

@end

