//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TNDRCardCellManagerDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSMapTable, NSSortDescriptor, NSString, TNDRAdCardCellManager, TNDRCardCellMediatorCounter, TNDRUserCardCellManager, UICollectionView;

@interface TNDRCardCellMediator : NSObject <UICollectionViewDataSource, UICollectionViewDelegate, TNDRCardCellManagerDelegate>
{
    BOOL _rebuildingCardStack;
    UICollectionView *_collectionView;
    id <TNDRCardCellControlDependencies> _dependencyContext;
    TNDRCardCellMediatorCounter *_counter;
    NSMapTable *_cardCellKeyMap;
    NSMapTable *_reuseIdentifierMap;
    TNDRUserCardCellManager *_userCardCellManager;
    TNDRAdCardCellManager *_adCardCellManager;
    NSSortDescriptor *_ascendingIndexSetSortDescriptor;
    NSSortDescriptor *_descendingIndexSetSortDescriptor;
}

- (void).cxx_destruct;
@property(retain, nonatomic) TNDRAdCardCellManager *adCardCellManager; // @synthesize adCardCellManager=_adCardCellManager;
@property(retain, nonatomic) NSSortDescriptor *ascendingIndexSetSortDescriptor; // @synthesize ascendingIndexSetSortDescriptor=_ascendingIndexSetSortDescriptor;
@property(retain, nonatomic) NSMapTable *cardCellKeyMap; // @synthesize cardCellKeyMap=_cardCellKeyMap;
- (void)cellManager:(id)arg1 batchDeleteIndexPaths:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)cellManager:(id)arg1 batchInsertIndexPaths:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)cellManager:(id)arg1 cardCellAtIndexPath:(id)arg2;
- (void)cellManager:(id)arg1 insertItemAtIndexPath:(id)arg2;
- (void)cellManager:(id)arg1 removeItemAtIndexPath:(id)arg2;
- (void)cellManagerDidFinishChangingContent:(id)arg1;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
@property(retain, nonatomic) TNDRCardCellMediatorCounter *counter; // @synthesize counter=_counter;
@property(nonatomic) __weak id <TNDRCardCellControlDependencies> dependencyContext; // @synthesize dependencyContext=_dependencyContext;
@property(retain, nonatomic) NSSortDescriptor *descendingIndexSetSortDescriptor; // @synthesize descendingIndexSetSortDescriptor=_descendingIndexSetSortDescriptor;
- (void)didFinishRebuildingCardStack;
- (id)initWithCollectionView:(id)arg1 dependencyContext:(id)arg2;
@property(nonatomic, getter=isRebuildingCardStack) BOOL rebuildingCardStack; // @synthesize rebuildingCardStack=_rebuildingCardStack;
- (BOOL)nextThreeCardsInCounterAreUserCards;
- (id)reuseIdentifierForCellManager:(id)arg1;
@property(retain, nonatomic) NSMapTable *reuseIdentifierMap; // @synthesize reuseIdentifierMap=_reuseIdentifierMap;
@property(retain, nonatomic) TNDRUserCardCellManager *userCardCellManager; // @synthesize userCardCellManager=_userCardCellManager;
- (BOOL)shouldAcceptAdCardCells;
- (BOOL)shouldAcceptUserCardCells;
- (id)sortedIndexPaths:(id)arg1 ascending:(BOOL)arg2;
- (void)updateCounterForAdCardCellsInCollectionView:(id)arg1;
- (void)willRebuildCardStackSoon;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

