//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerAnimatedTransitioning.h"

@class NSString, TNDRPassportLocationsListViewController, TNDRRecommendationViewController, UIView;

@interface TNDRPassportLocationsListAnimationController : NSObject <UIViewControllerAnimatedTransitioning>
{
    BOOL _presenting;
    TNDRPassportLocationsListViewController *_locationsListViewController;
    TNDRRecommendationViewController *_recommendationViewController;
    UIView *_passportButtonSuperview;
    struct CGPoint _passportButtonCenter;
}

- (void).cxx_destruct;
- (void)animateTransition:(id)arg1;
- (void)executeDismissalAnimation:(id)arg1;
- (void)executePresentationAnimation:(id)arg1;
@property(nonatomic, getter=isPresenting) BOOL presenting; // @synthesize presenting=_presenting;
@property(nonatomic) __weak TNDRPassportLocationsListViewController *locationsListViewController; // @synthesize locationsListViewController=_locationsListViewController;
@property(nonatomic) struct CGPoint passportButtonCenter; // @synthesize passportButtonCenter=_passportButtonCenter;
@property(nonatomic) __weak UIView *passportButtonSuperview; // @synthesize passportButtonSuperview=_passportButtonSuperview;
@property(nonatomic) __weak TNDRRecommendationViewController *recommendationViewController; // @synthesize recommendationViewController=_recommendationViewController;
- (double)transitionDuration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

