//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "NSFetchedResultsControllerDelegate.h"
#import "TNDRMomentViewerViewControllerDelegate.h"
#import "TNDRMomentsRefreshProtocol.h"
#import "TNDRMyMomentViewerDelegate.h"
#import "TNDRURLNavigableProtocol.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UIViewControllerTransitioningDelegate.h"

@class NSArray, NSFetchedResultsController, NSMutableArray, NSString, TNDRMomentViewerViewController, TNDRMyMomentViewerView, TNDRMyMomentsToMomentViewerAnimationController, UICollectionView, UIImageView, UIView;

@interface TNDRMyMomentsViewController : UIViewController <UICollectionViewDataSource, UICollectionViewDelegate, TNDRMyMomentViewerDelegate, NSFetchedResultsControllerDelegate, UIViewControllerTransitioningDelegate, TNDRMomentViewerViewControllerDelegate, TNDRMomentsRefreshProtocol, TNDRURLNavigableProtocol>
{
    NSString *MomentCellIdentifier;
    BOOL _hasLoadedMoments;
    NSMutableArray *_fetchedObjectChanges;
    id <TNDRMomentsActivityScrollDelegate> _delegate;
    UICollectionView *_collectionView;
    NSArray *_activeMomentsArray;
    NSArray *_inactiveMomentsArray;
    NSFetchedResultsController *_fetchedResultsController;
    TNDRMyMomentViewerView *_momentViewer;
    UIView *_headerViewContainer;
    UIImageView *_emptyGridView;
    TNDRMyMomentsToMomentViewerAnimationController *_toMomentViewerAnimationController;
    TNDRMomentViewerViewController *_momentViewerViewController;
}

+ (id)viewControllerNavigationKey;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *activeMomentsArray; // @synthesize activeMomentsArray=_activeMomentsArray;
- (void)adjustCollectionViewContentInsets;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned int)arg4 newIndexPath:(id)arg5;
- (void)controllerDidChangeContent:(id)arg1;
@property(nonatomic) __weak id <TNDRMomentsActivityScrollDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didCloseMomentViewer;
- (void)didGetMoreLikes:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)didRequestToDeleteMoment:(id)arg1;
- (void)didRequestToShowMomentViewerFor:(id)arg1;
- (void)didRequestToViewLikesForMoment:(id)arg1;
@property(retain, nonatomic) UIImageView *emptyGridView; // @synthesize emptyGridView=_emptyGridView;
@property(retain, nonatomic) NSFetchedResultsController *fetchedResultsController; // @synthesize fetchedResultsController=_fetchedResultsController;
- (void)handleAppForegrounded:(id)arg1;
- (void)handleUserDidLogin:(id)arg1;
- (void)handleUserDidLogout:(id)arg1;
@property(retain, nonatomic) UIView *headerViewContainer; // @synthesize headerViewContainer=_headerViewContainer;
@property(retain, nonatomic) NSArray *inactiveMomentsArray; // @synthesize inactiveMomentsArray=_inactiveMomentsArray;
- (id)init;
- (BOOL)isPrefetched:(id)arg1;
- (id)momentForCellAtIndexPath:(id)arg1;
@property(retain, nonatomic) TNDRMyMomentViewerView *momentViewer; // @synthesize momentViewer=_momentViewer;
@property(nonatomic) __weak TNDRMomentViewerViewController *momentViewerViewController; // @synthesize momentViewerViewController=_momentViewerViewController;
- (float)normalizedOffsetY;
- (int)numberOfSectionsInCollectionView:(id)arg1;
- (void)precacheImageForMoment:(id)arg1;
- (void)presentMomentViewerForMoment:(id)arg1;
- (void)refresh;
- (void)refreshVisibleCells;
- (void)registerNotifications;
- (BOOL)retrieveExpiredStatusAndPrepareCollectionViewForTransitionToIndexPath:(id)arg1 reloadIndexPath:(BOOL)arg2;
- (struct CGRect)scrollToTopAndGetCGRectTargetForTransition;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (BOOL)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
@property(retain, nonatomic) TNDRMyMomentsToMomentViewerAnimationController *toMomentViewerAnimationController; // @synthesize toMomentViewerAnimationController=_toMomentViewerAnimationController;
- (void)setup;
- (void)setupCollectionView;
- (void)setupDataSource;
- (BOOL)shouldReloadCollectionViewToPreventKnownIssue;
- (void)transitionTo:(id)arg1 optionsDict:(id)arg2 animated:(BOOL)arg3 completion:(CDUnknownBlockType)arg4;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;

// Remaining properties
@property(readonly, nonatomic) id <UIViewControllerAnimatedTransitioning> animationController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

