//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSArray, NSString, StyledPageControl, UIButton, UICollectionView, UIImageView, UILabel, UIScrollView, UIView;

@interface TNDRIntroViewController : UIViewController <UICollectionViewDataSource, UICollectionViewDelegate>
{
    BOOL _hasCompletedVerification;
    BOOL _hasPresentedValidation;
    NSArray *_items;
    UIView *_introView;
    UICollectionView *_collectionView;
    UIButton *_loginButton;
    UIButton *_infoButton;
    StyledPageControl *_pageControl;
    UIView *_privacyView;
    UIButton *_closePrivacyButton;
    UIImageView *_privacyLine;
    UILabel *_privacyHeaderLabel;
    UILabel *_bullet1Label;
    UILabel *_bullet2Label;
    UILabel *_bullet3Label;
    UILabel *_bullet4Label;
    UIImageView *_bullet1;
    UIImageView *_bullet2;
    UIImageView *_bullet3;
    UIImageView *_bullet4;
    UIScrollView *_privacyScrollView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *bullet1; // @synthesize bullet1=_bullet1;
@property(retain, nonatomic) UILabel *bullet1Label; // @synthesize bullet1Label=_bullet1Label;
@property(retain, nonatomic) UIImageView *bullet2; // @synthesize bullet2=_bullet2;
@property(retain, nonatomic) UILabel *bullet2Label; // @synthesize bullet2Label=_bullet2Label;
@property(retain, nonatomic) UIImageView *bullet3; // @synthesize bullet3=_bullet3;
@property(retain, nonatomic) UILabel *bullet3Label; // @synthesize bullet3Label=_bullet3Label;
@property(retain, nonatomic) UIImageView *bullet4; // @synthesize bullet4=_bullet4;
@property(retain, nonatomic) UILabel *bullet4Label; // @synthesize bullet4Label=_bullet4Label;
@property(retain, nonatomic) UIButton *closePrivacyButton; // @synthesize closePrivacyButton=_closePrivacyButton;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)handleClosePrivacyTap:(id)arg1;
- (void)handlePrivacyTap:(id)arg1;
- (void)handleSignInButtonTap:(id)arg1;
@property(nonatomic) BOOL hasCompletedVerification; // @synthesize hasCompletedVerification=_hasCompletedVerification;
@property(nonatomic) BOOL hasPresentedValidation; // @synthesize hasPresentedValidation=_hasPresentedValidation;
@property(retain, nonatomic) UIButton *infoButton; // @synthesize infoButton=_infoButton;
- (id)initWithIntroItems:(id)arg1;
@property(retain, nonatomic) UIView *introView; // @synthesize introView=_introView;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
@property(retain, nonatomic) UIButton *loginButton; // @synthesize loginButton=_loginButton;
- (int)numberOfSectionsInCollectionView:(id)arg1;
@property(retain, nonatomic) StyledPageControl *pageControl; // @synthesize pageControl=_pageControl;
- (void)pageControlValueChanged:(id)arg1;
- (void)performAnimationForTransitionToVerification;
- (void)performInitialAnimation;
- (int)preferredStatusBarStyle;
- (void)prepareForDismissalFromSMSVerification;
- (void)prepareForInitialAnimation;
- (void)prepareToPresentVerification:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) UILabel *privacyHeaderLabel; // @synthesize privacyHeaderLabel=_privacyHeaderLabel;
@property(retain, nonatomic) UIImageView *privacyLine; // @synthesize privacyLine=_privacyLine;
@property(retain, nonatomic) UIScrollView *privacyScrollView; // @synthesize privacyScrollView=_privacyScrollView;
@property(retain, nonatomic) UIView *privacyView; // @synthesize privacyView=_privacyView;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)setupPrivacyView;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

