//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TNDRCardCell;

@protocol TNDRRecommendationViewControllerCardCellInteractionHandler <NSObject>
- (void)userSwipedLeftForCardCell:(TNDRCardCell *)arg1;
- (void)userSwipedRightForCardCell:(TNDRCardCell *)arg1;
- (void)userTappedCardCell:(TNDRCardCell *)arg1;
- (void)userTappedInfoButtonForCardCell:(TNDRCardCell *)arg1;
- (void)userTappedLeftAccessoryForCardCell:(TNDRCardCell *)arg1;
- (void)userTappedLeftForCardCell:(TNDRCardCell *)arg1;
- (void)userTappedRightForCardCell:(TNDRCardCell *)arg1;

@optional
- (BOOL)shouldAllowSwipeDismissalForCell:(TNDRCardCell *)arg1 direction:(int)arg2;
@end

