//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSFetchedResultsControllerDelegate.h"
#import "UITableViewDataSource.h"

@class NSFetchedResultsController, NSString, UITableView;

@interface TNDRTableFetchedDataSource : NSObject <UITableViewDataSource, NSFetchedResultsControllerDelegate>
{
    BOOL _paused;
    id <TNDRDataSourceDelegate> _delegate;
    NSFetchedResultsController *_fetchedResultsController;
    NSString *_reuseIdentifier;
    UITableView *_tableView;
}

- (void).cxx_destruct;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned int)arg4 newIndexPath:(id)arg5;
- (void)controllerDidChangeContent:(id)arg1;
- (void)controllerWillChangeContent:(id)arg1;
@property(nonatomic) __weak id <TNDRDataSourceDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSFetchedResultsController *fetchedResultsController; // @synthesize fetchedResultsController=_fetchedResultsController;
- (id)initWithTableView:(id)arg1;
- (int)numberOfSectionsInTableView:(id)arg1;
@property(nonatomic) BOOL paused; // @synthesize paused=_paused;
@property(copy, nonatomic) NSString *reuseIdentifier; // @synthesize reuseIdentifier=_reuseIdentifier;
- (id)selectedItem;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

