//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerAnimatedTransitioning.h"

@class NSString, TNDRMatchesViewController, UIView;

@interface TNDRMatchesToMomentsAnimationController : NSObject <UIViewControllerAnimatedTransitioning>
{
    BOOL _presenting;
    TNDRMatchesViewController *_matchesViewController;
    UIView *_navBarSnapshot;
    double _presentationDuration;
    double _dismissalDuration;
    struct CGRect _cardStartFrameForFullStackAnimation;
}

- (void).cxx_destruct;
- (void)animateTransition:(id)arg1;
@property(nonatomic) struct CGRect cardStartFrameForFullStackAnimation; // @synthesize cardStartFrameForFullStackAnimation=_cardStartFrameForFullStackAnimation;
@property(nonatomic) double dismissalDuration; // @synthesize dismissalDuration=_dismissalDuration;
- (void)executeDismissalAnimation:(id)arg1;
- (void)executePresentationAnimation:(id)arg1;
- (id)init;
@property(nonatomic, getter=isPresenting) BOOL presenting; // @synthesize presenting=_presenting;
@property(retain, nonatomic) TNDRMatchesViewController *matchesViewController; // @synthesize matchesViewController=_matchesViewController;
@property(retain, nonatomic) UIView *navBarSnapshot; // @synthesize navBarSnapshot=_navBarSnapshot;
@property(nonatomic) double presentationDuration; // @synthesize presentationDuration=_presentationDuration;
- (double)transitionDuration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

