//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class TNDRPassportMapSearchViewController, TNDRPassportStackViewController;

@interface TNDRPassportStackContainerView : UIView
{
    TNDRPassportStackViewController *_passportStackViewController;
    TNDRPassportMapSearchViewController *_mapViewController;
}

- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
@property(nonatomic) __weak TNDRPassportMapSearchViewController *mapViewController; // @synthesize mapViewController=_mapViewController;
@property(nonatomic) __weak TNDRPassportStackViewController *passportStackViewController; // @synthesize passportStackViewController=_passportStackViewController;

@end

