//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

#import "UIGestureRecognizerDelegate.h"

@class NSArray, NSString, NSTimer, TNDRNotification, UIButton, UIColor, UIImageView, UILabel, UIPanGestureRecognizer, UITapGestureRecognizer, UIView;

@interface TNDRNotificationWindow : UIWindow <UIGestureRecognizerDelegate>
{
    UIColor *_greenColor;
    UIColor *_blueColor;
    UIColor *_redColor;
    UIColor *_defaultColor;
    UIColor *_redBorderColor;
    UIColor *_greenBorderColor;
    UIColor *_blueBorderColor;
    double _delayTimeNextNotification;
    double _delayTimeAfterTap;
    double _delayTimeAfterTossAway;
    struct CGPoint _startPoint;
    struct CGPoint _curPoint;
    struct CGPoint _maxPoint;
    struct CGPoint _startAbsPoint;
    BOOL _visible;
    BOOL _paused;
    BOOL _presenting;
    UIView *_visibleNotificationView;
    NSArray *_notifications;
    UIView *_bannerView;
    UIView *_bottomBorder;
    UIImageView *_imageView;
    UILabel *_titleLabel;
    UILabel *_detailLabel;
    UIImageView *_accessoryView;
    UIButton *_accessoryButton;
    UIImageView *_gripper;
    UIImageView *_imageViewIcon;
    UITapGestureRecognizer *_bannerTapGR;
    UIPanGestureRecognizer *_bannerPanGR;
    int _currentNotificationType;
    TNDRNotification *_currentNotification;
    NSTimer *_presentNextTimer;
    NSTimer *_tryPresentingTimer;
}

+ (id)notificationWindow;
- (void).cxx_destruct;
- (void)_endPresentingNotifications;
- (void)_hideBannerCompletion:(CDUnknownBlockType)arg1;
- (void)_showBannerCompletion:(CDUnknownBlockType)arg1;
- (void)_tossAwayBannerCompletion:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) UIButton *accessoryButton; // @synthesize accessoryButton=_accessoryButton;
@property(retain, nonatomic) UIImageView *accessoryView; // @synthesize accessoryView=_accessoryView;
- (id)activeDelegate;
- (id)activeViewController;
- (struct CGAffineTransform)affineTransformTranslateUpAndOut;
- (id)applicationKeyWindow;
- (id)avatarImageURLForUser:(id)arg1;
- (struct CGSize)avatarSizeForRoundedBorderedImage;
@property(retain, nonatomic) UIPanGestureRecognizer *bannerPanGR; // @synthesize bannerPanGR=_bannerPanGR;
@property(retain, nonatomic) UITapGestureRecognizer *bannerTapGR; // @synthesize bannerTapGR=_bannerTapGR;
@property(retain, nonatomic) UIView *bannerView; // @synthesize bannerView=_bannerView;
- (void)beginPresentingNotifications;
@property(retain, nonatomic) UIView *bottomBorder; // @synthesize bottomBorder=_bottomBorder;
@property(retain, nonatomic) TNDRNotification *currentNotification; // @synthesize currentNotification=_currentNotification;
@property(nonatomic) int currentNotificationType; // @synthesize currentNotificationType=_currentNotificationType;
- (struct CGRect)defaultBannerFrame;
- (struct CGRect)defaultImageFrame;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
- (int)displayPermissionForNotification:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (BOOL)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
@property(retain, nonatomic) UIImageView *gripper; // @synthesize gripper=_gripper;
- (void)handleBannerPan:(id)arg1;
- (void)handleBannerTap:(id)arg1;
- (void)handleRetryButtonTapped:(id)arg1;
- (void)hideBannerCompletion:(CDUnknownBlockType)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIImageView *imageViewIcon; // @synthesize imageViewIcon=_imageViewIcon;
- (id)initWithFrame:(struct CGRect)arg1;
@property(getter=isPaused) BOOL paused; // @synthesize paused=_paused;
@property(getter=isPresenting) BOOL presenting; // @synthesize presenting=_presenting;
@property(getter=isVisible) BOOL visible; // @synthesize visible=_visible;
@property(retain) NSArray *notifications; // @synthesize notifications=_notifications;
- (void)notifyWithFailedMessage:(id)arg1;
- (void)notifyWithMomentShareFailed:(id)arg1;
- (void)notifyWithNewMatch:(id)arg1;
- (void)notifyWithNewMatchRequest:(id)arg1;
- (void)notifyWithNewMessage:(id)arg1;
- (void)notifyWithNewMessageText:(id)arg1 name:(id)arg2 matchID:(id)arg3;
- (void)notifyWithNewMomentLike:(id)arg1;
- (BOOL)obtainPermanentIDsForObject:(id)arg1;
- (void)pausePresentingNotifications;
- (void)prefetchImageViewImageForNotification:(id)arg1;
- (void)prefetchImageWithURL:(id)arg1;
- (void)presentNextNotification;
@property(retain, nonatomic) NSTimer *presentNextTimer; // @synthesize presentNextTimer=_presentNextTimer;
- (void)queueNotification:(id)arg1;
- (void)removeAllNotifications;
- (void)removeFirstNotification;
- (void)resetNotificationFrames;
- (void)resumePresentingNotifications;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NSTimer *tryPresentingTimer; // @synthesize tryPresentingTimer=_tryPresentingTimer;
- (void)setupAccessoryButton;
- (void)setupBannerColors;
- (void)setupBannerViewWithFrame:(struct CGRect)arg1;
- (void)setupDelayTimes;
- (void)setupDetailLabel;
- (void)setupGestureRecognizers;
- (void)setupImageViews;
- (void)setupTitleLabel;
- (void)setupTryPresentingTimer;
- (void)setupWithFrame:(struct CGRect)arg1;
- (BOOL)shouldAllowInteractionForNotification:(id)arg1;
- (void)showBannerWithNotification:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)updateImageViewWithTeamTinderAvatar;
- (void)updateImageViewWithURL:(id)arg1;
- (void)updateNotificationImageViewsWithNotificationType:(int)arg1;
- (void)updateWithNotification:(id)arg1;
@property(readonly, nonatomic) UIView *visibleNotificationView; // @synthesize visibleNotificationView=_visibleNotificationView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

