//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFHTTPSessionManager.h"

@interface TNDRHTTPMediaClient : AFHTTPSessionManager
{
}

+ (id)sharedDebugHTTPClient;
+ (id)sharedHTTPClient;
- (void)clearAuthorizationHeader;
- (id)initWithBaseURL:(id)arg1;
- (void)postImageToMediaServer:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setAuthorizationHeaderWithToken:(id)arg1;
- (void)setup;
- (void)uploadCompositedImage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)uploadMomentPhoto:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

