//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSArray, NSShadow, NSTimer, UIColor;

@interface TNDRAnimatedEqualizerButton : UIButton
{
    BOOL _animated;
    UIColor *_barColor;
    NSShadow *_barShadow;
    NSArray *_bars;
    NSTimer *_animationTimer;
}

- (void).cxx_destruct;
- (void)animateBars:(BOOL)arg1;
@property(retain, nonatomic) NSTimer *animationTimer; // @synthesize animationTimer=_animationTimer;
@property(retain, nonatomic) UIColor *barColor; // @synthesize barColor=_barColor;
- (id)barPathWithHeight:(float)arg1;
@property(retain, nonatomic) NSShadow *barShadow; // @synthesize barShadow=_barShadow;
@property(retain, nonatomic) NSArray *bars; // @synthesize bars=_bars;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, getter=isAnimated) BOOL animated; // @synthesize animated=_animated;
- (float)randomHeight;
- (void)setHighlighted:(BOOL)arg1;
- (void)setupEqualizerBars;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

