//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface TNDRMomentText : NSObject
{
    NSString *_text;
    int _alignment;
    float _originY;
    float _size;
}

- (void).cxx_destruct;
@property(nonatomic) int alignment; // @synthesize alignment=_alignment;
@property(nonatomic) float originY; // @synthesize originY=_originY;
@property(nonatomic) float size; // @synthesize size=_size;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;

@end

