//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TNDRViewControllerAnimatedTransitioning.h"

@class NSString, TNDRDialogViewController;

@interface TNDRDialogAnimationController : NSObject <TNDRViewControllerAnimatedTransitioning>
{
    BOOL _presenting;
    TNDRDialogViewController *_presentingDialogViewController;
}

- (void).cxx_destruct;
- (void)animateHideViewController:(id)arg1 sandboxBounds:(struct CGRect)arg2;
- (void)animateShowViewController:(id)arg1 sandboxBounds:(struct CGRect)arg2;
- (void)animateTransition:(id)arg1;
- (void)executeDismissalAnimation:(id)arg1;
- (void)executePresentationAnimation:(id)arg1;
@property(nonatomic, getter=isPresenting) BOOL presenting; // @synthesize presenting=_presenting;
@property(nonatomic) __weak TNDRDialogViewController *presentingDialogViewController; // @synthesize presentingDialogViewController=_presentingDialogViewController;
- (double)transitionDuration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

