//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class FBKVOController, UIImageView, UILabel;

@interface TNDRMenuHeaderView : UIView
{
    UIImageView *_profilePictureImageView;
    UILabel *_firstNameLabel;
    UILabel *_viewProfileLabel;
    FBKVOController *_KVOController;
}

- (void).cxx_destruct;
@property(retain, nonatomic) FBKVOController *KVOController; // @synthesize KVOController=_KVOController;
@property(retain, nonatomic) UILabel *firstNameLabel; // @synthesize firstNameLabel=_firstNameLabel;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(retain, nonatomic) UIImageView *profilePictureImageView; // @synthesize profilePictureImageView=_profilePictureImageView;
@property(retain, nonatomic) UILabel *viewProfileLabel; // @synthesize viewProfileLabel=_viewProfileLabel;
- (void)setupFirstNameLabel;
- (void)setupProfileImageView;
- (void)setupViewProfileLabel;
- (void)updateFirstNameLabelFrame;

@end

