//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, TNDRAdContentView;

@protocol TNDRAdContentViewDelegate <NSObject>
- (NSString *)adContentViewOverlayActionButtonText;
- (NSString *)adContentViewOverlayTitleText;

@optional
- (void)userDidTapAdContentView:(TNDRAdContentView *)arg1;
- (void)userDidTapMoreInfoInOverlayViewOnAdContentView:(TNDRAdContentView *)arg1;
- (void)userDidTapPauseButtonForAdContentView:(TNDRAdContentView *)arg1;
- (void)userDidTapPlayInOverlayViewOnAdContentView:(TNDRAdContentView *)arg1;
- (void)userDidToggleAudioForAdContentView:(TNDRAdContentView *)arg1;
@end

