//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TNDRCardCellControlDependencies.h"
#import "TNDRCardCellStackControl.h"
#import "TNDRDialogViewControllerDelegate.h"
#import "TNDRDiscoverOffViewDelegate.h"
#import "TNDRPassportLocationsListViewControllerDelegate.h"
#import "TNDRTinderPlusPaywallViewControllerDelegate.h"
#import "TNDRURLNavigableProtocol.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIViewControllerTransitioningDelegate.h"

@class NSString, NSURLSessionDataTask, TNDRCardCellMediator, TNDRDiscoverOffView, TNDREmptyStackLayout, TNDRGameToNewMatchAnimationController, TNDRGamepadBackgroundView, TNDRGamepadButton, TNDRLikeGamepadButton, TNDRNoRecommendationsView, TNDRPassportGamepadButton, TNDRPassportLocationsListAnimationController, TNDRPassportLocationsListViewController, TNDRPassportMapStackContainerViewController, TNDRRateLimitRoadblockDialogViewController, TNDRRewindGamepadButton, TNDRStackLayout, TNDRTinderPlusPaywallAnimationController, TNDRTinderPlusPaywallViewController, TNDRUser, UICollectionView, UIImageView, UILabel, UIPanGestureRecognizer, UITapGestureRecognizer, UIView;

@interface TNDRRecommendationViewController : UIViewController <UIGestureRecognizerDelegate, UIViewControllerTransitioningDelegate, TNDRDiscoverOffViewDelegate, TNDRPassportLocationsListViewControllerDelegate, TNDRTinderPlusPaywallViewControllerDelegate, TNDRDialogViewControllerDelegate, TNDRCardCellControlDependencies, TNDRCardCellStackControl, TNDRURLNavigableProtocol>
{
    BOOL _isCardFinalizing;
    BOOL _isDraggingCard;
    BOOL _preventOpeningProfile;
    struct CGPoint _panStartPoint;
    struct CGPoint _panCurPoint;
    TNDRUser *_lastTrackedUser;
    BOOL _userInteractionEnabled;
    BOOL _openingUserProfile;
    BOOL _isShowingRateLimitDeviceTimeError;
    BOOL _recsSessionIsActive;
    BOOL _rebuildingCardStack;
    TNDRLikeGamepadButton *_likeButton;
    TNDRGamepadButton *_passButton;
    TNDRRewindGamepadButton *_rewindButton;
    TNDRPassportGamepadButton *_passportButton;
    TNDRGamepadButton *_infoButton;
    TNDRGamepadBackgroundView *_buttonContainer;
    TNDRStackLayout *_stackLayout;
    TNDREmptyStackLayout *_emptyStackLayout;
    UICollectionView *_collectionView;
    TNDRCardCellMediator *_mediator;
    UIPanGestureRecognizer *_panGestureRecognizer;
    UITapGestureRecognizer *_tapGestureRecognizer;
    UIView *_animatableCardContentView;
    UIImageView *_cardSnapshotShadow;
    TNDRNoRecommendationsView *_noRecommendationsView;
    TNDRDiscoverOffView *_discoverOffView;
    UIView *_animatableCardContainerView;
    UILabel *_likeStampView;
    UILabel *_passStampView;
    TNDRGameToNewMatchAnimationController *_gameToNewMatchTransitioning;
    TNDRTinderPlusPaywallViewController *_paywallViewController;
    TNDRTinderPlusPaywallAnimationController *_paywallAnimationController;
    TNDRRateLimitRoadblockDialogViewController *_rateLimitRoadblockDialogViewController;
    TNDRPassportLocationsListViewController *_passportLocationsListController;
    TNDRPassportLocationsListAnimationController *_myLocationsAnimationController;
    TNDRPassportMapStackContainerViewController *_passportMapSearchViewController;
    int _passportTravelState;
    NSURLSessionDataTask *_currentPassportTask;
}

+ (id)viewControllerNavigationKey;
- (void).cxx_destruct;
- (void)adjustCardAtIndex:(int)arg1 horizontalTranslation:(float)arg2;
- (void)adjustCardsForPanningPosition:(float)arg1;
@property(retain, nonatomic) UIView *animatableCardContainerView; // @synthesize animatableCardContainerView=_animatableCardContainerView;
@property(retain, nonatomic) UIView *animatableCardContentView; // @synthesize animatableCardContentView=_animatableCardContentView;
- (void)animateCell:(id)arg1 direction:(int)arg2;
- (void)animateCellToCenter:(id)arg1;
- (void)animateInGameButtons;
- (void)animateUnswipedCellOffscreen:(id)arg1 direction:(int)arg2 showStamp:(BOOL)arg3;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
@property(retain, nonatomic) TNDRGamepadBackgroundView *buttonContainer; // @synthesize buttonContainer=_buttonContainer;
@property(retain, nonatomic) UIImageView *cardSnapshotShadow; // @synthesize cardSnapshotShadow=_cardSnapshotShadow;
- (void)cardStackDidFinishRebuilding;
- (void)cardStackWillBeCleared;
- (id)cellForIndexOnStack:(unsigned int)arg1;
- (id)cellForTopCardOnStack;
- (void)changeButtonContainerForUpdatedGameType;
- (void)checkForGameButtonTypeChangesAndTransitionIfNecessary;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void)createAndShowAnimatableCardViewForCell:(id)arg1;
@property(retain, nonatomic) NSURLSessionDataTask *currentPassportTask; // @synthesize currentPassportTask=_currentPassportTask;
- (void)dealloc;
- (BOOL)destinationViewControllerShouldTriggerRecsSessionEnd:(id)arg1;
- (void)dialogViewControllerRequestsDismissal:(id)arg1;
- (void)didCompletePurchase;
- (void)didReceiveMemoryWarning;
- (void)didSelectToCloseLocationListWithoutTraveling;
- (void)didSelectToNavigateToPassportPaywall:(unsigned int)arg1;
- (void)didSelectToOpenMapSearchController;
- (void)didSelectTravelToLocation:(id)arg1;
- (void)discoverButtonTapped;
@property(retain) TNDRDiscoverOffView *discoverOffView; // @synthesize discoverOffView=_discoverOffView;
- (void)dismissCardCellWithSwipeLeft:(id)arg1 showStamp:(BOOL)arg2;
- (void)dismissCardCellWithSwipeRight:(id)arg1 showStamp:(BOOL)arg2;
- (void)dismissCell:(id)arg1 direction:(int)arg2 showStamp:(BOOL)arg3;
@property(retain, nonatomic) TNDREmptyStackLayout *emptyStackLayout; // @synthesize emptyStackLayout=_emptyStackLayout;
- (void)finishSwipingInDirection:(int)arg1 withVelocity:(struct CGPoint)arg2;
- (id)gamePanGestureRecognizer;
@property(retain, nonatomic) TNDRGameToNewMatchAnimationController *gameToNewMatchTransitioning; // @synthesize gameToNewMatchTransitioning=_gameToNewMatchTransitioning;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (void)handleAppBackgroundedNotification:(id)arg1;
- (void)handleAppForegroundedNotification:(id)arg1;
- (void)handleMediatorDidChangeCellsNotification:(id)arg1;
- (void)handleNoRecommendationsNotification:(id)arg1;
- (void)handlePanGesture:(id)arg1;
- (void)handlePaywallDownloadedProducts:(id)arg1;
- (void)handleRecsSessionEndingFromViewDisappearing;
- (void)handleRecsSessionStartingFromViewAppearing;
- (void)handleRewindDidBecomeAvailableNotification:(id)arg1;
- (void)handleRewindDidBecomeUnavailableNotification:(id)arg1;
- (void)handleStatusBarChangedNotification:(id)arg1;
- (void)handleSwipesRemainingUpdatedNotification:(id)arg1;
- (void)handleTinderPlusActiveNotification:(id)arg1;
- (void)handleTinderPlusInactiveNotification:(id)arg1;
- (void)handleTrackRecsStartAfterIntro:(id)arg1;
- (void)handleUserAuthenticated:(id)arg1;
- (void)highlightActionIndicators:(float)arg1;
@property(retain, nonatomic) TNDRGamepadButton *infoButton; // @synthesize infoButton=_infoButton;
- (void)infoButtonTapped:(id)arg1;
- (id)init;
@property(nonatomic, getter=isRebuildingCardStack) BOOL rebuildingCardStack; // @synthesize rebuildingCardStack=_rebuildingCardStack;
@property(nonatomic) BOOL isShowingRateLimitDeviceTimeError; // @synthesize isShowingRateLimitDeviceTimeError=_isShowingRateLimitDeviceTimeError;
@property(retain, nonatomic) TNDRLikeGamepadButton *likeButton; // @synthesize likeButton=_likeButton;
- (void)likeButtonTapped:(id)arg1;
- (id)likeStamp;
@property(retain, nonatomic) UILabel *likeStampView; // @synthesize likeStampView=_likeStampView;
@property(retain, nonatomic) TNDRCardCellMediator *mediator; // @synthesize mediator=_mediator;
@property(retain, nonatomic) TNDRPassportLocationsListAnimationController *myLocationsAnimationController; // @synthesize myLocationsAnimationController=_myLocationsAnimationController;
@property(retain) TNDRNoRecommendationsView *noRecommendationsView; // @synthesize noRecommendationsView=_noRecommendationsView;
- (void)notifyInteractionHandlerOfSwipeLeft;
- (void)notifyInteractionHandlerOfSwipeRight;
- (void)notifyInteractionHandlerOfTapLeft;
- (void)notifyInteractionHandlerOfTapLeftAccessory;
- (void)notifyInteractionHandlerOfTapRight;
- (void)notifyInteractionHandlerOfTappedCard;
- (void)notifyInteractionHandlerOfTappedInfoButton;
- (int)numberOfCardsInStack;
@property(nonatomic) BOOL openingUserProfile; // @synthesize openingUserProfile=_openingUserProfile;
@property(retain, nonatomic) UIPanGestureRecognizer *panGestureRecognizer; // @synthesize panGestureRecognizer=_panGestureRecognizer;
@property(retain, nonatomic) TNDRGamepadButton *passButton; // @synthesize passButton=_passButton;
- (void)passButtonTapped:(id)arg1;
- (id)passStamp;
@property(retain, nonatomic) UILabel *passStampView; // @synthesize passStampView=_passStampView;
@property(retain, nonatomic) TNDRPassportGamepadButton *passportButton; // @synthesize passportButton=_passportButton;
- (void)passportButtonTapped:(id)arg1;
@property(retain, nonatomic) TNDRPassportLocationsListViewController *passportLocationsListController; // @synthesize passportLocationsListController=_passportLocationsListController;
@property(retain, nonatomic) TNDRPassportMapStackContainerViewController *passportMapSearchViewController; // @synthesize passportMapSearchViewController=_passportMapSearchViewController;
@property(nonatomic) int passportTravelState; // @synthesize passportTravelState=_passportTravelState;
@property(retain, nonatomic) TNDRTinderPlusPaywallAnimationController *paywallAnimationController; // @synthesize paywallAnimationController=_paywallAnimationController;
- (void)paywallRequestsDismissal;
@property(retain, nonatomic) TNDRTinderPlusPaywallViewController *paywallViewController; // @synthesize paywallViewController=_paywallViewController;
- (void)performRewindAction;
- (void)postDidDismissCellNotificationForDirection:(int)arg1;
@property(retain, nonatomic) TNDRRateLimitRoadblockDialogViewController *rateLimitRoadblockDialogViewController; // @synthesize rateLimitRoadblockDialogViewController=_rateLimitRoadblockDialogViewController;
@property(nonatomic) BOOL recsSessionIsActive; // @synthesize recsSessionIsActive=_recsSessionIsActive;
- (void)registerNotifications;
- (void)removeDiscoverOffView;
- (void)removeNoRecommendationsView;
- (void)resetAnimatableContentViewForCell:(id)arg1;
- (void)returnCardCellToCenter:(id)arg1;
- (void)returnRecommendationToCenterForRateLimiting:(id)arg1;
@property(retain, nonatomic) TNDRRewindGamepadButton *rewindButton; // @synthesize rewindButton=_rewindButton;
- (void)rewindButtonTapped:(id)arg1;
@property(retain, nonatomic) TNDRStackLayout *stackLayout; // @synthesize stackLayout=_stackLayout;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(nonatomic) BOOL userInteractionEnabled; // @synthesize userInteractionEnabled=_userInteractionEnabled;
- (void)setup;
- (void)setupAccessibilityLabels;
- (void)setupAnimatableCardContainerView;
- (void)setupButtons;
- (void)setupGameCardFrames;
- (void)setupGestureRecognizer;
- (void)setupPaywallViewController;
- (void)setupRateLimitRoadblockViewControllerWithUserID:(id)arg1;
- (void)showDiscoverOffiew;
- (void)showNoRecommendationsView;
- (void)showTinderPlusPaywallFrom:(unsigned int)arg1;
- (id)stackControlDelegate;
- (id)stackViewController;
- (void)topCardTapped:(id)arg1;
- (void)transitionTo:(id)arg1 optionsDict:(id)arg2 animated:(BOOL)arg3 completion:(CDUnknownBlockType)arg4;
- (void)translateSwipedCellOffscreen:(id)arg1 direction:(int)arg2;
- (void)updateDiscoverEnabledWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;

// Remaining properties
@property(readonly, nonatomic) id <UIViewControllerAnimatedTransitioning> animationController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

