//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_TNDRFriend.h"

#import "TNDRCommonAttribute.h"

@class NSString;

@interface TNDRFriend : _TNDRFriend <TNDRCommonAttribute>
{
}

+ (id)createFriendFromTinderID:(id)arg1 requestStatus:(int)arg2 userID:(id)arg3 fullName:(id)arg4;
- (id)commonAttributeName;
@property(readonly, copy) NSString *description;
- (id)imageURLforSize:(struct CGSize)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

