//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TNDRDialogViewControllerPriority.h"
#import "TNDRURLNavigableProtocol.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITableViewDataSource.h"

@class NSString, TNDRDialogFooter, TNDRDialogHeader, UITableView, UITapGestureRecognizer, UIView;

@interface TNDRDialogViewController : UIViewController <UITableViewDataSource, TNDRURLNavigableProtocol, TNDRDialogViewControllerPriority, UIGestureRecognizerDelegate>
{
    BOOL _opaqueContent;
    BOOL _tapShouldDismiss;
    BOOL _shouldAnimateBeforeDismiss;
    TNDRDialogHeader *_headerView;
    TNDRDialogFooter *_footerView;
    UIView *_backgroundOverlay;
    UIView *_containerView;
    UITableView *_tableView;
    id <TNDRDialogViewControllerDelegate> _delegate;
    float _numberOfRowsToDisplay;
    UITapGestureRecognizer *_dismissOnTapGestureRecognizer;
}

+ (id)viewControllerNavigationKey;
- (void).cxx_destruct;
- (void)adjustContentDimensions;
@property(readonly, nonatomic) id <UIViewControllerAnimatedTransitioning><TNDRViewControllerAnimatedTransitioning> animationController;
@property(retain, nonatomic) UIView *backgroundOverlay; // @synthesize backgroundOverlay=_backgroundOverlay;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak id <TNDRDialogViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) unsigned int dialogPriority;
@property(retain, nonatomic) UITapGestureRecognizer *dismissOnTapGestureRecognizer; // @synthesize dismissOnTapGestureRecognizer=_dismissOnTapGestureRecognizer;
@property(retain, nonatomic) TNDRDialogFooter *footerView; // @synthesize footerView=_footerView;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (void)handleTapInView:(id)arg1;
@property(nonatomic, getter=hasOpaqueContent, setter=setOpaqueContent:) BOOL opaqueContent; // @synthesize opaqueContent=_opaqueContent;
@property(retain, nonatomic) TNDRDialogHeader *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) float numberOfRowsToDisplay; // @synthesize numberOfRowsToDisplay=_numberOfRowsToDisplay;
- (void)requestDismissal;
@property(nonatomic) BOOL shouldAnimateBeforeDismiss; // @synthesize shouldAnimateBeforeDismiss=_shouldAnimateBeforeDismiss;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) BOOL tapShouldDismiss; // @synthesize tapShouldDismiss=_tapShouldDismiss;
- (void)setupGestureRecognizer;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

