//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TNDRAnalyticsTracker : NSObject
{
}

+ (void)setSharedTracker:(id)arg1;
+ (id)sharedTracker;
- (id)currentUser;
- (id)init;
- (void)setup;
- (void)trackAccountViewIntro;
- (void)trackAllAnalyticsForEvent:(id)arg1 properties:(id)arg2;
- (void)trackAppCloseEvent;
- (void)trackAppOpenEvent:(BOOL)arg1;
- (void)trackChatBlockMatch:(id)arg1 userID:(id)arg2;
- (void)trackChatOpenForMatchID:(id)arg1 userID:(id)arg2 fromPush:(BOOL)arg3;
- (void)trackChatOpenProfileForMatch:(id)arg1 userID:(id)arg2;
- (void)trackChatReportMatch:(id)arg1 userID:(id)arg2 reason:(id)arg3 otherExplanation:(id)arg4;
- (void)trackChatSendMessageToMatch:(id)arg1 userID:(id)arg2 message:(id)arg3;
- (void)trackContactOpen;
- (void)trackFriendsClaimID:(id)arg1;
- (void)trackFriendsIDClaimed:(id)arg1;
- (void)trackFriendsIncomingRequest:(id)arg1;
- (void)trackFriendsIncomingRequestAccepted:(id)arg1;
- (void)trackFriendsIncomingRequestDeclined:(id)arg1;
- (void)trackFriendsIncomingRequestViewProfile:(id)arg1;
- (void)trackFriendsOpenAddFriendsSource:(unsigned int)arg1;
- (void)trackFriendsOpenCreateID;
- (void)trackFriendsOpenEditID;
- (void)trackFriendsRequest:(id)arg1 requestType:(unsigned int)arg2 searchText:(id)arg3 countNumberUsers:(unsigned int)arg4;
- (void)trackFriendsShareID:(id)arg1 destination:(id)arg2;
- (void)trackMatchInviteFriends:(id)arg1;
- (void)trackMatchKeepPlaying:(id)arg1;
- (void)trackMatchListViewed;
- (void)trackMatchNewMatch:(id)arg1 fromPush:(BOOL)arg2;
- (void)trackMatchOpenChat:(id)arg1;
- (void)trackMenuAppSettingsSelected;
- (void)trackMenuClose;
- (void)trackMenuContactTinderSelected;
- (void)trackMenuDiscoverySettingsSelected;
- (void)trackMenuOpen;
- (void)trackMenuProfileSelected;
- (void)trackMenuRecommendationsSelected;
- (void)trackMenuShareSelected;
- (void)trackMixpanelEvent:(id)arg1 properties:(id)arg2;
- (void)trackMomentDeleteForMomentWithID:(id)arg1 fromKey:(unsigned int)arg2;
- (void)trackMomentLikesViewForMomentWithID:(id)arg1 fromKey:(unsigned int)arg2;
- (void)trackMomentSave:(id)arg1;
- (void)trackMomentsCameraRollClose;
- (void)trackMomentsCameraRollOpen;
- (void)trackMomentsCameraRollSelect;
- (void)trackMomentsCameraRollSelect:(long long)arg1 latitude:(double)arg2 longitude:(double)arg3;
- (void)trackMomentsHideForUserWithID:(id)arg1 matchID:(id)arg2 type:(unsigned int)arg3;
- (void)trackMyProfileView;
- (void)trackPassportAcceptLocationWithNewLat:(double)arg1 andLong:(double)arg2;
- (void)trackPassportChooseLocationWithLat:(double)arg1 andLong:(double)arg2 isExpired:(BOOL)arg3 isTinderPlusSubscriber:(BOOL)arg4;
- (void)trackPassportDismissView:(id)arg1 andPassportID:(id)arg2;
- (void)trackPassportLaunchFromView:(id)arg1 andPassportID:(id)arg2;
- (void)trackPassportMapOpen:(BOOL)arg1;
- (void)trackPassportMapPinDroppedWithLat:(double)arg1 andLong:(double)arg2 isCurrentLocation:(BOOL)arg3;
- (void)trackPassportMapSearch:(id)arg1 withMethod:(id)arg2 isPopular:(BOOL)arg3;
- (void)trackPassportMenuClosed;
- (void)trackPassportMoveMap;
- (void)trackPassportProfileView:(id)arg1 andPassportID:(id)arg2;
- (void)trackPassportSelectMyLocation;
- (void)trackPassportStartRecsExhausted:(BOOL)arg1;
- (void)trackProfileAddPhoto:(id)arg1;
- (void)trackProfileChangePhotoOrder:(id)arg1 fromIndex:(id)arg2 toIndex:(id)arg3;
- (void)trackProfileDeletePhoto:(id)arg1;
- (void)trackProfileEdit;
- (void)trackPushMarketingCampaign:(id)arg1;
- (void)trackPushMatch:(id)arg1;
- (void)trackPushMessage:(id)arg1;
- (void)trackRecommendationsUndoNoRewindableUserShownPaywall:(BOOL)arg1 isUserTraveling:(BOOL)arg2;
- (void)trackRecommendationsUndoPreviouslyLiked:(BOOL)arg1 otherID:(id)arg2 paywall:(BOOL)arg3 isUserTraveling:(BOOL)arg4 isRecTraveling:(BOOL)arg5;
- (void)trackRecsDiscoveryToggled:(BOOL)arg1;
- (void)trackRecsEnd;
- (void)trackRecsInviteFriends;
- (void)trackRecsPhotoViewForUser:(id)arg1 andPhoto:(id)arg2;
- (void)trackRecsProfileCloseForUser:(id)arg1;
- (void)trackRecsProfileOpenForUser:(id)arg1;
- (void)trackRecsRateUser:(id)arg1 method:(id)arg2 fromMore:(BOOL)arg3 liked:(BOOL)arg4 isUserTraveling:(BOOL)arg5 isRecTraveling:(BOOL)arg6 tinderPlus:(BOOL)arg7;
- (void)trackRecsReportUser:(id)arg1 reason:(id)arg2 otherExplanation:(id)arg3;
- (void)trackRecsStart;
- (void)trackRecsView:(id)arg1;
- (void)trackReportMoment:(id)arg1 match:(id)arg2 userID:(id)arg3 reason:(id)arg4 otherExplanation:(id)arg5 fromType:(int)arg6;
- (void)trackReportRecommendation:(id)arg1 reason:(id)arg2 otherExplanation:(id)arg3;
- (void)trackSparksEvent:(id)arg1 properties:(id)arg2;
- (void)trackTinderPlusExitPaywallCancelWithProductInfo:(id)arg1 percentLikesLeft:(float)arg2 unlimitedLikesOffered:(BOOL)arg3;
- (void)trackTinderPlusPaywallViewAllProducts:(id)arg1 encounteredFrom:(unsigned int)arg2 percentLikesLeft:(float)arg3 unlimitedLikesOffered:(BOOL)arg4;
- (void)trackTinderPlusPurchase:(id)arg1 withPrice:(id)arg2 andLocale:(id)arg3 from:(unsigned int)arg4 percentLikesLeft:(float)arg5 unlimitedLikesOffered:(BOOL)arg6;
- (void)trackTinderPlusRestore:(id)arg1 success:(BOOL)arg2;
- (void)trackTinderPlusRoadblockCancelWithProductInfo:(id)arg1 otherID:(id)arg2 percentLikesLeft:(float)arg3 timeRemaining:(long long)arg4;
- (void)trackTinderPlusRoadblockSelectSku:(id)arg1 withPrice:(id)arg2 andLocale:(id)arg3 otherID:(id)arg4 percentLikesLeft:(float)arg5 timeRemaining:(long long)arg6;
- (void)trackTinderPlusRoadblockViewWithProductInfo:(id)arg1 otherID:(id)arg2 percentLikesLeft:(float)arg3 timeRemaining:(long long)arg4;
- (void)trackTinderPlusSelectPurchaseOption:(id)arg1 withPrice:(id)arg2 andLocale:(id)arg3 percentLikesLeft:(float)arg4 unlimitedLikesOffered:(BOOL)arg5;
- (void)trackTinderPlusSkuOffered:(id)arg1;

@end

