//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TNDRMomentsCameraButtonDelegate.h"

@class NSString, TNDREditMomentButtonContainerView, UIView;

@interface TNDREditMomentButtonAnimationManager : NSObject <TNDRMomentsCameraButtonDelegate>
{
    TNDREditMomentButtonContainerView *_buttonContainerView;
    UIView *_headerDarkenView;
    UIView *_footerDarkenView;
    int _editingState;
    CDUnknownBlockType _presentationCompletionBlock;
}

- (void).cxx_destruct;
- (void)animateForDismissalCompletion:(CDUnknownBlockType)arg1;
- (void)animateForPresentationCompletion:(CDUnknownBlockType)arg1;
- (void)animateInBottomButtonsForFilterGridMode;
- (void)animateInEditButtonsForTransitionFromCamera;
- (void)animateInEditButtonsFromEdgesIncludeShareButton:(BOOL)arg1;
- (void)animateOutEditButtonsForFilterGridMode;
- (void)animateOutEditButtonsForReturningToCamera;
- (void)animateOutEditButtonsToEdgesIncludeShareButton:(BOOL)arg1;
- (void)animateOutEditButtonsToEdgesIncludeShareButton:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) TNDREditMomentButtonContainerView *buttonContainerView; // @synthesize buttonContainerView=_buttonContainerView;
- (void)didCompleteAnimationToShareState;
@property(nonatomic) int editingState; // @synthesize editingState=_editingState;
@property(retain, nonatomic) UIView *footerDarkenView; // @synthesize footerDarkenView=_footerDarkenView;
@property(retain, nonatomic) UIView *headerDarkenView; // @synthesize headerDarkenView=_headerDarkenView;
- (void)hideEditButtonsBehind:(id)arg1;
- (void)prepareUIButtonsForTransitionFromCameraMoments;
@property(copy, nonatomic) CDUnknownBlockType presentationCompletionBlock; // @synthesize presentationCompletionBlock=_presentationCompletionBlock;
- (void)revealEditButtons;
- (float)translationAmountForTransition;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

