//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DDXMLDocument, NSArray, NSString, NSURL;

@interface TNDRLiveRailVASTXMLParser : NSObject
{
    DDXMLDocument *_XMLDocument;
}

+ (id)URLForXPath:(id)arg1 inXMLDocument:(id)arg2;
+ (id)elementsForXPath:(id)arg1 inXMLDocument:(id)arg2;
+ (id)parserForVASTPayload:(id)arg1;
+ (id)stringForXPath:(id)arg1 inXMLDocument:(id)arg2;
- (void).cxx_destruct;
- (id)URLForXPath:(id)arg1;
@property(retain, nonatomic) DDXMLDocument *XMLDocument; // @synthesize XMLDocument=_XMLDocument;
@property(readonly, nonatomic) NSString *adActionButtonTitle;
@property(readonly, nonatomic) NSString *adSubtitle;
@property(readonly, nonatomic) NSString *adTitle;
@property(readonly, nonatomic) NSURL *bandwidthAppropriateAdVideoURL;
@property(readonly, nonatomic) NSString *campaignOrderID;
@property(readonly, nonatomic) NSURL *clickThroughURL;
@property(readonly, nonatomic) NSURL *closeTrackingURL;
@property(readonly, nonatomic) NSURL *companionAdImageURL;
@property(readonly, nonatomic) NSURL *completeTrackingURL;
@property(readonly, nonatomic) NSString *creativeID;
@property(readonly, nonatomic) NSURL *firstQuartileTrackingURL;
@property(readonly, nonatomic) NSArray *impressionURLs;
- (id)initWithPayload:(id)arg1;
@property(readonly, nonatomic) NSURL *midpointTrackingURL;
@property(readonly, nonatomic) NSURL *muteTrackingURL;
@property(readonly, nonatomic) NSURL *pauseTrackingURL;
@property(readonly, nonatomic) NSString *provider;
@property(readonly, nonatomic) NSURL *resumeTrackingURL;
@property(readonly, nonatomic) NSString *socialShareTextContent;
@property(readonly, nonatomic) NSURL *socialShareURL;
- (id)stringForXPath:(id)arg1;
@property(readonly, nonatomic) NSURL *thirdQuartileTrackingURL;
@property(readonly, nonatomic) NSURL *unmuteTrackingURL;
- (id)videoTrackingEventURLForEventName:(id)arg1;

@end

