//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIScrollViewDelegate.h"

@class NSString, UIActivityIndicatorView, UIButton, UIImageView, UILabel, UIScrollView, UIView;

@interface TNDRFacebookPhotoCropperController : UIViewController <UIScrollViewDelegate>
{
    struct CGPoint _startingImageViewCenter;
    struct CGAffineTransform _startingImageViewTransform;
    UIScrollView *_scrollView;
    UIView *_squareView;
    UIView *_outlineView;
    UIButton *_chooseButton;
    UIButton *_cancelButton;
    UILabel *_directionsLabel;
    UIView *_spinnerBackgroundView;
    UIActivityIndicatorView *_activityIndicator;
    UIImageView *_imageView;
    NSString *_facebookID;
    id <TNDRFacebookImagePickerDelegate> _photoPickerDelegate;
}

- (void).cxx_destruct;
- (id)buttonWithText:(id)arg1;
- (void)cancel:(id)arg1;
- (id)croppedImage;
- (struct CGRect)croppingRectAsPercentages;
- (void)didReceiveMemoryWarning;
@property(retain, nonatomic) NSString *facebookID; // @synthesize facebookID=_facebookID;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic) __weak id <TNDRFacebookImagePickerDelegate> photoPickerDelegate; // @synthesize photoPickerDelegate=_photoPickerDelegate;
- (void)save:(id)arg1;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(float)arg3;
- (void)setupScrollView;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)viewForZoomingInScrollView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

