//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSDictionary, UIButton, UIImageView, UILabel, UITapGestureRecognizer, UITextField, UIView;

@interface TNDRFriendsChangeMyIDTableViewCell : UITableViewCell
{
    UITextField *_textField;
    UIButton *_submitButton;
    UILabel *_statusLabel;
    id <TNDRFriendsChangeMyIDCellDelegate> _delegate;
    UIImageView *_badgeView;
    NSDictionary *_errorTextAttributes;
    NSDictionary *_statusTextAttributes;
    UIView *_previousTinderIDView;
    UILabel *_previousTinderIDLabel;
    UILabel *_tapToEditLabel;
    UITapGestureRecognizer *_tapGestureRecognizer;
}

- (void).cxx_destruct;
- (struct UIEdgeInsets)autoLayoutEdgeInsetsForStatusField;
- (struct UIEdgeInsets)autoLayoutEdgeInsetsForTextField;
- (void)awakeFromNib;
@property(retain, nonatomic) UIImageView *badgeView; // @synthesize badgeView=_badgeView;
@property(nonatomic) __weak id <TNDRFriendsChangeMyIDCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSDictionary *errorTextAttributes; // @synthesize errorTextAttributes=_errorTextAttributes;
- (void)handleTapToEdit:(id)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
@property(retain, nonatomic) UILabel *previousTinderIDLabel; // @synthesize previousTinderIDLabel=_previousTinderIDLabel;
@property(retain, nonatomic) UIView *previousTinderIDView; // @synthesize previousTinderIDView=_previousTinderIDView;
- (void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
@property(retain, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(retain, nonatomic) NSDictionary *statusTextAttributes; // @synthesize statusTextAttributes=_statusTextAttributes;
@property(retain, nonatomic) UIButton *submitButton; // @synthesize submitButton=_submitButton;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(retain, nonatomic) UILabel *tapToEditLabel; // @synthesize tapToEditLabel=_tapToEditLabel;
@property(retain, nonatomic) UITextField *textField; // @synthesize textField=_textField;
- (void)setup;
- (void)setupIDBadgeIcon;
- (void)setupPreviousTinderIDView;
- (void)setupSubmitButton;
- (void)setupTextAttributes;
- (void)showMessage:(id)arg1 isError:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;

@end

