//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "NSFetchedResultsControllerDelegate.h"
#import "TNDRMyMomentCellDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSFetchedResultsController, NSString, TNDRMoment, TNDRMyMomentCell, UIImage, UIImageView, UILongPressGestureRecognizer, UINavigationBar, UIScrollView, UITableView;

@interface TNDRMyMomentViewerView : UIView <UIScrollViewDelegate, TNDRMyMomentCellDelegate, UIGestureRecognizerDelegate, UITableViewDataSource, UITableViewDelegate, NSFetchedResultsControllerDelegate>
{
    BOOL _viewedFromChat;
    BOOL _requestedDeletion;
    BOOL _requestedHideLikes;
    BOOL _viewingLikes;
    BOOL _momentIsMyMoment;
    BOOL _canDismissOnTap;
    TNDRMoment *_moment;
    UIImage *_blurredSnapshotImage;
    id <TNDRMyMomentViewerDelegate> _delegate;
    UIView *_bgOverlay;
    TNDRMyMomentCell *_momentCell;
    UIScrollView *_scrollView;
    UIView *_scrollViewSnapshot;
    UINavigationBar *_navigationBar;
    UIImageView *_blurredBackgroundView;
    UIImageView *_prefetchImageView;
    NSFetchedResultsController *_fetchedResultsController;
    UITableView *_likesTableView;
    float _yVelocity;
    UILongPressGestureRecognizer *_tapGestureRecognizer;
    struct CATransform3D _dipBackTransform3D;
}

- (void).cxx_destruct;
- (void)animateInMomentCell;
- (void)animateOutMomentCell;
- (float)baseRotateAmountWithPerc:(float)arg1;
@property(retain, nonatomic) UIView *bgOverlay; // @synthesize bgOverlay=_bgOverlay;
@property(retain, nonatomic) UIImageView *blurredBackgroundView; // @synthesize blurredBackgroundView=_blurredBackgroundView;
@property(retain, nonatomic) UIImage *blurredSnapshotImage; // @synthesize blurredSnapshotImage=_blurredSnapshotImage;
@property(nonatomic) BOOL canDismissOnTap; // @synthesize canDismissOnTap=_canDismissOnTap;
- (void)closeMomentViewer:(id)arg1;
- (void)configureCell:(id)arg1 atIndexPath:(id)arg2;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned int)arg4 newIndexPath:(id)arg5;
- (void)controllerDidChangeContent:(id)arg1;
- (void)controllerWillChangeContent:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <TNDRMyMomentViewerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didRequestToDeleteMoment;
- (void)didRequestToViewLikes;
@property(nonatomic) struct CATransform3D dipBackTransform3D; // @synthesize dipBackTransform3D=_dipBackTransform3D;
- (struct CATransform3D)dipBackTransformWithTranslation:(float)arg1;
- (void)dipCardBackwardsAndShowLikes;
- (void)enableTableViewInteraction;
@property(retain, nonatomic) NSFetchedResultsController *fetchedResultsController; // @synthesize fetchedResultsController=_fetchedResultsController;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)handleTapGesture:(id)arg1;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, getter=isViewedFromChat) BOOL viewedFromChat; // @synthesize viewedFromChat=_viewedFromChat;
@property(nonatomic, getter=isViewingLikes) BOOL viewingLikes; // @synthesize viewingLikes=_viewingLikes;
- (id)likeForIndexPath:(id)arg1;
@property(retain, nonatomic) UITableView *likesTableView; // @synthesize likesTableView=_likesTableView;
@property(retain, nonatomic) TNDRMoment *moment; // @synthesize moment=_moment;
@property(retain, nonatomic) TNDRMyMomentCell *momentCell; // @synthesize momentCell=_momentCell;
@property(nonatomic) BOOL momentIsMyMoment; // @synthesize momentIsMyMoment=_momentIsMyMoment;
@property(retain, nonatomic) UINavigationBar *navigationBar; // @synthesize navigationBar=_navigationBar;
- (int)numberOfSectionsInTableView:(id)arg1;
- (float)percentToBottomTranslation:(float)arg1;
@property(retain, nonatomic) UIImageView *prefetchImageView; // @synthesize prefetchImageView=_prefetchImageView;
- (void)prepareViewsForShowingLikes;
- (void)presentMoment;
@property(nonatomic) BOOL requestedDeletion; // @synthesize requestedDeletion=_requestedDeletion;
@property(nonatomic) BOOL requestedHideLikes; // @synthesize requestedHideLikes=_requestedHideLikes;
- (void)restoreCard;
- (void)restoreNonLikesViewMode;
- (void)retrieveLikesForMoment:(id)arg1;
- (struct CATransform3D)rotateBackTransformWithTranslation:(float)arg1;
- (struct CATransform3D)scaleDownTransformWithTranslation:(float)arg1;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
@property(retain, nonatomic) UIView *scrollViewSnapshot; // @synthesize scrollViewSnapshot=_scrollViewSnapshot;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
@property(retain, nonatomic) UILongPressGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(nonatomic) float yVelocity; // @synthesize yVelocity=_yVelocity;
- (void)setup;
- (void)setupDipBackTransform;
- (void)setupLikesDataSource;
- (void)setupTapGestureRecognizer;
- (void)setupTransparentNavigationBar;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (struct CATransform3D)translateUpTransform;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

