//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TNDRMomentsCameraButtonDelegate.h"
#import "UIViewControllerAnimatedTransitioning.h"

@class NSString, TNDRMomentsCameraButton;

@interface TNDRMatchesToMomentsCameraAnimationController : NSObject <UIViewControllerAnimatedTransitioning, TNDRMomentsCameraButtonDelegate>
{
    struct CGPoint _centerStartingCameraButton;
    id <UIViewControllerContextTransitioning> _presentContext;
    TNDRMomentsCameraButton *_toViewCameraButton;
    struct CGPoint _toViewCameraCenter;
    TNDRMomentsCameraButton *_tempFromButton;
    BOOL _isPresenting;
    TNDRMomentsCameraButton *_startingCameraButton;
    TNDRMomentsCameraButton *_endingCameraButton;
    double _presentationDuration;
    double _dismissalDuration;
}

- (void).cxx_destruct;
- (void)animateTransition:(id)arg1;
- (void)cleanupViewsForPresentationInContext:(id)arg1;
- (void)clearAllViewsInSandbox:(id)arg1;
- (void)didCompleteAnimationToCameraState;
- (void)didCompleteAnimationToNormalState;
@property(nonatomic) double dismissalDuration; // @synthesize dismissalDuration=_dismissalDuration;
@property(nonatomic) __weak TNDRMomentsCameraButton *endingCameraButton; // @synthesize endingCameraButton=_endingCameraButton;
- (void)executeDismissalAnimation:(id)arg1;
- (void)executePresentationAnimation:(id)arg1;
- (id)init;
@property(nonatomic) BOOL isPresenting; // @synthesize isPresenting=_isPresenting;
@property(nonatomic) double presentationDuration; // @synthesize presentationDuration=_presentationDuration;
@property(nonatomic) __weak TNDRMomentsCameraButton *startingCameraButton; // @synthesize startingCameraButton=_startingCameraButton;
- (double)transitionDuration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

