//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDateFormatter, TNDRPopularLocation;

@interface TNDRPassportPopularLocationViewModel : NSObject
{
    TNDRPopularLocation *_popularLocation;
    NSArray *_activeUserPhotos;
    NSDateFormatter *_dateFormatter;
}

- (void).cxx_destruct;
- (id)activeInLocationString;
@property(retain, nonatomic) NSArray *activeUserPhotos; // @synthesize activeUserPhotos=_activeUserPhotos;
- (id)avatarURLForIndexPath:(id)arg1;
- (id)cityName;
- (id)countryName;
@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
- (id)goToLocationString;
- (id)initWithPopularLocation:(id)arg1 dateFormatter:(id)arg2;
- (id)location;
- (id)locationImageURL;
- (int)numberOfActivePeople;
@property(retain, nonatomic) TNDRPopularLocation *popularLocation; // @synthesize popularLocation=_popularLocation;
- (id)populationString;
- (id)timeString;

@end

