//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TNDRURLNavigableProtocol.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UIViewControllerTransitioningDelegate.h"

@class NSIndexPath, NSLayoutConstraint, NSString, TNDRPassportLocationsHeaderView, TNDRPassportLocationsListViewModel, UIButton, UIImage, UIImageView, UITableView, UITapGestureRecognizer, UIView;

@interface TNDRPassportLocationsListViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, UIGestureRecognizerDelegate, UIViewControllerTransitioningDelegate, TNDRURLNavigableProtocol>
{
    UIView *_backgroundOverlay;
    UIView *_outerContainerView;
    UIView *_containerView;
    UIImageView *_downArrowImageView;
    UIButton *_closeButton;
    id <TNDRPassportLocationsListViewControllerDelegate> _delegate;
    TNDRPassportLocationsListViewModel *_viewModel;
    TNDRPassportLocationsHeaderView *_discoverPeopleInHeaderView;
    UITableView *_locationsTableView;
    UIButton *_addNewLocationButton;
    UITapGestureRecognizer *_tapGestureRecognizer;
    NSLayoutConstraint *_contentHeightConstraint;
    UIImageView *_closeImageView;
    UIView *_closeBackgroundView;
    int _locationsListState;
    NSIndexPath *_travelQueuedIndexPath;
}

+ (id)viewControllerNavigationKey;
- (void).cxx_destruct;
- (void)_autoLayoutSubviews;
- (BOOL)_canScrollWithTableContentHeight:(float)arg1;
- (void)_configureDefaultCellVisuals:(id)arg1;
- (float)_contentHeightForTargetTableContentHeight:(float)arg1;
- (float)_maxAvailableContentHeight;
- (void)_setupSubviews;
- (float)_totalContentHeightWithTableContentHeight:(float)arg1;
@property(retain, nonatomic) UIButton *addNewLocationButton; // @synthesize addNewLocationButton=_addNewLocationButton;
- (void)addNewLocationButtonTapped:(id)arg1;
@property(retain, nonatomic) UIView *backgroundOverlay; // @synthesize backgroundOverlay=_backgroundOverlay;
@property(readonly, nonatomic) UIImage *checkmarkImage;
@property(retain, nonatomic) UIView *closeBackgroundView; // @synthesize closeBackgroundView=_closeBackgroundView;
@property(nonatomic) __weak UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UIImageView *closeImageView; // @synthesize closeImageView=_closeImageView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) NSLayoutConstraint *contentHeightConstraint; // @synthesize contentHeightConstraint=_contentHeightConstraint;
@property(nonatomic) __weak id <TNDRPassportLocationsListViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) TNDRPassportLocationsHeaderView *discoverPeopleInHeaderView; // @synthesize discoverPeopleInHeaderView=_discoverPeopleInHeaderView;
@property(retain, nonatomic) UIImageView *downArrowImageView; // @synthesize downArrowImageView=_downArrowImageView;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (void)handleUserAuthenticated:(id)arg1;
- (id)initWithViewModel:(id)arg1;
@property(nonatomic) int locationsListState; // @synthesize locationsListState=_locationsListState;
@property(retain, nonatomic) UITableView *locationsTableView; // @synthesize locationsTableView=_locationsTableView;
- (void)marginTapped:(id)arg1;
- (int)numberOfSectionsInTableView:(id)arg1;
@property(retain, nonatomic) UIView *outerContainerView; // @synthesize outerContainerView=_outerContainerView;
- (void)queueTravelToLocationAtIndexPath:(id)arg1;
- (void)registerNotifications;
- (void)resetPassportButtonState;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(retain, nonatomic) NSIndexPath *travelQueuedIndexPath; // @synthesize travelQueuedIndexPath=_travelQueuedIndexPath;
@property(retain, nonatomic) TNDRPassportLocationsListViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)unregisterNotifications;
- (void)updateForTravelCompleted:(BOOL)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

