//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TNDRPassportPopularLocationCellDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSMutableDictionary, NSString, NSTimer, TNDRCentersFlowLayout, TNDRPassportStackLayout, TNDRPassportStackViewModel, UICollectionView, UILabel, UITapGestureRecognizer;

@interface TNDRPassportStackViewController : UIViewController <UICollectionViewDataSource, UICollectionViewDelegate, UIScrollViewDelegate, UIGestureRecognizerDelegate, TNDRPassportPopularLocationCellDelegate>
{
    id <TNDRPassportPaywallDelegate> _delegate;
    UICollectionView *_collectionView;
    TNDRCentersFlowLayout *_expandedFlowLayout;
    TNDRPassportStackLayout *_expandedStackLayout;
    TNDRPassportStackLayout *_collapsedStackLayout;
    UITapGestureRecognizer *_stackTapGestureRecognizer;
    NSTimer *_stackCollapseTimer;
    TNDRPassportStackViewModel *_viewModel;
    NSMutableDictionary *_cellViewModels;
    UILabel *_titleLabel;
}

- (void).cxx_destruct;
- (void)_cancelCollapseTimer;
- (void)_changeToCollapsedStackLayout;
- (void)_changeToExpandedFlowLayout;
- (void)_changeToExpandedStackLayout;
- (id)_popularLocationViewModelForCell:(id)arg1;
- (id)_popularLocationViewModelForIndexPath:(id)arg1;
- (void)_scheduleCollapseTimer;
- (void)_setupLayouts;
@property(retain, nonatomic) NSMutableDictionary *cellViewModels; // @synthesize cellViewModels=_cellViewModels;
@property(retain, nonatomic) TNDRPassportStackLayout *collapsedStackLayout; // @synthesize collapsedStackLayout=_collapsedStackLayout;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (void)configureCell:(id)arg1 atIndexPath:(id)arg2 onCell:(id)arg3;
@property(nonatomic) __weak id <TNDRPassportPaywallDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) TNDRCentersFlowLayout *expandedFlowLayout; // @synthesize expandedFlowLayout=_expandedFlowLayout;
@property(retain, nonatomic) TNDRPassportStackLayout *expandedStackLayout; // @synthesize expandedStackLayout=_expandedStackLayout;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (id)init;
- (id)initWithViewModel:(id)arg1;
- (int)numberOfActiveUsersForCell:(id)arg1;
- (int)numberOfSectionsInCollectionView:(id)arg1;
@property(retain, nonatomic) NSTimer *stackCollapseTimer; // @synthesize stackCollapseTimer=_stackCollapseTimer;
@property(retain, nonatomic) UITapGestureRecognizer *stackTapGestureRecognizer; // @synthesize stackTapGestureRecognizer=_stackTapGestureRecognizer;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) TNDRPassportStackViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void)tapped:(id)arg1;
- (void)tappedGoToLocationOnCell:(id)arg1;
- (void)timerFired:(id)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

