//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "UIScrollViewDelegate.h"

@class NSString, UIButton, UIImageView, UILabel, UIView;

@interface TNDRAddFriendCell : UITableViewCell <UIScrollViewDelegate>
{
    UIView *_overlay;
    UIImageView *_avatarImageView;
    UILabel *_nameLabel;
    UILabel *_statusLabel;
    UIButton *_addFriendButton;
    UIButton *_addTinderFriendButton;
    UIView *_separator;
    int _requestStatus;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *addFriendButton; // @synthesize addFriendButton=_addFriendButton;
@property(retain, nonatomic) UIButton *addTinderFriendButton; // @synthesize addTinderFriendButton=_addTinderFriendButton;
@property(retain, nonatomic) UIImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void)prepareForReuse;
@property(nonatomic) int requestStatus; // @synthesize requestStatus=_requestStatus;
@property(retain, nonatomic) UIView *separator; // @synthesize separator=_separator;
- (void)setAvatarImage:(id)arg1;
@property(retain, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
- (void)setup;
- (void)setupAddFriendButton;
- (void)setupAddTinderFriendButton;
- (void)setupAvatarImageView;
- (void)setupAvatarView;
- (void)setupBackground;
- (void)setupLabels;
- (void)setupOverlay;
- (void)setupSeparator;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

