//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImage, UIImageView, UILabel;

@interface TNDRCardStatView : UIView
{
    UILabel *_contentLabel;
    UIImage *_image;
    UIImageView *_imageView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setTintColor:(id)arg1;
- (void)setup;

@end

