//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewController.h"

@class NSArray, StyledPageControl, UICollectionViewFlowLayout, UIImage;

@interface TNDRPhotoPageController : UICollectionViewController
{
    StyledPageControl *_photoPageControl;
    UICollectionViewFlowLayout *_flowLayout;
    UIImage *_grayImage;
    id <TNDRPhotoPageControllerDelegate> _delegate;
    NSArray *_photoData;
    UIImage *_lastLoadedImage;
    unsigned int _averagedSelectedPhotoIndex;
    unsigned int _lastLoadedIndex;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int averagedSelectedPhotoIndex; // @synthesize averagedSelectedPhotoIndex=_averagedSelectedPhotoIndex;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
@property(nonatomic) __weak id <TNDRPhotoPageControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (id)initWithPhotoData:(id)arg1 andPageControl:(id)arg2;
@property(retain, nonatomic) UIImage *lastLoadedImage; // @synthesize lastLoadedImage=_lastLoadedImage;
@property(nonatomic) unsigned int lastLoadedIndex; // @synthesize lastLoadedIndex=_lastLoadedIndex;
- (int)numberOfSectionsInCollectionView:(id)arg1;
- (void)pageControlValueChanged:(id)arg1;
@property(retain, nonatomic) NSArray *photoData; // @synthesize photoData=_photoData;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)setCurrentPage:(unsigned int)arg1;
- (void)setupPageControl;
- (void)setupPhotosCollectionView;
- (void)updateCurrentlySelectedImage;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;

@end

