//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSDate, NSDictionary, NSString, NSURL, TNDRMoment, TNDRUser, TTTTimeIntervalFormatter, UIButton, UIImageView, UILabel, UIView;

@interface TNDRMyMomentsActivityCell : UITableViewCell
{
    NSDictionary *_nameStringAttributes;
    NSDictionary *_timeStringAttributes;
    NSString *_activityLikeString;
    NSString *_activityPostString;
    UIView *_separator;
    BOOL _lastCellInSection;
    TNDRMoment *_moment;
    TNDRUser *_user;
    NSURL *_avatarImageURL;
    NSURL *_momentImageURL;
    NSDate *_activityDate;
    int _activityType;
    UIImageView *_avatarImageView;
    id <TNDRMyMomentsActivityCellDelegate> _delegate;
    UIImageView *_momentThumbnailView;
    UILabel *_nameAndTimeLabel;
    UILabel *_activityLabel;
    UIButton *_momentThumbnailButton;
    TTTTimeIntervalFormatter *_timeFormatter;
    NSString *_formattedTimeString;
    NSString *_nameString;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDate *activityDate; // @synthesize activityDate=_activityDate;
@property(retain, nonatomic) UILabel *activityLabel; // @synthesize activityLabel=_activityLabel;
@property(nonatomic) int activityType; // @synthesize activityType=_activityType;
- (id)avatarImage;
@property(retain, nonatomic) NSURL *avatarImageURL; // @synthesize avatarImageURL=_avatarImageURL;
@property(retain, nonatomic) UIImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(nonatomic) __weak id <TNDRMyMomentsActivityCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *formattedTimeString; // @synthesize formattedTimeString=_formattedTimeString;
- (void)handleMomentThumbTapped:(id)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
@property(nonatomic) BOOL lastCellInSection; // @synthesize lastCellInSection=_lastCellInSection;
- (void)layoutSubviews;
@property(retain, nonatomic) TNDRMoment *moment; // @synthesize moment=_moment;
@property(retain, nonatomic) NSURL *momentImageURL; // @synthesize momentImageURL=_momentImageURL;
@property(retain, nonatomic) UIButton *momentThumbnailButton; // @synthesize momentThumbnailButton=_momentThumbnailButton;
@property(retain, nonatomic) UIImageView *momentThumbnailView; // @synthesize momentThumbnailView=_momentThumbnailView;
@property(retain, nonatomic) UILabel *nameAndTimeLabel; // @synthesize nameAndTimeLabel=_nameAndTimeLabel;
@property(retain, nonatomic) NSString *nameString; // @synthesize nameString=_nameString;
- (void)positionSeparator;
- (void)prepareForReuse;
- (void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
@property(retain, nonatomic) TTTTimeIntervalFormatter *timeFormatter; // @synthesize timeFormatter=_timeFormatter;
@property(retain, nonatomic) TNDRUser *user; // @synthesize user=_user;
- (void)setup;
- (void)setupAttributesForStrings;
- (void)setupAvatarImageView;
- (void)setupLabels;
- (void)setupMomentThumbnailView;
- (void)setupSeparator;
- (void)updateMomentImageView;
- (void)updateNameAndTimeLabelText;

@end

