//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

#import "TNDRURLNavigableProtocol.h"

@class NSString, NSURL, TNDRSansNavigationWebViewController;

@interface TNDRAdWebViewController : UINavigationController <TNDRURLNavigableProtocol>
{
    NSURL *_URL;
    id <TNDRAdWebViewControllerDelegate> _adWebViewControllerDelegate;
    TNDRSansNavigationWebViewController *_webViewController;
    NSString *_shareText;
    NSURL *_shareURL;
}

+ (id)viewControllerNavigationKey;
- (void).cxx_destruct;
@property(retain, nonatomic) NSURL *URL; // @synthesize URL=_URL;
@property(nonatomic) __weak id <TNDRAdWebViewControllerDelegate> adWebViewControllerDelegate; // @synthesize adWebViewControllerDelegate=_adWebViewControllerDelegate;
- (id)backgroundImageForNavigationBar;
- (id)backgroundImageForToolbar;
- (id)initWithURL:(id)arg1 adWebViewControllerDelegate:(id)arg2;
@property(retain, nonatomic) NSString *shareText; // @synthesize shareText=_shareText;
@property(retain, nonatomic) NSURL *shareURL; // @synthesize shareURL=_shareURL;
@property(nonatomic) __weak TNDRSansNavigationWebViewController *webViewController; // @synthesize webViewController=_webViewController;
- (void)setupNavigationBar;
- (void)setupToolbar;
- (id)shadowImageForNavigationBar;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;

// Remaining properties
@property(readonly, nonatomic) id <UIViewControllerAnimatedTransitioning> animationController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

