//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UICollectionViewDataSource.h"

@class NSArray, NSString;

@interface TNDRMomentStackDataSource : NSObject <UICollectionViewDataSource>
{
    NSArray *_objects;
    NSString *_reuseIdentifier;
    CDUnknownBlockType _cellConfigurationBlock;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType cellConfigurationBlock; // @synthesize cellConfigurationBlock=_cellConfigurationBlock;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (id)initWithObjects:(id)arg1 reuseIdentifier:(id)arg2 cellConfigurationBlock:(CDUnknownBlockType)arg3;
- (int)numberOfSectionsInCollectionView:(id)arg1;
@property(copy, nonatomic) NSArray *objects; // @synthesize objects=_objects;
@property(copy, nonatomic) NSString *reuseIdentifier; // @synthesize reuseIdentifier=_reuseIdentifier;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

