//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexPath, TNDRMomentCard;

@protocol TNDRMomentCardDelegate <NSObject>
- (void)didTapCardAtIndexPath:(NSIndexPath *)arg1;
- (void)didTapLikeAndMessageButtonOnCard:(TNDRMomentCard *)arg1;
- (void)didTapMoreInformationButtonAtIndexPath:(NSIndexPath *)arg1;
- (void)didTapProfileImageAtIndexPath:(NSIndexPath *)arg1;
- (struct CGRect)frameForCollapse;
- (struct CGAffineTransform)transformForIndex:(int)arg1;
@end

