//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, UIButton, UIImage, UIImageView;

@interface TNDRMomentsFooterView : UIView
{
    BOOL _isHiding;
    UIButton *_momentsCameraButton;
    UIImage *_momentsBackgroundGradient;
    UIImageView *_momentsBackgroundGradientView;
    NSArray *_buttonArray;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *buttonArray; // @synthesize buttonArray=_buttonArray;
- (void)handleDisableCameraButton:(id)arg1;
- (void)handleEnableCameraButton:(id)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
@property(nonatomic) BOOL isHiding; // @synthesize isHiding=_isHiding;
@property(retain, nonatomic) UIImage *momentsBackgroundGradient; // @synthesize momentsBackgroundGradient=_momentsBackgroundGradient;
@property(retain, nonatomic) UIImageView *momentsBackgroundGradientView; // @synthesize momentsBackgroundGradientView=_momentsBackgroundGradientView;
@property(retain, nonatomic) UIButton *momentsCameraButton; // @synthesize momentsCameraButton=_momentsCameraButton;
- (void)setupButtonsToAnimate;
- (void)showMomentsFooter:(BOOL)arg1 animated:(BOOL)arg2;

@end

