//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerTransitioningDelegate.h"

@class NSString, TNDRMatchesToMomentsCameraAnimationController, TNDRMomentsCameraButton;

@interface TNDRMatchesToMomentsCameraTransitioningDelegate : NSObject <UIViewControllerTransitioningDelegate>
{
    TNDRMomentsCameraButton *_startingCameraButton;
    TNDRMomentsCameraButton *_endingCameraButton;
    TNDRMatchesToMomentsCameraAnimationController *_transitioning;
}

- (void).cxx_destruct;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
@property(nonatomic) __weak TNDRMomentsCameraButton *endingCameraButton; // @synthesize endingCameraButton=_endingCameraButton;
@property(nonatomic) __weak TNDRMomentsCameraButton *startingCameraButton; // @synthesize startingCameraButton=_startingCameraButton;
@property(retain, nonatomic) TNDRMatchesToMomentsCameraAnimationController *transitioning; // @synthesize transitioning=_transitioning;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

