//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"

@class CLLocation, CLLocationManager, CLPlacemark, NSArray, NSData, NSDate, NSMutableDictionary, NSMutableSet, NSNumber, NSOrderedSet, NSString, NSTimer, NSURL, TNDRAccountWarningsViewModel, TNDRProductIdsViewModel;

@interface TNDRCurrentUser : NSObject <CLLocationManagerDelegate>
{
    BOOL _authenticated;
    BOOL _trending;
    BOOL _newUser;
    BOOL _newSubscriber;
    BOOL _userBlocked;
    BOOL _isSynchronizingWithServer;
    BOOL _isIOSVersion8;
    BOOL _metadataUpdateInProgress;
    BOOL _requestedWarningStateThisSession;
    NSData *_deviceToken;
    CLPlacemark *_placemark;
    NSOrderedSet *_photos;
    NSString *_userID;
    NSNumber *_userNumber;
    NSString *_tinderID;
    int _warningType;
    CLLocationManager *_locationManager;
    NSMutableSet *_seenUsers;
    NSDate *_lastDuplicateDate;
    NSMutableDictionary *_tinderFriends;
    TNDRProductIdsViewModel *_productIdsViewModel;
    TNDRAccountWarningsViewModel *_accountWarningsViewModel;
    NSTimer *_rateLimitedCheckMetadataTimer;
}

+ (id)abbreviatedStringForGender:(int)arg1;
+ (void)resetUserDefaultsValues;
+ (id)sharedCurrentUser;
- (void).cxx_destruct;
- (void)acceptAccountWarningNotification:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) NSDate *accountCreated;
@property(readonly, nonatomic) NSArray *accountWarnings;
@property(retain, nonatomic) TNDRAccountWarningsViewModel *accountWarningsViewModel; // @synthesize accountWarningsViewModel=_accountWarningsViewModel;
@property(readonly, nonatomic) NSString *activeSubscriptionProductIdentifier;
- (unsigned int)adSwipeInterval;
- (void)addPhotoWithFacebookID:(id)arg1 isMainPhoto:(BOOL)arg2 croppingRectInPercentages:(struct CGRect)arg3 completion:(CDUnknownBlockType)arg4;
- (void)addRecentLocation:(id)arg1 placemark:(id)arg2 predeterminedTitle:(id)arg3 predeterminedDescription:(id)arg4;
- (void)addSeenUser:(id)arg1;
@property(readonly, nonatomic) int ageFilterMax;
@property(readonly, nonatomic) int ageFilterMin;
- (void)aggregateAllCurrentUserDataInto:(id)arg1 inContext:(id)arg2;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
@property(readonly, nonatomic) NSString *bio;
@property(readonly, nonatomic) NSDate *birthdate;
- (void)checkForPlusExpiration;
- (void)clearUserInfoAndNotify;
- (void)clearUserInformation;
- (id)currentLanguageCode;
- (void)dealloc;
@property(readonly, copy) NSString *debugDescription;
- (void)deleteAccount:(CDUnknownBlockType)arg1;
- (void)deletePhotoWithID:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) NSData *deviceToken; // @synthesize deviceToken=_deviceToken;
@property(nonatomic, getter=didRequestWarningStateThisSession) BOOL requestedWarningStateThisSession; // @synthesize requestedWarningStateThisSession=_requestedWarningStateThisSession;
@property(nonatomic) BOOL discoverIsEnabled;
- (void)displayAlertForLocationChangeFailure;
@property(readonly, nonatomic) float distanceFilter;
@property(readonly, nonatomic) NSString *facebookID;
- (void)facebookSessionStateChanged:(id)arg1;
@property(readonly, nonatomic) NSDate *firstLogin;
@property(readonly, nonatomic) NSString *firstName;
@property(nonatomic) int gender;
@property(readonly, nonatomic) int genderFilter;
- (void)handleRateLimitedTimerUpdate:(id)arg1;
@property(nonatomic) BOOL hasAlreadySeenProfileEditTooltip;
@property(nonatomic) BOOL hasAlreadySharedMoment;
@property(nonatomic) BOOL hasCompletedIntroduction;
@property(nonatomic) BOOL hasCompletedMomentsTutorial;
@property(nonatomic, getter=hasEncounteredRateLimitingPaywall) BOOL encounteredRateLimitingPaywall;
@property(nonatomic) BOOL hasReachedOldestMoment;
- (BOOL)hasSeenUser:(id)arg1;
@property(readonly, nonatomic) NSString *home;
- (id)imageURLForWidth:(float)arg1;
- (void)incrementProfileRatedCount:(BOOL)arg1 liked:(BOOL)arg2;
- (id)init;
@property(readonly, nonatomic) int inviteType;
@property(nonatomic, getter=isAuthenticated) BOOL authenticated; // @synthesize authenticated=_authenticated;
- (BOOL)isCoordinate:(CDStruct_2c43369c)arg1 equivalentToCoordinate:(CDStruct_2c43369c)arg2 maximumDelta:(double)arg3;
@property(nonatomic) BOOL isIOSVersion8; // @synthesize isIOSVersion8=_isIOSVersion8;
@property(nonatomic, getter=isNewSubscriber) BOOL newSubscriber; // @synthesize newSubscriber=_newSubscriber;
@property(nonatomic, getter=isNewUser) BOOL newUser; // @synthesize newUser=_newUser;
@property(readonly, nonatomic) BOOL isRateLimited;
@property(nonatomic, getter=isSaveToCameraRollEnabled) BOOL saveToCameraRollEnabled;
@property(nonatomic, getter=isSillyModeEnabled) BOOL sillyModeEnabled;
@property(nonatomic) BOOL isSynchronizingWithServer; // @synthesize isSynchronizingWithServer=_isSynchronizingWithServer;
@property(readonly, nonatomic) BOOL isTinderPlusEnabled;
@property(readonly, nonatomic) BOOL isTinderPlusSubscriber;
@property(nonatomic, getter=isTraveling) BOOL traveling;
@property(nonatomic, getter=isTrending) BOOL trending; // @synthesize trending=_trending;
@property(readonly, nonatomic, getter=isUserBlocked) BOOL userBlocked; // @synthesize userBlocked=_userBlocked;
@property(nonatomic, getter=isVibrationEnabled) BOOL vibrationEnabled;
@property(retain, nonatomic) NSDate *lastDuplicateDate; // @synthesize lastDuplicateDate=_lastDuplicateDate;
@property(retain, nonatomic) NSDate *lastViewedMatches;
@property(retain, nonatomic) NSDate *lastViewedMyMomentsActivityDate;
@property(readonly, nonatomic) float likesAvailablePercentage;
@property(readonly, nonatomic) CLLocation *location;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
- (void)locationManagerDidPauseLocationUpdates:(id)arg1;
- (void)locationManagerDidResumeLocationUpdates:(id)arg1;
- (BOOL)locationManagerShouldDisplayHeadingCalibration:(id)arg1;
- (void)logFailedPhotoDeletion:(id)arg1 request:(id)arg2 response:(id)arg3;
- (void)logFailedServerUpdateForPhotoPositions:(id)arg1 request:(id)arg2 response:(id)arg3;
- (void)logout:(CDUnknownBlockType)arg1;
@property(nonatomic) BOOL metadataUpdateInProgress; // @synthesize metadataUpdateInProgress=_metadataUpdateInProgress;
@property(nonatomic) BOOL needsAttention;
- (void)parsePassportJSONData:(id)arg1;
- (void)performBlockForMockUser:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) NSOrderedSet *photos; // @synthesize photos=_photos;
@property(retain, nonatomic) CLPlacemark *placemark; // @synthesize placemark=_placemark;
- (void)precacheUserImages;
- (void)processAccountNotificationsJSON:(id)arg1;
- (void)processMetadataJSON:(id)arg1;
- (void)processProductIDJSONInformation:(id)arg1;
- (void)processPurchasesJSONInformation:(id)arg1;
- (void)processRateLimitingJSON:(id)arg1;
- (void)processUserJSONIntoUserDefaults:(id)arg1;
- (id)productIdentifiers;
@property(retain, nonatomic) TNDRProductIdsViewModel *productIdsViewModel; // @synthesize productIdsViewModel=_productIdsViewModel;
@property(retain, nonatomic) NSTimer *rateLimitedCheckMetadataTimer; // @synthesize rateLimitedCheckMetadataTimer=_rateLimitedCheckMetadataTimer;
@property(readonly, nonatomic) NSDate *rateLimitingLikesResetDate;
@property(readonly, nonatomic) long long rateLimitingLikesResetDateForAnalytics;
@property(nonatomic) BOOL receivesLikeNotifications;
@property(nonatomic) BOOL receivesMatchNotifications;
@property(nonatomic) BOOL receivesMatchRequestNotifications;
@property(nonatomic) BOOL receivesMessageNotifications;
@property(readonly, nonatomic) NSArray *recentLocations;
- (void)registerForNotifications;
- (void)removeSeenUser:(id)arg1;
- (void)requestAccountWarningsViewModelWithCompletion:(CDUnknownBlockType)arg1;
- (void)resetApplicationState;
- (void)resetRateLimitingLimitations;
- (void)restoreEncounteredValueFromSavedData;
- (void)retrieveAccountWarningState;
- (void)saveGlobalsToUserDefaults:(id)arg1;
- (void)saveMinimumVersioningInformation:(id)arg1;
- (void)saveProcessedDataIntoCoreDataUser;
@property(retain, nonatomic) NSMutableSet *seenUsers; // @synthesize seenUsers=_seenUsers;
- (void)setLikesAvailablePercentage:(float)arg1;
- (void)setRateLimitingLikesResetDate:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *tinderFriends; // @synthesize tinderFriends=_tinderFriends;
@property(retain, nonatomic) NSString *tinderID; // @synthesize tinderID=_tinderID;
@property(retain, nonatomic) NSString *userID; // @synthesize userID=_userID;
@property(retain, nonatomic) NSNumber *userNumber; // @synthesize userNumber=_userNumber;
- (void)setupLocationManager;
@property(readonly, nonatomic) NSURL *smallAvatarImageURL;
- (void)startLocationMonitoring;
- (void)stopLocationMonitoring;
- (id)stopTravelingCompletion:(CDUnknownBlockType)arg1;
- (void)storeAdSwipeIntervalInDefaults:(id)arg1;
@property(readonly, nonatomic) NSMutableDictionary *superProperties;
- (void)synchronizeCoreDataStoreWithServer:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) double timeIntervalUntilRateLimitReset;
- (void)timestampFirstLoginToNow;
- (void)trackMixpanel:(id)arg1 properties:(id)arg2;
- (void)trackSparks:(id)arg1 properties:(id)arg2;
- (id)travelToLocation:(id)arg1 placemark:(id)arg2 predeterminedTitle:(id)arg3 predeterminedDescription:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)updateCurrentUserMetadata;
- (void)updateInformation:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)updateLocation;
- (void)updateServerWithPhotoPositions:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)updateSmallAvatarURL;
- (id)userInContext:(id)arg1;
- (void)userLocationChanged;
- (void)verifyLocationAccess;
@property(readonly, nonatomic) int warningType; // @synthesize warningType=_warningType;

// Remaining properties
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

