//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol TNDRMomentsCameraOverlayDelegate <NSObject>
- (void)didChangeZoomSlider:(float)arg1;
- (BOOL)didLongPressToLockFocusAndExposurePointAt:(struct CGPoint)arg1;
- (void)didSelectToCloseCamera:(BOOL)arg1;
- (void)didSelectToOpenCameraRoll;
- (void)didSelectToTakePhotoWithCamera:(int)arg1;
- (BOOL)didTapToFocusPointAt:(struct CGPoint)arg1;
- (void)didToggleCameraDevice;
- (void)didToggleCameraFlash:(int)arg1;
@end

