//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSLayoutConstraint, UIButton, UIImageView, UILabel;

@interface TNDRMomentCardFullScreenInfoView : UIView
{
    BOOL _presentedFromChat;
    UIImageView *_avatarImageView;
    UILabel *_nameLabel;
    UILabel *_timeLabel;
    UIButton *_moreOptionsButton;
    UIButton *_likeAndMessageButton;
    NSLayoutConstraint *_moreOptionsButtonConstraint;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
- (void)buildMoreOptionsButton;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UIButton *likeAndMessageButton; // @synthesize likeAndMessageButton=_likeAndMessageButton;
@property(retain, nonatomic) UIButton *moreOptionsButton; // @synthesize moreOptionsButton=_moreOptionsButton;
@property(retain, nonatomic) NSLayoutConstraint *moreOptionsButtonConstraint; // @synthesize moreOptionsButtonConstraint=_moreOptionsButtonConstraint;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) BOOL presentedFromChat; // @synthesize presentedFromChat=_presentedFromChat;
- (void)resetMoreOptionsButtonToBePinnedToRight;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
- (void)setup;
- (void)setupLikeAndMessageButton;
- (void)setupMoreOptionsButton;
- (void)setupNameLabel;
- (void)setupProfileImageView;
- (void)setupTimeLabel;
- (void)transferActionsFrom:(id)arg1 toButton:(id)arg2;

@end

