//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewController.h"

#import "NSFetchedResultsControllerDelegate.h"

@class NSFetchRequest, NSFetchedResultsController, NSManagedObjectContext, NSMutableArray, NSString, UIActivityIndicatorView, UICollectionViewFlowLayout;

@interface TNDRProfileHorizontalViewController : UICollectionViewController <NSFetchedResultsControllerDelegate>
{
    UICollectionViewFlowLayout *_collectionViewFlowLayout;
    NSString *_cellIdentifier;
    UIActivityIndicatorView *_spinnerView;
    NSMutableArray *_fetchedObjectChanges;
    NSFetchedResultsController *_fetchedResultsController;
    NSFetchRequest *_fetchRequest;
    NSManagedObjectContext *_externalContext;
}

- (void).cxx_destruct;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (void)configureCell:(id)arg1 forIndexPath:(id)arg2;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned int)arg4 newIndexPath:(id)arg5;
- (void)controllerDidChangeContent:(id)arg1;
@property(retain, nonatomic) NSManagedObjectContext *externalContext; // @synthesize externalContext=_externalContext;
@property(retain, nonatomic) NSFetchRequest *fetchRequest; // @synthesize fetchRequest=_fetchRequest;
@property(retain, nonatomic) NSFetchedResultsController *fetchedResultsController; // @synthesize fetchedResultsController=_fetchedResultsController;
- (id)initWithContext:(id)arg1 fetchRequest:(id)arg2;
- (float)neededHeight;
- (int)numberOfSectionsInCollectionView:(id)arg1;
- (void)setup;
- (void)setupCollectionView;
- (void)setupFetchedResultsController;
- (void)viewDidLoad;

@end

