//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "RMStoreObserver.h"
#import "TNDRPaywallManagerDelegate.h"
#import "TNDRRecommendationViewControllerRecsSessionTracking.h"
#import "TNDRURLNavigableProtocol.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSDictionary, NSString, TNDRPassportPaywallViewModel, UIButton, UITableView, UIView;

@interface TNDRTinderPlusPaywallViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, UIGestureRecognizerDelegate, RMStoreObserver, TNDRPaywallManagerDelegate, TNDRURLNavigableProtocol, TNDRRecommendationViewControllerRecsSessionTracking>
{
    id <TNDRTinderPlusPaywallViewControllerDelegate> _delegate;
    UIView *_backgroundOverlay;
    UIView *_containerView;
    UIButton *_restorePurchaseButton;
    UITableView *_tableView;
    NSDictionary *_features;
    NSArray *_featureKeys;
    UIButton *_purchaseButton;
    unsigned int _willEncounterFrom;
    TNDRPassportPaywallViewModel *_paywallViewModel;
}

+ (id)sharedPaywallViewController;
+ (id)tinderPlusAvailableFeatureKeys;
+ (id)viewControllerNavigationKey;
- (void).cxx_destruct;
- (void)adjustContentDimensions;
@property(retain, nonatomic) UIView *backgroundOverlay; // @synthesize backgroundOverlay=_backgroundOverlay;
- (float)bottomInsetForHeaderCopyText;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
- (void)dealloc;
@property(nonatomic) __weak id <TNDRTinderPlusPaywallViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didTapPurchaseButton:(id)arg1;
- (void)didTapRestorePurchaseButton:(id)arg1;
- (void)dismissPaywallDialog;
@property(retain, nonatomic) NSArray *featureKeys; // @synthesize featureKeys=_featureKeys;
@property(retain, nonatomic) NSDictionary *features; // @synthesize features=_features;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (void)handleTapInView:(id)arg1;
- (void)handleTinderPlusWasActivated:(id)arg1;
- (float)headerHeightForTableView;
- (BOOL)inboundSegueShouldTriggerRecsSessionEnd;
- (id)init;
- (void)notifyPaywallPresentationReadinessWithCompletion:(CDUnknownBlockType)arg1;
- (void)paywallPurchaseCancelled;
- (void)paywallPurchaseFailed;
- (void)paywallPurchaseNotAllowed;
- (void)paywallPurchaseSucceeded;
@property(retain, nonatomic) TNDRPassportPaywallViewModel *paywallViewModel; // @synthesize paywallViewModel=_paywallViewModel;
- (void)preparePaywallFrom:(unsigned int)arg1 withCompletion:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) UIButton *purchaseButton; // @synthesize purchaseButton=_purchaseButton;
@property(readonly, nonatomic) int purchasedFromFeature;
@property(retain, nonatomic) UIButton *restorePurchaseButton; // @synthesize restorePurchaseButton=_restorePurchaseButton;
- (float)rowHeightForTableCells;
- (void)scaleAnimation:(id)arg1;
- (void)scaleToDefault:(id)arg1;
- (void)scaleToSmall:(id)arg1;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) unsigned int willEncounterFrom; // @synthesize willEncounterFrom=_willEncounterFrom;
- (void)setupFeatures;
- (void)setupGestureRecognizer;
- (void)setupPaywallViewModelWithCompletion:(CDUnknownBlockType)arg1;
- (void)setupTinderPlusTableViewFooter;
- (void)setupTinderPlusTableViewHeader;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)topInsetForHeaderTitleImage;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (id)windowForHUD;

// Remaining properties
@property(readonly, nonatomic) id <UIViewControllerAnimatedTransitioning> animationController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

