//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSDictionary, TNDRUser;

@interface TNDRUpdatesMergeOperation : NSOperation
{
    BOOL _isFinished;
    BOOL _hasNewMatch;
    BOOL _isMatch;
    NSDictionary *_updatesJSON;
    NSDictionary *_matchJSON;
    TNDRUser *_userToAssociate;
    int _mergeType;
}

- (void).cxx_destruct;
@property(nonatomic) BOOL hasNewMatch; // @synthesize hasNewMatch=_hasNewMatch;
- (id)initWithMatchToMerge:(id)arg1 andUserForMatch:(id)arg2;
- (id)initWithMatchesToMerge:(id)arg1;
- (BOOL)isFinished;
@property(nonatomic) BOOL isMatch; // @synthesize isMatch=_isMatch;
@property(retain, nonatomic) NSDictionary *matchJSON; // @synthesize matchJSON=_matchJSON;
- (void)mergeRecLike;
@property(nonatomic) int mergeType; // @synthesize mergeType=_mergeType;
- (void)mergeUpdates;
- (void)setFinished:(BOOL)arg1;
@property(retain, nonatomic) NSDictionary *updatesJSON; // @synthesize updatesJSON=_updatesJSON;
@property(retain, nonatomic) TNDRUser *userToAssociate; // @synthesize userToAssociate=_userToAssociate;
- (void)start;

@end

