//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class NSURL, TNDRCardStatView, UIActivityIndicatorView, UIImageView, UILabel, UIView;

@interface TNDRRecommendationCardCell : UICollectionViewCell
{
    BOOL _liked;
    UIImageView *_cardBackground;
    UIImageView *_profileImageView;
    UIView *_cardContentView;
    UIView *_infoView;
    UILabel *_nameAndAgeLabel;
    TNDRCardStatView *_commonFriendsStatView;
    TNDRCardStatView *_commonInterestsStatView;
    NSURL *_profileImageURL;
    UIImageView *_likeStampView;
    UIImageView *_passStampView;
    UILabel *_rewindLabel;
    UIView *_cardSnapshot;
    UIActivityIndicatorView *_activityIndicator;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
- (void)applyLayoutAttributes:(id)arg1;
@property(retain, nonatomic) UIImageView *cardBackground; // @synthesize cardBackground=_cardBackground;
@property(retain, nonatomic) UIView *cardContentView; // @synthesize cardContentView=_cardContentView;
@property(retain, nonatomic) UIView *cardSnapshot; // @synthesize cardSnapshot=_cardSnapshot;
@property(retain, nonatomic) TNDRCardStatView *commonFriendsStatView; // @synthesize commonFriendsStatView=_commonFriendsStatView;
@property(retain, nonatomic) TNDRCardStatView *commonInterestsStatView; // @synthesize commonInterestsStatView=_commonInterestsStatView;
- (void)configureCommonFriendsViewForUser:(id)arg1;
- (void)configureCommonInterestsViewForUser:(id)arg1;
- (void)configureForUser:(id)arg1;
- (void)configureNameAndAgeLabelForUser:(id)arg1;
- (void)configurePhotoViewForUser:(id)arg1;
@property(retain, nonatomic) UIView *infoView; // @synthesize infoView=_infoView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutCommonFriendsStatView;
- (void)layoutCommonInterestsStatView;
- (void)layoutNameAndAgeLabel;
- (void)layoutSubviews;
@property(retain, nonatomic) UIImageView *likeStampView; // @synthesize likeStampView=_likeStampView;
@property(nonatomic) BOOL liked; // @synthesize liked=_liked;
@property(retain, nonatomic) UILabel *nameAndAgeLabel; // @synthesize nameAndAgeLabel=_nameAndAgeLabel;
@property(retain, nonatomic) UIImageView *passStampView; // @synthesize passStampView=_passStampView;
- (void)prepareForReuse;
@property(retain, nonatomic) NSURL *profileImageURL; // @synthesize profileImageURL=_profileImageURL;
@property(retain, nonatomic) UIImageView *profileImageView; // @synthesize profileImageView=_profileImageView;
@property(retain, nonatomic) UILabel *rewindLabel; // @synthesize rewindLabel=_rewindLabel;
- (void)setFrame:(struct CGRect)arg1;
- (void)setup;
- (void)setupActivityIndicator;
- (void)setupCardBackground;
- (void)setupCardContentView;
- (void)setupCommonFriendsStatView;
- (void)setupCommonInterestsStatView;
- (void)setupImage;
- (void)setupInfo;
- (void)setupInfoView;
- (void)setupNameAndAgeLabel;
- (void)setupProfileImageView;
- (id)statDefaultTintColor;
- (void)updatePhotoViewWithNewSelectionFromUser:(id)arg1;

@end

