//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TNDRCardCell.h"

#import "TNDRCardCellViewProvider.h"

@class NSString, TNDRCardCellUserInformationView, TNDRCardCellUserProfilePhotoView, TNDRUser;

@interface TNDRUserCardCell : TNDRCardCell <TNDRCardCellViewProvider>
{
    TNDRUser *_user;
    TNDRCardCellUserProfilePhotoView *_profilePhotoView;
    TNDRCardCellUserInformationView *_informationView;
}

- (void).cxx_destruct;
- (id)contentView;
@property(retain, nonatomic) TNDRCardCellUserInformationView *informationView; // @synthesize informationView=_informationView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)prepareForReuse;
@property(retain, nonatomic) TNDRCardCellUserProfilePhotoView *profilePhotoView; // @synthesize profilePhotoView=_profilePhotoView;
- (id)secondaryView;
@property(retain, nonatomic) TNDRUser *user; // @synthesize user=_user;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

