//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIWindow;

@protocol TNDRPaywallManagerDelegate <NSObject>
- (void)paywallPurchaseCancelled;
- (void)paywallPurchaseFailed;
- (void)paywallPurchaseNotAllowed;
- (void)paywallPurchaseSucceeded;
- (UIWindow *)windowForHUD;
@end

