//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class FBKVOController, NSString, UIImageView, UILabel;

@interface TNDRWhatsNewCell : UITableViewCell
{
    UIImageView *_avatarImageView;
    NSString *_textLabelString;
    UILabel *_descriptionTextLabel;
    FBKVOController *_KVOController;
}

- (void).cxx_destruct;
@property(retain, nonatomic) FBKVOController *KVOController; // @synthesize KVOController=_KVOController;
@property(retain, nonatomic) UIImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) UILabel *descriptionTextLabel; // @synthesize descriptionTextLabel=_descriptionTextLabel;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
@property(retain, nonatomic) NSString *textLabelString; // @synthesize textLabelString=_textLabelString;
- (void)setup;

@end

