//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary;

@interface TNDRReportReasonsViewModel : NSObject
{
    NSArray *_reportingReasons;
    NSDictionary *_reportingReasonsImageNames;
    NSDictionary *_reportingReasonsStrings;
}

+ (id)analyticsReportKeyForReason:(unsigned int)arg1;
- (void).cxx_destruct;
- (id)imageForIndexPath:(id)arg1;
- (id)imageForReportingReason:(unsigned int)arg1;
- (id)init;
- (id)localizedStringForIndexPath:(id)arg1;
- (id)localizedStringForReportingReason:(unsigned int)arg1;
- (id)localizedStringsForReportReasons:(id)arg1;
@property(readonly, nonatomic) NSArray *reportingReasons; // @synthesize reportingReasons=_reportingReasons;
@property(retain, nonatomic) NSDictionary *reportingReasonsImageNames; // @synthesize reportingReasonsImageNames=_reportingReasonsImageNames;
@property(retain, nonatomic) NSDictionary *reportingReasonsStrings; // @synthesize reportingReasonsStrings=_reportingReasonsStrings;
- (void)requestReportReasonsWithCompletion:(CDUnknownBlockType)arg1;

@end

