//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

#import "NSFetchedResultsControllerDelegate.h"

@class NSFetchedResultsController, TNDRMoment, TNDRMomentFailedOverlay, TNDRMyMomentsNotificationBubble, UIImageView;

@interface TNDRMyMomentsActivityButton : UIButton <NSFetchedResultsControllerDelegate>
{
    TNDRMomentFailedOverlay *_failureOverlay;
    NSFetchedResultsController *_momentsFetchedResultsController;
    NSFetchedResultsController *_momentsLikesFetchedResultsController;
    TNDRMoment *_lastPostedMoment;
    UIImageView *_momentImageView;
    TNDRMyMomentsNotificationBubble *_notificationBubbleView;
}

- (void).cxx_destruct;
- (void)checkForAnyFailedMoments;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned int)arg4 newIndexPath:(id)arg5;
- (void)controller:(id)arg1 didChangeSection:(id)arg2 atIndex:(unsigned int)arg3 forChangeType:(unsigned int)arg4;
- (void)controllerDidChangeContent:(id)arg1;
- (void)controllerWillChangeContent:(id)arg1;
@property(retain, nonatomic) TNDRMomentFailedOverlay *failureOverlay; // @synthesize failureOverlay=_failureOverlay;
- (void)handleUserDidLogin:(id)arg1;
- (void)hide;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) TNDRMoment *lastPostedMoment; // @synthesize lastPostedMoment=_lastPostedMoment;
@property(retain, nonatomic) UIImageView *momentImageView; // @synthesize momentImageView=_momentImageView;
@property(retain, nonatomic) NSFetchedResultsController *momentsFetchedResultsController; // @synthesize momentsFetchedResultsController=_momentsFetchedResultsController;
@property(retain, nonatomic) NSFetchedResultsController *momentsLikesFetchedResultsController; // @synthesize momentsLikesFetchedResultsController=_momentsLikesFetchedResultsController;
@property(retain, nonatomic) TNDRMyMomentsNotificationBubble *notificationBubbleView; // @synthesize notificationBubbleView=_notificationBubbleView;
- (void)setup;
- (void)setupFetchedResultsController;
- (void)setupNotifications;
- (void)setupSubviews;
- (void)show;
- (void)updateButton;
- (void)updateLastFetchedMoment;
- (void)updateNumberOfMoments;

@end

