//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TNDRTitleButtonDelegate.h"
#import "UIPageViewControllerDataSource.h"
#import "UIPageViewControllerDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSArray, NSString, TNDRTitleButton, UINavigationBar, UIPageViewController, UIScrollView;

@interface TNDRBaseSlidingPagedController : UIViewController <UIPageViewControllerDataSource, UIPageViewControllerDelegate, UIScrollViewDelegate, TNDRTitleButtonDelegate>
{
    BOOL _isTransitioning;
    BOOL _allowScrollTransitionForHeaderTap;
    TNDRTitleButton *_leftmostHeaderItem;
    TNDRTitleButton *_rightmostHeaderItem;
    UIPageViewController *_pagedViewController;
    UIScrollView *_pagedScrollView;
    UINavigationBar *_navigationBar;
    NSArray *_viewControllers;
    NSArray *_headerTitleButtons;
    int _centerIndex;
    float _currentIndex;
    int _lastIndex;
    TNDRTitleButton *_titleL2;
    TNDRTitleButton *_titleL1;
    TNDRTitleButton *_titleButton;
    TNDRTitleButton *_titleR1;
    TNDRTitleButton *_titleR2;
}

- (void).cxx_destruct;
- (void)adjustButton:(id)arg1 forSide:(int)arg2 percentOffset:(float)arg3 fullWidth:(float)arg4 normalizedOffset:(float)arg5;
- (void)adjustCurrentIndexToScrollOffset:(float)arg1;
- (void)adjustHeaderItemsTitlenessForNormalizedOffset:(float)arg1;
- (void)adjustHeaderNavigationItemsToScrollOffset:(float)arg1;
- (void)adjustNavigationBarForNormalizedOffset:(float)arg1;
@property(nonatomic) BOOL allowScrollTransitionForHeaderTap; // @synthesize allowScrollTransitionForHeaderTap=_allowScrollTransitionForHeaderTap;
- (void)applyRotationIfNeededOnButton:(id)arg1 normalizedOffset:(float)arg2;
- (void)assignScrollViewDelegateToSelfFrom:(id)arg1;
@property(nonatomic) int centerIndex; // @synthesize centerIndex=_centerIndex;
@property(nonatomic) float currentIndex; // @synthesize currentIndex=_currentIndex;
- (id)currentlyVisibleViewController;
- (void)didDragInsideTitleButton;
- (void)didReceiveMemoryWarning;
- (void)didTouchDownInsideTitleButton;
- (void)didTouchUpInsideTitleButton;
- (void)disableAllInteraction;
- (void)enableAllInteraction;
- (void)extendHitEdgeForButton:(id)arg1;
- (void)extendHitEdgesForTitleButtons;
- (void)handleHeaderButtonTap:(id)arg1;
@property(retain, nonatomic) NSArray *headerTitleButtons; // @synthesize headerTitleButtons=_headerTitleButtons;
- (int)indexOfCurrentlyVisibleViewController;
- (int)indexOfViewController:(id)arg1;
- (id)initWithViewControllerSets:(id)arg1 initialViewControllerIndex:(int)arg2;
- (id)initWithViewControllers:(id)arg1 headerTitleButtons:(id)arg2 initialViewControllerIndex:(int)arg3;
@property(nonatomic) BOOL isTransitioning; // @synthesize isTransitioning=_isTransitioning;
@property(nonatomic) int lastIndex; // @synthesize lastIndex=_lastIndex;
@property(retain, nonatomic) TNDRTitleButton *leftmostHeaderItem; // @synthesize leftmostHeaderItem=_leftmostHeaderItem;
@property(retain, nonatomic) UINavigationBar *navigationBar; // @synthesize navigationBar=_navigationBar;
- (float)normalizedOffsetFromScrollOffset:(float)arg1;
- (void)notifyDidTransitionToViewController;
- (void)notifyWillTransitionToViewController:(int)arg1;
- (void)pageViewController:(id)arg1 didFinishAnimating:(BOOL)arg2 previousViewControllers:(id)arg3 transitionCompleted:(BOOL)arg4;
- (id)pageViewController:(id)arg1 viewControllerAfterViewController:(id)arg2;
- (id)pageViewController:(id)arg1 viewControllerBeforeViewController:(id)arg2;
- (void)pageViewController:(id)arg1 willTransitionToViewControllers:(id)arg2;
@property(retain, nonatomic) UIScrollView *pagedScrollView; // @synthesize pagedScrollView=_pagedScrollView;
@property(retain, nonatomic) UIPageViewController *pagedViewController; // @synthesize pagedViewController=_pagedViewController;
- (void)resetHeaderTitleItemsTransform;
@property(retain, nonatomic) TNDRTitleButton *rightmostHeaderItem; // @synthesize rightmostHeaderItem=_rightmostHeaderItem;
- (struct CGAffineTransform)rotationForTitleItemAtOffset:(float)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
@property(retain, nonatomic) TNDRTitleButton *titleButton; // @synthesize titleButton=_titleButton;
@property(retain, nonatomic) TNDRTitleButton *titleL1; // @synthesize titleL1=_titleL1;
@property(retain, nonatomic) TNDRTitleButton *titleL2; // @synthesize titleL2=_titleL2;
@property(retain, nonatomic) TNDRTitleButton *titleR1; // @synthesize titleR1=_titleR1;
@property(retain, nonatomic) TNDRTitleButton *titleR2; // @synthesize titleR2=_titleR2;
@property(retain, nonatomic) NSArray *viewControllers; // @synthesize viewControllers=_viewControllers;
- (void)setupHeaderItemsForIndex:(int)arg1;
- (void)setupHeaderItemsForIndex:(int)arg1 offset:(float)arg2;
- (void)setupHeaderTitleButtonActions;
- (void)setupNavigationBar;
- (void)setupWithViewControllers:(id)arg1 headerTitleButtons:(id)arg2 initialIndex:(int)arg3;
- (void)transitionToViewController:(id)arg1;
- (void)transitionToViewController:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)transitionToViewControllerAtIndex:(int)arg1;
- (void)transitionToViewControllerAtIndex:(int)arg1 completion:(CDUnknownBlockType)arg2;
- (void)transitionToViewControllerWithDirection:(int)arg1 fromIndex:(int)arg2 numberOfTimes:(int)arg3 completion:(CDUnknownBlockType)arg4;
- (void)translateHeaderTitleItems:(float)arg1;
- (void)updateInternalViewControllerArray:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (float)xAdjustForButton:(id)arg1 side:(int)arg2 percentOffset:(float)arg3;
- (float)xOffsetForButtonSide:(int)arg1 fullWidth:(float)arg2 percentOffset:(float)arg3 xAdjust:(float)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

