//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TNDRCrayonColorPickerDelegate.h"
#import "TNDRDrawing.h"
#import "TNDREditMomentTransitionProtocol.h"
#import "TNDREditMomentsTextViewDelegate.h"
#import "TNDRFilterDelegate.h"
#import "TNDRURLNavigableProtocol.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITextFieldDelegate.h"
#import "UITextViewDelegate.h"

@class NSString, TNDRColorPickerView, TNDRDrawOnViewGL, TNDREditMomentButtonAnimationManager, TNDREditMomentButtonContainerView, TNDREditMomentsTextView, TNDRFilterViewController, UIActivityIndicatorView, UIButton, UIColor, UIImage, UIImageView, UIPanGestureRecognizer, UITapGestureRecognizer, UIView;

@interface TNDREditMomentViewController : UIViewController <UIGestureRecognizerDelegate, UITextFieldDelegate, UITextViewDelegate, TNDRCrayonColorPickerDelegate, TNDRFilterDelegate, TNDREditMomentsTextViewDelegate, TNDREditMomentTransitionProtocol, TNDRDrawing, TNDRURLNavigableProtocol>
{
    BOOL _isAddingText;
    BOOL _selectedSmallText;
    BOOL _editingText;
    BOOL _pickingTextColor;
    BOOL _isSharing;
    BOOL _openedEditWithButton;
    BOOL _easterEgg;
    BOOL _keyboardShowing;
    BOOL _hasAnimatedFromTransition;
    BOOL _isDismissing;
    id <TNDREditMomentDelegate> _delegate;
    int _captureCameraState;
    UIImageView *_imageView;
    UIPanGestureRecognizer *_panGestureRecognizer;
    UITapGestureRecognizer *_tapGestureRecognizer;
    TNDRDrawOnViewGL *_drawingView;
    UIButton *_btnClose;
    UIButton *_btnFlash;
    UIButton *_btnReverseCamera;
    UIButton *_btnCameraRoll;
    UIView *_matchViewSnapshot;
    int _editingState;
    int _textSize;
    UIImage *_imageToEdit;
    UIImage *_originalImage;
    TNDREditMomentsTextView *_textView;
    TNDREditMomentsTextView *_helperTextView;
    TNDRColorPickerView *_colorPicker;
    UIColor *_currentSelectedDrawColor;
    UIColor *_currentSelectedTextColor;
    TNDRFilterViewController *_filterViewController;
    int _currentFilter;
    UIView *_headerDarken;
    UIView *_footerDarken;
    TNDREditMomentButtonContainerView *_buttonContainerView;
    TNDREditMomentButtonAnimationManager *_buttonAnimationManager;
    UIActivityIndicatorView *_indicatorView2;
    UIView *_firstShareBackgroundView;
    UIView *_firstShareContainer;
    UIImage *_circlePic;
    UIImage *_compositedImageToShare;
    int _editMomentDefaultTextHeight;
    struct CGSize _keyboardSize;
    struct CGRect _defaultImageFrame;
    struct CGAffineTransform _previousTextFieldTransform;
}

+ (id)viewControllerNavigationKey;
- (void).cxx_destruct;
- (float)allowedTextMovementHeight;
- (struct CGRect)allowedTextMovementRect;
- (float)allowedTextMovementRegionPercent;
- (void)animateEditingButtons;
- (void)animateForDismissalCompletion:(CDUnknownBlockType)arg1;
- (void)animateInColorPickerForEditState:(int)arg1;
- (void)animateInFirstShare;
- (void)animateOutFirstShareForSharing:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (void)animateSave:(id)arg1;
- (void)animateVisibleTextFieldToKeyboard;
- (void)backButtonTapped:(id)arg1;
- (id)backgroundImageForDrawButton;
- (struct CGAffineTransform)bottomTextViewTransform;
@property(retain, nonatomic) UIButton *btnCameraRoll; // @synthesize btnCameraRoll=_btnCameraRoll;
@property(retain, nonatomic) UIButton *btnClose; // @synthesize btnClose=_btnClose;
@property(retain, nonatomic) UIButton *btnFlash; // @synthesize btnFlash=_btnFlash;
@property(retain, nonatomic) UIButton *btnReverseCamera; // @synthesize btnReverseCamera=_btnReverseCamera;
@property(retain, nonatomic) TNDREditMomentButtonAnimationManager *buttonAnimationManager; // @synthesize buttonAnimationManager=_buttonAnimationManager;
@property(retain, nonatomic) TNDREditMomentButtonContainerView *buttonContainerView; // @synthesize buttonContainerView=_buttonContainerView;
- (BOOL)canFitTextSize:(int)arg1;
@property(nonatomic) int captureCameraState; // @synthesize captureCameraState=_captureCameraState;
- (void)changeToDrawingMode;
- (void)changeToEditingState:(int)arg1;
- (void)changeToFilterEditingMode;
- (void)changeToPreviewMode;
- (void)changeToTextEditingMode;
@property(retain, nonatomic) UIImage *circlePic; // @synthesize circlePic=_circlePic;
- (void)colorButtonTapped:(id)arg1;
@property(retain, nonatomic) TNDRColorPickerView *colorPicker; // @synthesize colorPicker=_colorPicker;
@property(retain, nonatomic) UIImage *compositedImageToShare; // @synthesize compositedImageToShare=_compositedImageToShare;
- (void)configureInteractionForEndingDrawing:(CDUnknownBlockType)arg1;
- (void)configureInteractionForStartingDrawing;
- (id)copyButton:(id)arg1;
@property(nonatomic) int currentFilter; // @synthesize currentFilter=_currentFilter;
@property(retain, nonatomic) UIColor *currentSelectedDrawColor; // @synthesize currentSelectedDrawColor=_currentSelectedDrawColor;
@property(retain, nonatomic) UIColor *currentSelectedTextColor; // @synthesize currentSelectedTextColor=_currentSelectedTextColor;
- (void)dealloc;
@property(nonatomic) struct CGRect defaultImageFrame; // @synthesize defaultImageFrame=_defaultImageFrame;
@property(nonatomic) __weak id <TNDREditMomentDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didExitGridView;
- (void)didPickColor:(id)arg1 animatingFromPoint:(struct CGPoint)arg2;
- (void)disableGestureRecognizers;
- (void)disableTextView;
- (void)doMomentShare;
- (void)drawButtonTapped:(id)arg1;
@property(retain, nonatomic) TNDRDrawOnViewGL *drawingView; // @synthesize drawingView=_drawingView;
@property(nonatomic) BOOL easterEgg; // @synthesize easterEgg=_easterEgg;
- (void)easterEgg:(id)arg1;
@property(nonatomic) int editMomentDefaultTextHeight; // @synthesize editMomentDefaultTextHeight=_editMomentDefaultTextHeight;
- (void)editTextButtonTapped:(id)arg1;
@property(nonatomic) int editingState; // @synthesize editingState=_editingState;
- (void)enableGestureRecognizers;
- (void)enableTextView;
- (void)endDrawingModeAndReturnToPreview;
- (void)filterButtonTapped:(id)arg1;
- (void)filterSelected:(id)arg1 filterUsed:(int)arg2;
@property(retain, nonatomic) TNDRFilterViewController *filterViewController; // @synthesize filterViewController=_filterViewController;
@property(retain, nonatomic) UIView *firstShareBackgroundView; // @synthesize firstShareBackgroundView=_firstShareBackgroundView;
- (void)firstShareButtonTapped:(id)arg1;
- (void)firstShareCancelTapped:(id)arg1;
@property(retain, nonatomic) UIView *firstShareContainer; // @synthesize firstShareContainer=_firstShareContainer;
@property(retain, nonatomic) UIView *footerDarken; // @synthesize footerDarken=_footerDarken;
- (void)forceUpdateLineHeightForTextView:(id)arg1;
- (id)generateCompositeImageToShare;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
@property(nonatomic) BOOL hasAnimatedFromTransition; // @synthesize hasAnimatedFromTransition=_hasAnimatedFromTransition;
- (BOOL)hasPhotoLibraryAccess;
@property(retain, nonatomic) UIView *headerDarken; // @synthesize headerDarken=_headerDarken;
@property(retain, nonatomic) TNDREditMomentsTextView *helperTextView; // @synthesize helperTextView=_helperTextView;
- (void)hideSupportingDrawButtons;
- (void)hideSupportingTextButtons;
- (void)hideTextView;
- (void)hideUIElementsForDrawing;
- (void)hideUIElementsForFilterGridMode;
- (void)hideUIElementsForFilterScrolling;
- (id)imageCompositingTextView:(id)arg1 ontoImage:(id)arg2;
@property(retain, nonatomic) UIImage *imageToEdit; // @synthesize imageToEdit=_imageToEdit;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView2; // @synthesize indicatorView2=_indicatorView2;
- (id)initWithPhoto:(id)arg1 frame:(struct CGRect)arg2;
@property(nonatomic) BOOL isAddingText; // @synthesize isAddingText=_isAddingText;
@property(nonatomic) BOOL isDismissing; // @synthesize isDismissing=_isDismissing;
@property(nonatomic, getter=isEditingText) BOOL editingText; // @synthesize editingText=_editingText;
@property(nonatomic, getter=isPickingTextColor) BOOL pickingTextColor; // @synthesize pickingTextColor=_pickingTextColor;
- (BOOL)isRectOutOfBottomTextBounds:(struct CGRect)arg1;
- (BOOL)isRectOutOfTopTextBounds:(struct CGRect)arg1;
@property(nonatomic) BOOL isSharing; // @synthesize isSharing=_isSharing;
- (void)keyboardDidHide:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
@property(nonatomic) BOOL keyboardShowing; // @synthesize keyboardShowing=_keyboardShowing;
@property(nonatomic) struct CGSize keyboardSize; // @synthesize keyboardSize=_keyboardSize;
- (void)keyboardWillChangeFrame:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)loadView;
@property(retain, nonatomic) UIView *matchViewSnapshot; // @synthesize matchViewSnapshot=_matchViewSnapshot;
- (struct CGSize)maxAllowedTextSize;
- (id)momentTextForCurrentMoment;
@property(nonatomic) BOOL openedEditWithButton; // @synthesize openedEditWithButton=_openedEditWithButton;
@property(retain, nonatomic) UIImage *originalImage; // @synthesize originalImage=_originalImage;
@property(retain, nonatomic) UIPanGestureRecognizer *panGestureRecognizer; // @synthesize panGestureRecognizer=_panGestureRecognizer;
- (void)panned:(id)arg1;
- (id)photoView;
- (struct CGPoint)pointToShoveSelectedColorButton:(struct CGPoint)arg1 forEditState:(int)arg2;
- (BOOL)prefersStatusBarHidden;
- (void)prepareForPresentationFromCameraMoments;
@property(nonatomic) struct CGAffineTransform previousTextFieldTransform; // @synthesize previousTextFieldTransform=_previousTextFieldTransform;
- (void)registerKeyboardNotifications;
- (void)returnToTextEditingModeAfterPickingColor;
- (void)saveButtonTapped:(id)arg1;
@property(nonatomic) BOOL selectedSmallText; // @synthesize selectedSmallText=_selectedSmallText;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(nonatomic) int textSize; // @synthesize textSize=_textSize;
@property(retain, nonatomic) TNDREditMomentsTextView *textView; // @synthesize textView=_textView;
- (void)setupButtonAnimationManager;
- (void)setupButtonContainerView;
- (void)setupColorPicker;
- (void)setupComposedDrawingPlaceholder;
- (void)setupCurrentlySelectedColor;
- (void)setupFilterViewCompletion:(CDUnknownBlockType)arg1;
- (void)setupMainImageView;
- (void)setupTextEntryField;
- (void)shareButtonTapped:(id)arg1;
- (void)shareMoment;
- (void)showColorPickerForEditState:(int)arg1;
- (void)showFirstShareAlert;
- (void)showMomentCompositeFailedUserAlert;
- (void)showSupportingDrawButtons;
- (void)showSupportingTextButtons;
- (void)showTextEditingOptionButtons;
- (void)showTextView;
- (void)showUIElementsForDrawing;
- (void)showUIElementsForEndFilterScrolling;
- (void)sizeTextViewFontForText:(id)arg1 forceUpdateLineHeight:(BOOL)arg2;
- (void)sizeTextViewForUpdatedText;
- (id)stringForButtonIconNamed:(id)arg1 isActive:(BOOL)arg2;
- (void)tapped:(id)arg1;
- (void)textAlignmentButtonTapped:(id)arg1;
- (void)textColorButtonTapped:(id)arg1;
- (void)textSizeButtonTapped:(id)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (BOOL)textViewShouldBeginEditing:(id)arg1;
- (void)toggleButton:(id)arg1 appearing:(BOOL)arg2 animated:(BOOL)arg3;
- (void)toggleEditButton:(id)arg1 active:(BOOL)arg2;
- (float)topMarginHeight;
- (struct CGAffineTransform)topTextViewTransform;
- (void)truncateTextForNewSize;
- (void)undoButtonLongPress:(id)arg1;
- (void)undoButtonTapped:(id)arg1;
- (void)updateButtonTintColor:(id)arg1 withColor:(id)arg2;
- (void)updateTextViewPositionForMovementConstraint;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (float)widthForTextView;

// Remaining properties
@property(readonly, nonatomic) id <UIViewControllerAnimatedTransitioning> animationController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

