//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDateFormatter;

@interface TNDRPassportStackViewModel : NSObject
{
    NSArray *_popularLocations;
    NSDateFormatter *_dateFormatter;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
- (id)init;
- (id)initWithPopularLocations:(id)arg1;
- (int)numberOfPopularLocations;
- (id)popularLocationViewModelForIndexPath:(id)arg1;
@property(retain, nonatomic) NSArray *popularLocations; // @synthesize popularLocations=_popularLocations;

@end

