//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFHTTPSessionManager.h"

@interface TNDRHTTPContentClient : AFHTTPSessionManager
{
}

+ (id)sharedHTTPClient;
- (void)clearAuthorizationHeader;
- (void)deletePhotoWithParams:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithBaseURL:(id)arg1;
- (id)operatingSystemVersion;
- (void)setAuthorizationHeaderWithToken:(id)arg1;
- (void)setup;
- (void)updateServerPhotoPositions:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

