//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexPath, TNDRPassportActiveUserCell, TNDRPassportPopularLocationCell;

@protocol TNDRPassportPopularLocationCellDelegate <NSObject>
- (void)configureCell:(TNDRPassportActiveUserCell *)arg1 atIndexPath:(NSIndexPath *)arg2 onCell:(TNDRPassportPopularLocationCell *)arg3;
- (int)numberOfActiveUsersForCell:(TNDRPassportPopularLocationCell *)arg1;
- (void)tappedGoToLocationOnCell:(TNDRPassportPopularLocationCell *)arg1;
@end

