//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "NSFetchedResultsControllerDelegate.h"
#import "TNDRMomentViewerViewControllerDelegate.h"
#import "TNDRMomentsRefreshProtocol.h"
#import "TNDRMyMomentViewerDelegate.h"
#import "TNDRMyMomentsActivityCellDelegate.h"
#import "TNDRURLNavigableProtocol.h"
#import "UIScrollViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UIViewControllerTransitioningDelegate.h"

@class NSArray, NSDateFormatter, NSFetchedResultsController, NSMutableArray, NSString, NSTimer, TNDRMomentViewerViewController, TNDRMyMomentViewerView, TNDRMyMomentsToMomentViewerAnimationController, UIImageView, UITableView;

@interface TNDRMyMomentsActivityViewController : UIViewController <NSFetchedResultsControllerDelegate, UITableViewDataSource, UITableViewDelegate, UIScrollViewDelegate, UIViewControllerTransitioningDelegate, TNDRMomentViewerViewControllerDelegate, TNDRMyMomentViewerDelegate, TNDRMyMomentsActivityCellDelegate, TNDRMomentsRefreshProtocol, TNDRURLNavigableProtocol>
{
    NSMutableArray *_fetchedObjectChanges;
    unsigned int _prevUnviewedCount;
    unsigned int _prevViewedCount;
    BOOL _hasLoadedMoments;
    NSArray *_tempUnviewedArray;
    NSArray *_tempViewedArray;
    id <TNDRMomentsActivityScrollDelegate> _delegate;
    UITableView *_tableView;
    NSArray *_allFetchedActivity;
    NSArray *_unviewedMomentsArray;
    NSArray *_viewedMomentsArray;
    NSFetchedResultsController *_fetchedResultsController;
    NSDateFormatter *_dateFormatter;
    NSArray *_itemsToMarkViewed;
    TNDRMyMomentViewerView *_momentViewer;
    NSTimer *_dataTimer;
    UIImageView *_emptyGridView;
    TNDRMyMomentsToMomentViewerAnimationController *_toMomentViewerAnimationController;
    TNDRMomentViewerViewController *_momentViewerViewController;
}

+ (id)viewControllerNavigationKey;
- (void).cxx_destruct;
- (void)adjustTableViewContentInsets;
@property(retain, nonatomic) NSArray *allFetchedActivity; // @synthesize allFetchedActivity=_allFetchedActivity;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)configureCell:(id)arg1 forIndexPath:(id)arg2;
- (void)controllerDidChangeContent:(id)arg1;
@property(retain, nonatomic) NSTimer *dataTimer; // @synthesize dataTimer=_dataTimer;
@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
@property(nonatomic) __weak id <TNDRMomentsActivityScrollDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didCloseMomentViewer;
- (void)didReceiveMemoryWarning;
- (void)didRequestToDeleteMoment:(id)arg1;
- (void)didRequestToOpenChatFor:(id)arg1 withAvatarImage:(id)arg2;
- (void)didRequestToPresentMomentViewerFor:(id)arg1 cell:(id)arg2;
@property(retain, nonatomic) UIImageView *emptyGridView; // @synthesize emptyGridView=_emptyGridView;
@property(retain, nonatomic) NSFetchedResultsController *fetchedResultsController; // @synthesize fetchedResultsController=_fetchedResultsController;
- (void)handleAppDidEnterBackground:(id)arg1;
- (void)handleUserDidLogin:(id)arg1;
- (void)handleUserDidLogout:(id)arg1;
- (id)indexPathsOfCellsToRemoveForMoment:(id)arg1;
- (id)init;
@property(retain, nonatomic) NSArray *itemsToMarkViewed; // @synthesize itemsToMarkViewed=_itemsToMarkViewed;
- (id)likeForIndexPath:(id)arg1;
- (void)markAllViewedLikesCompletion:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) TNDRMyMomentViewerView *momentViewer; // @synthesize momentViewer=_momentViewer;
@property(retain, nonatomic) TNDRMomentViewerViewController *momentViewerViewController; // @synthesize momentViewerViewController=_momentViewerViewController;
- (float)normalizedOffsetY;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)parseLikesForViewedAndUnviewed:(CDUnknownBlockType)arg1;
- (void)presentMomentViewerForMoment:(id)arg1;
- (void)refresh;
- (void)registerNotifications;
- (void)removeMomentLikeCellsFromTable:(id)arg1;
- (void)resetData;
- (id)retrieveIDFromServerLike:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (BOOL)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (id)sectionHeaderLabelForRect:(struct CGRect)arg1;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) TNDRMyMomentsToMomentViewerAnimationController *toMomentViewerAnimationController; // @synthesize toMomentViewerAnimationController=_toMomentViewerAnimationController;
@property(retain, nonatomic) NSArray *unviewedMomentsArray; // @synthesize unviewedMomentsArray=_unviewedMomentsArray;
@property(retain, nonatomic) NSArray *viewedMomentsArray; // @synthesize viewedMomentsArray=_viewedMomentsArray;
- (void)setup;
- (void)setupCoreDataLikesSource;
- (void)setupTableView;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (void)transitionTo:(id)arg1 optionsDict:(id)arg2 animated:(BOOL)arg3 completion:(CDUnknownBlockType)arg4;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

