//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TNDREditMomentDelegate.h"
#import "TNDRMomentsCameraOverlayDelegate.h"
#import "TNDRURLNavigableProtocol.h"
#import "UIAlertViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"

@class ALAssetsLibrary, AVCaptureConnection, AVCaptureDevice, AVCaptureDeviceInput, AVCaptureSession, AVCaptureStillImageOutput, AVCaptureVideoPreviewLayer, FBKVOController, NSString, TNDRImagePickerController, TNDRMomentsCameraOverlayView, TNDRMomentsCameraToEditTransitioningDelegate<UIViewControllerTransitioningDelegate>, UIAlertView, UIButton, UIImageView, UIToolbar, UIView;

@interface TNDRMomentsCameraViewController : UIViewController <TNDRMomentsCameraOverlayDelegate, TNDREditMomentDelegate, UINavigationControllerDelegate, UIImagePickerControllerDelegate, UIGestureRecognizerDelegate, UIAlertViewDelegate, TNDRURLNavigableProtocol>
{
    float _screenHeight;
    float _cameraHeightDiff;
    float _scaleUpFactor;
    float _effectiveScale;
    float _beginGestureScale;
    float _maxZoomValue;
    BOOL _viewWillAppearWorkFinished;
    BOOL _supportsFrontCamera;
    BOOL _requestAdjustExposure;
    BOOL _sharingMoment;
    BOOL _lockExposureAfterExposing;
    BOOL _userIsChoosingPhotoFromCameraRoll;
    int _cameraFlashState;
    TNDRMomentsCameraOverlayView *_momentsOverlayView;
    UIView *_matchViewSnapshot;
    UIView *_flashOverlay;
    UIImageView *_capturedPhotoView;
    UIButton *_placeholderShareButton;
    AVCaptureSession *_avSession;
    AVCaptureVideoPreviewLayer *_avPreviewLayer;
    AVCaptureDevice *_avCurrentDevice;
    AVCaptureDeviceInput *_avDeviceInput;
    AVCaptureStillImageOutput *_avStillImageOutput;
    AVCaptureConnection *_avVideoConnection;
    TNDRMomentsCameraToEditTransitioningDelegate<UIViewControllerTransitioningDelegate> *_cameraToEditTransitioningDelegate;
    FBKVOController *_kvoController;
    TNDRImagePickerController *_cameraRollPickerController;
    UIImageView *_cameraRollPreviewView;
    UIToolbar *_cameraRollPreviewToolbar;
    ALAssetsLibrary *_assetsLibrary;
    UIAlertView *_cameraAccessWasDenied;
    UIAlertView *_cameraAccessIsRestricted;
}

+ (id)viewControllerNavigationKey;
- (void).cxx_destruct;
- (void)addCaptureOutputToDeviceInput;
- (void)addDeviceToSession:(id)arg1;
- (void)addPreviewLayerToViewLayer;
- (BOOL)adjustExposureForAVCaptureDeviceOnViewCoordinate:(struct CGPoint)arg1 lock:(BOOL)arg2;
- (BOOL)adjustFocusAndExposureForAVCaptureDeviceOnViewCoordinate:(struct CGPoint)arg1 lock:(BOOL)arg2;
- (void)adjustForContinuousAutoWhiteBalance;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
@property(retain, nonatomic) ALAssetsLibrary *assetsLibrary; // @synthesize assetsLibrary=_assetsLibrary;
- (void)avCaptureError:(id)arg1;
@property(retain, nonatomic) AVCaptureDevice *avCurrentDevice; // @synthesize avCurrentDevice=_avCurrentDevice;
@property(retain, nonatomic) AVCaptureDeviceInput *avDeviceInput; // @synthesize avDeviceInput=_avDeviceInput;
@property(retain, nonatomic) AVCaptureVideoPreviewLayer *avPreviewLayer; // @synthesize avPreviewLayer=_avPreviewLayer;
@property(retain, nonatomic) AVCaptureSession *avSession; // @synthesize avSession=_avSession;
@property(retain, nonatomic) AVCaptureStillImageOutput *avStillImageOutput; // @synthesize avStillImageOutput=_avStillImageOutput;
@property(retain, nonatomic) AVCaptureConnection *avVideoConnection; // @synthesize avVideoConnection=_avVideoConnection;
- (id)backFacingCameraIfAvailable;
@property(retain, nonatomic) UIAlertView *cameraAccessIsRestricted; // @synthesize cameraAccessIsRestricted=_cameraAccessIsRestricted;
@property(retain, nonatomic) UIAlertView *cameraAccessWasDenied; // @synthesize cameraAccessWasDenied=_cameraAccessWasDenied;
@property(nonatomic) int cameraFlashState; // @synthesize cameraFlashState=_cameraFlashState;
@property(retain, nonatomic) TNDRImagePickerController *cameraRollPickerController; // @synthesize cameraRollPickerController=_cameraRollPickerController;
@property(retain, nonatomic) UIToolbar *cameraRollPreviewToolbar; // @synthesize cameraRollPreviewToolbar=_cameraRollPreviewToolbar;
@property(retain, nonatomic) UIImageView *cameraRollPreviewView; // @synthesize cameraRollPreviewView=_cameraRollPreviewView;
@property(retain, nonatomic) TNDRMomentsCameraToEditTransitioningDelegate<UIViewControllerTransitioningDelegate> *cameraToEditTransitioningDelegate; // @synthesize cameraToEditTransitioningDelegate=_cameraToEditTransitioningDelegate;
- (id)captureDeviceForPosition:(int)arg1;
- (void)captureStillImageWithCamera:(int)arg1;
@property(retain, nonatomic) UIImageView *capturedPhotoView; // @synthesize capturedPhotoView=_capturedPhotoView;
- (struct CGAffineTransform)combinedTransformForScalingPhoto;
- (struct CGPoint)convertToPointOfInterestFromViewCoordinates:(struct CGPoint)arg1;
- (void)dealloc;
- (void)didChangeZoomSlider:(float)arg1;
- (void)didChooseCameraRollImageTransitionToEdit;
- (BOOL)didLongPressToLockFocusAndExposurePointAt:(struct CGPoint)arg1;
- (void)didReceiveMemoryWarning;
- (void)didSelectToCloseCamera:(BOOL)arg1;
- (void)didSelectToOpenCameraRoll;
- (void)didSelectToTakePhotoWithCamera:(int)arg1;
- (void)didTapEditMomentCloseButton;
- (void)didTapShareMomentButton;
- (BOOL)didTapToAdjustFocusAndExposureAtPoint:(struct CGPoint)arg1 lock:(BOOL)arg2;
- (BOOL)didTapToFocusPointAt:(struct CGPoint)arg1;
- (void)didToggleCameraDevice;
- (void)didToggleCameraFlash:(int)arg1;
- (void)finishViewWillAppearWork;
@property(retain, nonatomic) UIView *flashOverlay; // @synthesize flashOverlay=_flashOverlay;
- (BOOL)focusAVCaptureDeviceOnViewCoordinate:(struct CGPoint)arg1 lock:(BOOL)arg2;
- (id)frontFacingCameraIfAvailable;
- (void)handleAppForegrounded:(id)arg1;
- (void)handlePinchGesture:(id)arg1;
- (void)handlePreviewCancelTapped:(id)arg1;
- (void)handlePreviewChooseTapped:(id)arg1;
- (void)hideStatusBar;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (id)init;
@property(retain, nonatomic) FBKVOController *kvoController; // @synthesize kvoController=_kvoController;
- (void)lockCurrentExposure;
@property(nonatomic) BOOL lockExposureAfterExposing; // @synthesize lockExposureAfterExposing=_lockExposureAfterExposing;
@property(retain, nonatomic) UIView *matchViewSnapshot; // @synthesize matchViewSnapshot=_matchViewSnapshot;
@property(retain, nonatomic) TNDRMomentsCameraOverlayView *momentsOverlayView; // @synthesize momentsOverlayView=_momentsOverlayView;
- (void)performTransitionToEditMomentsViewControllerWithImage:(id)arg1 andCameraState:(int)arg2 completion:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) UIButton *placeholderShareButton; // @synthesize placeholderShareButton=_placeholderShareButton;
- (int)preferredStatusBarStyle;
- (BOOL)prefersStatusBarHidden;
- (BOOL)redirectionToSettingsAppIsSupported;
- (void)registerNotifications;
- (void)removeCaptureOutputFromDeviceInput;
- (void)removePreviewLayer;
@property(nonatomic) BOOL requestAdjustExposure; // @synthesize requestAdjustExposure=_requestAdjustExposure;
- (void)retrieveMetadataForAssetURL:(id)arg1;
@property(nonatomic) BOOL sharingMoment; // @synthesize sharingMoment=_sharingMoment;
@property(nonatomic) BOOL supportsFrontCamera; // @synthesize supportsFrontCamera=_supportsFrontCamera;
@property(nonatomic) BOOL userIsChoosingPhotoFromCameraRoll; // @synthesize userIsChoosingPhotoFromCameraRoll=_userIsChoosingPhotoFromCameraRoll;
- (void)setup;
- (void)setupAVFoundation;
- (void)setupAVFoundationObserver;
- (void)setupAlertViews;
- (void)setupCameraControlsOverlay;
- (void)setupCameraFlashOverlay;
- (void)setupCaptureConnection;
- (void)setupLastUsedCaptureDevice;
- (void)setupPlaceholderShareButtonForTransition;
- (void)setupPreviewLayer;
- (void)setupStillImageCaptureOutput;
- (void)showCameraRollPreviewModeWithImage:(id)arg1;
- (void)switchCameraDevice;
- (void)trackImageProperties:(id)arg1;
- (void)transitionTo:(id)arg1 optionsDict:(id)arg2 animated:(BOOL)arg3 completion:(CDUnknownBlockType)arg4;
- (void)updateNavigationBarForChoosePhoto:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)zoomVideoToScale:(float)arg1;

// Remaining properties
@property(readonly, nonatomic) id <UIViewControllerAnimatedTransitioning> animationController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

