//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

@class NSMutableArray, UIButton, UIColor, UIImageView, UILabel, UIView;

@interface TNDRActionSheet : UIWindow
{
    UIWindow *_mainWindow;
    BOOL _roundedButtons;
    BOOL _statusBarHidden;
    BOOL _scaleBackground;
    id _actionSheetDelegate;
    UILabel *_title;
    UIView *_sheetView;
    float _currentYOffset;
    UIButton *_previousButton;
    UIImageView *_normalBackgroundView;
    NSMutableArray *_containerViews;
    UIWindow *_window;
    UIView *_windowBackground;
    UIColor *_windowBackgroundColor;
}

- (void).cxx_destruct;
- (void)_showWithAnimation:(BOOL)arg1;
@property(nonatomic) __weak id actionSheetDelegate; // @synthesize actionSheetDelegate=_actionSheetDelegate;
- (void)addButtonWithTitle:(id)arg1 buttonId:(int)arg2 font:(id)arg3 textColor:(id)arg4 textHighlightColor:(id)arg5 textShadowColor:(id)arg6 backgroundColor:(id)arg7 backgroundHightlightColor:(id)arg8 buttonImage:(id)arg9 increasedSpacing:(BOOL)arg10 group:(int)arg11;
- (void)addTitle:(id)arg1 buttonId:(int)arg2 font:(id)arg3 textColor:(id)arg4 backgroundColor:(id)arg5 group:(int)arg6;
- (void)animateGroupIn:(int)arg1;
- (void)animateInBackground;
- (void)animateOutBackground;
@property(retain, nonatomic) NSMutableArray *containerViews; // @synthesize containerViews=_containerViews;
@property(nonatomic) float currentYOffset; // @synthesize currentYOffset=_currentYOffset;
- (void)dismissWithAnimation:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithTitle:(id)arg1 delegate:(id)arg2 frame:(struct CGRect)arg3 blurBackground:(BOOL)arg4 scaleBackground:(BOOL)arg5 backgroundColor:(id)arg6;
- (id)nextResponder;
@property(retain, nonatomic) UIImageView *normalBackgroundView; // @synthesize normalBackgroundView=_normalBackgroundView;
@property(retain, nonatomic) UIButton *previousButton; // @synthesize previousButton=_previousButton;
- (void)processButtonAction:(id)arg1;
- (void)roundButtons;
- (void)roundCorner:(id)arg1 top:(BOOL)arg2 bottom:(BOOL)arg3;
@property(nonatomic) BOOL roundedButtons; // @synthesize roundedButtons=_roundedButtons;
@property(nonatomic) BOOL scaleBackground; // @synthesize scaleBackground=_scaleBackground;
@property(retain, nonatomic) UIView *sheetView; // @synthesize sheetView=_sheetView;
@property(nonatomic) BOOL statusBarHidden; // @synthesize statusBarHidden=_statusBarHidden;
@property(retain, nonatomic) UILabel *title; // @synthesize title=_title;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
@property(retain, nonatomic) UIView *windowBackground; // @synthesize windowBackground=_windowBackground;
@property(retain, nonatomic) UIColor *windowBackgroundColor; // @synthesize windowBackgroundColor=_windowBackgroundColor;
- (void)showAnimated;
- (void)showOverWindow:(id)arg1 animated:(BOOL)arg2;
- (void)showWithAnimation:(BOOL)arg1;

@end

