//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TNDRLocation;

@protocol TNDRPassportLocationsListViewControllerDelegate <NSObject>
- (void)didSelectToCloseLocationListWithoutTraveling;
- (void)didSelectToNavigateToPassportPaywall:(unsigned int)arg1;
- (void)didSelectToOpenMapSearchController;
- (void)didSelectTravelToLocation:(TNDRLocation *)arg1;

@optional
- (void)selectedNewLocation:(TNDRLocation *)arg1;
@end

