//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerAnimatedTransitioning.h"

@class NSString, TNDRMyProfileEditViewController, TNDRProfilePreviewViewController, UIView, UIViewController;

@interface TNDRProfilePreviewTransitioning : NSObject <UIViewControllerAnimatedTransitioning>
{
    struct CGRect _previewPhotoFrame;
    struct CGRect _previewInfoFrame;
    int _previewPhotoNumber;
    float _scale;
    TNDRProfilePreviewViewController *_previewVC;
    TNDRMyProfileEditViewController *_editorVC;
    struct CGRect _editorInfoContainerFrame;
    struct CGRect _editorCellFrame;
    struct CGRect _editorFrame;
    UIView *_editorSnapshot;
    BOOL _reverse;
    UIViewController *_source;
}

- (void).cxx_destruct;
- (void)animateTransition:(id)arg1;
@property(nonatomic) BOOL reverse; // @synthesize reverse=_reverse;
@property(retain, nonatomic) UIViewController *source; // @synthesize source=_source;
- (double)transitionDuration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

