//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class TNDRPassportLocationActivePeopleView, TNDRPassportLocationStatsView, UIButton;

@interface TNDRPassportLocationInfoView : UIView
{
    TNDRPassportLocationStatsView *_statView;
    TNDRPassportLocationActivePeopleView *_activePeopleView;
    UIButton *_goToLocationButton;
}

- (void).cxx_destruct;
- (void)_setupAutoLayout;
- (void)_setupSubviews;
@property(retain, nonatomic) TNDRPassportLocationActivePeopleView *activePeopleView; // @synthesize activePeopleView=_activePeopleView;
@property(retain, nonatomic) UIButton *goToLocationButton; // @synthesize goToLocationButton=_goToLocationButton;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) TNDRPassportLocationStatsView *statView; // @synthesize statView=_statView;

@end

