//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_TNDRMomentPhoto.h"

@interface TNDRMomentPhoto : _TNDRMomentPhoto
{
}

- (id)imageURLForSize:(int)arg1 useLargerImageIfAvailable:(BOOL)arg2;
- (id)largestCachedImageURL:(int)arg1;
- (void)prepareForDeletion;
- (id)priorityURLArrayForImageSize:(int)arg1;
- (id)retrieveLargestCachedImage:(id)arg1;
- (id)urlForSize:(int)arg1;

@end

