//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TNDRActionSheetDelegate.h"
#import "TNDRNotificationWindowDelegate.h"
#import "TNDRPhotoPageControllerDelegate.h"
#import "TNDRProfileEditorChangedData.h"
#import "TNDRURLNavigableProtocol.h"
#import "UIScrollViewDelegate.h"
#import "UIViewControllerTransitioningDelegate.h"

@class NSArray, NSManagedObjectContext, NSString, StyledPageControl, TNDRActionSheet, TNDRChatViewController, TNDRMatchToChatAnimationController, TNDRMyProfileEditViewController, TNDRPhotoPageController, TNDRProfileHorizontalViewController, TNDRUser, UIAlertView, UIButton, UILabel, UINavigationBar, UIScrollView, UITextView, UIView;

@interface TNDRProfilePreviewViewController : UIViewController <TNDRPhotoPageControllerDelegate, TNDRActionSheetDelegate, TNDRNotificationWindowDelegate, UIViewControllerTransitioningDelegate, TNDRProfileEditorChangedData, UIScrollViewDelegate, TNDRURLNavigableProtocol>
{
    UIView *_backgroundView;
    NSArray *_photos;
    int _firstImageToShow;
    UILabel *_nameLabel;
    NSString *_firstName;
    UILabel *_distanceAway;
    UILabel *_lastActive;
    UILabel *_bioTitleLabel;
    UITextView *_bioView;
    NSString *_bio;
    UILabel *_travelingInformation;
    UILabel *_contactsOrFriendsLabel;
    int _numberOfFriends;
    UILabel *_interestsLabel;
    int _numberOfInterests;
    BOOL _editingProfile;
    BOOL _needsToUpdateLayoutsForInfoUpdate;
    BOOL _viewHasAppeared;
    BOOL _isDismissing;
    BOOL _isIOSVersion8;
    TNDRActionSheet *_actionSheet;
    id <UIViewControllerTransitioningDelegate> _profileEditorTransitioningDelegate;
    TNDRMyProfileEditViewController *_profileEditor;
    TNDRProfileHorizontalViewController *_friendsController;
    TNDRProfileHorizontalViewController *_interestsController;
    UIButton *_followButton;
    UIButton *_hideButton;
    UIAlertView *_followAlertView;
    UIAlertView *_hideAlertView;
    TNDRMatchToChatAnimationController *_matchToChatAnimationController;
    TNDRChatViewController *_chatViewController;
    BOOL _currentUserProfile;
    BOOL _presentedFromChat;
    BOOL _presentingMatch;
    BOOL _likeOnDismiss;
    BOOL _passOnDismiss;
    id <TNDR2ProfilePreviewDelegate> _delegate;
    TNDRUser *_user;
    UINavigationBar *_navigationBar;
    UIView *_infoView;
    TNDRPhotoPageController *_photoPageController;
    StyledPageControl *_photoPageControl;
    UIScrollView *_mainScrollView;
    UIView *_navigationBarSnapshot;
    NSManagedObjectContext *_context;
}

+ (id)viewControllerNavigationKey;
- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 triggeredButtonWithId:(int)arg2;
- (void)addBio;
- (void)addContacts;
- (void)addInterests;
- (void)addNameAndLocation;
- (void)addNavigationBarToView;
- (void)addTravelingInfo;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)animateForDismissal;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
- (void)blockButtonTapped;
@property(retain, nonatomic) NSManagedObjectContext *context; // @synthesize context=_context;
- (id)coreDataCachedLargePhotoDataForMe:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <TNDR2ProfilePreviewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didChangeBio:(id)arg1;
- (void)didChangePhotoData:(id)arg1;
- (void)didChangePhotoIndex:(id)arg1;
- (void)didFinishServerPhotoDataUpdate;
- (id)distanceString:(float)arg1;
- (void)doneButtonTapped:(id)arg1;
- (void)editButtonTapped:(id)arg1;
- (void)followMatch;
- (void)handleFollowButtonTapped;
- (void)handleHideButtonTapped;
- (void)handleRequestToShowStatusBar:(id)arg1;
- (float)heightForText:(id)arg1 fontSize:(unsigned int)arg2 attributes:(id)arg3;
- (void)hideMomentsButtonTapped;
@property(retain, nonatomic) UIView *infoView; // @synthesize infoView=_infoView;
- (id)init;
- (id)interactionControllerForDismissal:(id)arg1;
@property(nonatomic, getter=isCurrentUserProfile) BOOL currentUserProfile; // @synthesize currentUserProfile=_currentUserProfile;
@property(nonatomic, getter=isPresentedFromChat) BOOL presentedFromChat; // @synthesize presentedFromChat=_presentedFromChat;
@property(nonatomic, getter=isPresentingMatch) BOOL presentingMatch; // @synthesize presentingMatch=_presentingMatch;
- (id)largePhotoDataForMe;
- (id)lastActivityString:(id)arg1;
- (void)layoutViews;
- (void)likeButtonTapped:(id)arg1;
@property(nonatomic) BOOL likeOnDismiss; // @synthesize likeOnDismiss=_likeOnDismiss;
@property(retain, nonatomic) UIScrollView *mainScrollView; // @synthesize mainScrollView=_mainScrollView;
- (void)messageButtonTapped;
- (void)moreButtonTapped:(id)arg1;
@property(retain, nonatomic) UINavigationBar *navigationBar; // @synthesize navigationBar=_navigationBar;
@property(retain, nonatomic) UIView *navigationBarSnapshot; // @synthesize navigationBarSnapshot=_navigationBarSnapshot;
- (BOOL)needToWrap;
- (struct CGPoint)offsetForDismissal;
- (void)passButtonTapped:(id)arg1;
@property(nonatomic) BOOL passOnDismiss; // @synthesize passOnDismiss=_passOnDismiss;
- (id)photoDataForUser;
@property(retain, nonatomic) StyledPageControl *photoPageControl; // @synthesize photoPageControl=_photoPageControl;
@property(retain, nonatomic) TNDRPhotoPageController *photoPageController; // @synthesize photoPageController=_photoPageController;
- (int)preferredStatusBarStyle;
- (void)prematchEllipsisTapped:(id)arg1;
- (void)prepareToShowGameProfileForUser:(id)arg1 delegate:(id)arg2;
- (void)prepareToShowMatchProfileForUser:(id)arg1 delegate:(id)arg2;
- (void)prepareToShowProfileForCurrentUser;
- (void)presentChatForMatch;
- (void)registerNotifications;
- (void)reportButtonTapped;
- (void)scrollViewDidScroll:(id)arg1;
@property(retain, nonatomic) TNDRUser *user; // @synthesize user=_user;
- (void)setupActionSheet;
- (void)setupFollowHideButtons;
- (void)setupInfoView;
- (void)setupNavigationBar;
- (void)setupNavigationBarForCurrentUserProfile;
- (void)setupNavigationBarForGameProfile;
- (void)setupNavigationBarForMatchProfile;
- (void)setupNavigationBarForModals;
- (void)setupPhotoPageController;
- (void)setupPreMatchEllipsisButton;
- (void)setupScrollView;
- (void)showNavigationBarItems:(BOOL)arg1;
- (struct CGSize)sizeForText:(id)arg1 fontSize:(unsigned int)arg2;
- (void)transitionTo:(id)arg1 optionsDict:(id)arg2 animated:(BOOL)arg3 completion:(CDUnknownBlockType)arg4;
- (void)unregisterNotifications;
- (void)updateAndNotifyDelegateForDismissal;
- (void)updateInfoView;
- (void)updateProfilePreviewWithMockCurrentUserUsingExistingInfo;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)wantsToFollow;
- (void)wantsToHide;
- (float)widthForText:(id)arg1 fontSize:(unsigned int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

