//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class UILabel;

@interface TNDRMyMomentsNotificationBubble : UIImageView
{
    int _numMoments;
    UILabel *_numberLabel;
}

- (void).cxx_destruct;
- (id)init;
- (struct CGSize)minSize;
@property(nonatomic) int numMoments; // @synthesize numMoments=_numMoments;
@property(retain, nonatomic) UILabel *numberLabel; // @synthesize numberLabel=_numberLabel;
- (void)setup;
- (void)setupBackground;
- (void)setupLabel;

@end

