//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSString, TNDRCard, TNDRCardStackLayoutItem, UIPanGestureRecognizer;

@interface TNDRCardStackView : UIView <UIGestureRecognizerDelegate>
{
    BOOL _updating;
    NSMutableArray *_cards;
    UIView *_customPositiveStampView;
    UIView *_customNegativeStampView;
    id <TNDRCardStackViewDataSource> _dataSource;
    id <TNDRCardStackViewDelegate> _delegate;
    TNDRCardStackLayoutItem *_layoutItem;
    NSMutableArray *_reusableCards;
    NSMutableDictionary *_registedCardClasses;
    UIPanGestureRecognizer *_panGestureRecognizer;
    TNDRCard *_currentCell;
    struct CGPoint _panStartPoint;
    struct CGPoint _startLocationOnCard;
}

- (void).cxx_destruct;
- (void)addParallaxToCard:(id)arg1 atIndex:(int)arg2;
- (void)adjustCardAtIndex:(int)arg1 horizontalTranslation:(float)arg2;
- (void)adjustCardsForPanningPosition:(float)arg1;
- (void)animateTopCardOffscreenWithDirection:(int)arg1 velocity:(struct CGPoint)arg2;
- (void)applyLayoutAttributesToAllCards;
- (void)applyLayoutAttributesToCard:(id)arg1 atIndex:(int)arg2;
- (void)beginUpdates;
- (id)cardForIndex:(int)arg1;
- (id)cardForReuseIdentifier:(id)arg1;
@property(retain, nonatomic) NSMutableArray *cards; // @synthesize cards=_cards;
- (Class)classForReuseIdentifier:(id)arg1;
- (void)configureCardForIndex:(int)arg1;
- (void)configureDefaultFrameForCard:(id)arg1;
- (id)createCardForReuseIdentifier:(id)arg1;
@property(retain, nonatomic) TNDRCard *currentCell; // @synthesize currentCell=_currentCell;
@property(retain, nonatomic) UIView *customNegativeStampView; // @synthesize customNegativeStampView=_customNegativeStampView;
@property(retain, nonatomic) UIView *customPositiveStampView; // @synthesize customPositiveStampView=_customPositiveStampView;
@property(nonatomic) __weak id <TNDRCardStackViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id <TNDRCardStackViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deleteCardAtIndexPath:(id)arg1;
- (void)deleteCardsAtIndexPaths:(id)arg1;
- (void)deleteOutOfRangeCards;
- (id)dequeReusableCardWithReuseIdentifier:(id)arg1 atIndex:(int)arg2;
- (void)endUpdates;
- (void)handleContinuingPanGestureWithRecognizer:(id)arg1;
- (void)handleEndingPanGestureWithRecognizer:(id)arg1;
- (void)handlePanGesture:(id)arg1;
- (void)handleStartingPanGestureWithRecognizer:(id)arg1;
- (int)indexForCard:(id)arg1;
- (id)initWithCardStackLayoutItem:(id)arg1;
- (void)insertCardAtIndexPath:(id)arg1;
- (void)insertCardsAtIndexPaths:(id)arg1;
- (int)insertionIndexForCard:(id)arg1 atIndex:(int)arg2;
@property(retain, nonatomic) TNDRCardStackLayoutItem *layoutItem; // @synthesize layoutItem=_layoutItem;
- (void)layoutSubviews;
@property(retain, nonatomic) UIPanGestureRecognizer *panGestureRecognizer; // @synthesize panGestureRecognizer=_panGestureRecognizer;
@property(nonatomic) struct CGPoint panStartPoint; // @synthesize panStartPoint=_panStartPoint;
- (BOOL)pannedEnoughForActionWithGestureRecognizer:(id)arg1;
- (void)putStampsOnTopCard;
@property(retain, nonatomic) NSMutableDictionary *registedCardClasses; // @synthesize registedCardClasses=_registedCardClasses;
- (void)registerClass:(Class)arg1 forCellWithReuseIdentifier:(id)arg2;
- (void)reloadData;
- (void)restoreViewToCenter:(id)arg1;
@property(retain, nonatomic) NSMutableArray *reusableCards; // @synthesize reusableCards=_reusableCards;
- (id)safeGetCardFromDataSourceForIndex:(int)arg1;
@property(nonatomic) struct CGPoint startLocationOnCard; // @synthesize startLocationOnCard=_startLocationOnCard;
@property(nonatomic) BOOL updating; // @synthesize updating=_updating;
- (void)setupGestureRecognizers;
- (void)tryAddCardToStack:(id)arg1 atIndex:(int)arg2;
- (id)tryGetReusableCardForIdentifier:(id)arg1;
- (void)updateCardsOnStack;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

