//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

@class UIImageView, UIView;

@interface TNDRShareMomentWindow : UIWindow
{
    UIImageView *_backgroundImageView;
    UIImageView *_compositedImageToShareView;
    UIView *_cameraButtonCopy;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(retain, nonatomic) UIView *cameraButtonCopy; // @synthesize cameraButtonCopy=_cameraButtonCopy;
@property(retain, nonatomic) UIImageView *compositedImageToShareView; // @synthesize compositedImageToShareView=_compositedImageToShareView;

@end

