//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFHTTPRequestOperationManager.h"

@class NSOperation;

@interface TNDRHTTPRequestClient : AFHTTPRequestOperationManager
{
    NSOperation *_lastMessageOperation;
}

+ (id)sharedDebugHTTPClient;
+ (id)sharedHTTPClient;
- (void).cxx_destruct;
- (id)POST:(id)arg1 parameters:(id)arg2 timeoutInterval:(double)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)clearAuthorizationHeader;
- (BOOL)hasAuthenticationToken;
- (id)initWithBaseURL:(id)arg1;
@property(nonatomic) __weak NSOperation *lastMessageOperation; // @synthesize lastMessageOperation=_lastMessageOperation;
- (id)performRequestWithPath:(id)arg1 method:(id)arg2 parameters:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (id)sendMessage:(id)arg1 toMatch:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)sendPhotoMessage:(id)arg1 toMatch:(id)arg2 withMessageID:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)setAuthorizationHeaderWithToken:(id)arg1;
- (void)setup;

@end

