//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MSCMoreOptionTableViewCellDelegate.h"
#import "NSFetchedResultsControllerDelegate.h"
#import "TNDR2ProfilePreviewDelegate.h"
#import "TNDRChatViewControllerDelegate.h"
#import "TNDRMomentStackViewControllerDelegate.h"
#import "TNDRNoMatchesViewDelegate.h"
#import "TNDRURLNavigableProtocol.h"
#import "UIActionSheetDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UISearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"
#import "UIViewControllerTransitioningDelegate.h"

@class NSFetchedResultsController, NSIndexPath, NSMutableArray, NSPredicate, NSString, NSTimer, TNDRChatToProfileTransitioningDelegate, TNDRList, TNDRMatch, TNDRMatchCell, TNDRMatchesToMomentsAnimationController, TNDRMiniStackContainerView, TNDRMiniStackView, TNDRMomentStackViewController, TNDRNoMatchesView, TNDRProfilePreviewViewController, TNDRPullToRefreshView, UIAlertView, UIImage, UIImageView, UISearchBar, UITableView, UITapGestureRecognizer, UIToolbar, UIView;

@interface TNDRMatchesViewController : UIViewController <NSFetchedResultsControllerDelegate, UIActionSheetDelegate, UIGestureRecognizerDelegate, MSCMoreOptionTableViewCellDelegate, TNDR2ProfilePreviewDelegate, UIAlertViewDelegate, UITextFieldDelegate, TNDRNoMatchesViewDelegate, UIViewControllerTransitioningDelegate, TNDRMomentStackViewControllerDelegate, UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate, TNDRChatViewControllerDelegate, TNDRURLNavigableProtocol>
{
    UISearchBar *_searchBar;
    UIView *_searchOverlayView;
    UITapGestureRecognizer *_overlayTapGR;
    TNDRList *_currentlyViewedList;
    float _topOffset;
    UIImage *_imageForNewMatchesOrMessages;
    UIImage *_imageForNoNewMatchesOrMessages;
    UIImageView *_dotView;
    UIView *_separator;
    struct CGPoint _savedScrollOffset;
    float _lastOffsetY;
    float _defaultSearchContainerHeight;
    BOOL _inSearchMode;
    BOOL _hasMatches;
    BOOL _miniStackVisible;
    BOOL _returningFromChat;
    BOOL _hasFinishedOneUpdateCallForThisSession;
    BOOL _hasAuthed;
    BOOL _isCurrentlyVisible;
    BOOL _presentingMomentStack;
    UITableView *_tableView;
    id <TNDRMatchesSearchDelegate> _delegate;
    TNDRMiniStackView *_miniStackView;
    NSMutableArray *_matches;
    NSFetchedResultsController *_fetchedResultsController;
    TNDRNoMatchesView *_noMatchesView;
    UIView *_matchesUpdatingView;
    UIView *_searchBarContainer;
    UIView *_searchBarBackground;
    UIToolbar *_toolbar;
    NSMutableArray *_selectedMatches;
    UIAlertView *_followAlertView;
    NSIndexPath *_indexPathToFollow;
    UIImage *_userImageToPresentFromSearch;
    TNDRMatch *_matchToPresentFromSearch;
    TNDRProfilePreviewViewController *_profilePreviewForRequest;
    TNDRChatToProfileTransitioningDelegate *_profileTransitioningDelegate;
    NSPredicate *_sharedMomentsPredicate;
    TNDRMiniStackContainerView *_headerViewContainer;
    UITapGestureRecognizer *_miniMomentStackTapGestureRecognizer;
    NSFetchedResultsController *_momentsFetchedResultsController;
    TNDRMatchesToMomentsAnimationController *_matchesToMomentsAnimationController;
    TNDRMomentStackViewController *_momentStackViewController;
    TNDRMatchCell *_footerCell;
    UIView *_footerContainer;
    TNDRPullToRefreshView *_pullToRefreshView;
    UIView *_tableFooterWhiteView;
    NSTimer *_miniMomentStackUpdateTimer;
    NSIndexPath *_selectedIndexPath;
    struct CGRect _keyboardFrame;
}

+ (id)viewControllerNavigationKey;
- (void).cxx_destruct;
- (void)addObservers;
- (void)adjustFramesForSearching:(BOOL)arg1 animated:(BOOL)arg2;
- (void)adjustSubviewsForNoMatches:(BOOL)arg1;
- (void)adjustTableHeaderForSearching:(BOOL)arg1;
- (void)adjustTableViewInsetsForSearching:(BOOL)arg1;
- (void)animateSearchContainerForSearching:(BOOL)arg1 animated:(BOOL)arg2;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)configureCell:(id)arg1 atIndexPath:(id)arg2;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned int)arg4 newIndexPath:(id)arg5;
- (void)controller:(id)arg1 didChangeSection:(id)arg2 atIndex:(unsigned int)arg3 forChangeType:(unsigned int)arg4;
- (void)controllerDidChangeContent:(id)arg1;
- (void)controllerWillChangeContent:(id)arg1;
- (void)dealloc;
- (struct CGRect)defaultTableHeaderFrame;
@property(nonatomic) __weak id <TNDRMatchesSearchDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didBlockUser;
- (void)didTapChatCloseButton;
- (void)didTapDiscoverButton;
- (void)didTapMomentStackViewControllerDoneButton;
- (void)didTapProfileDoneButton;
- (void)enableCancelButton:(id)arg1;
- (void)enableSearching:(BOOL)arg1 animated:(BOOL)arg2;
@property(retain, nonatomic) NSFetchedResultsController *fetchedResultsController; // @synthesize fetchedResultsController=_fetchedResultsController;
- (void)filterForCurrentlyViewedList;
@property(retain, nonatomic) UIAlertView *followAlertView; // @synthesize followAlertView=_followAlertView;
- (void)followMatch;
@property(retain, nonatomic) TNDRMatchCell *footerCell; // @synthesize footerCell=_footerCell;
@property(retain, nonatomic) UIView *footerContainer; // @synthesize footerContainer=_footerContainer;
- (struct CGRect)frameForTableView;
- (void)handleDidAuthenticateNotification:(id)arg1;
- (void)handleDidLogoutNotification:(id)arg1;
- (void)handleOverlayTap:(id)arg1;
- (void)handleUpdateDoneNotification:(id)arg1;
- (void)handleUserAuthenticatedNotification:(id)arg1;
- (void)handleUserLogoutNotification:(id)arg1;
@property(nonatomic) BOOL hasAuthed; // @synthesize hasAuthed=_hasAuthed;
@property(nonatomic) BOOL hasFinishedOneUpdateCallForThisSession; // @synthesize hasFinishedOneUpdateCallForThisSession=_hasFinishedOneUpdateCallForThisSession;
@property(nonatomic) BOOL hasMatches; // @synthesize hasMatches=_hasMatches;
@property(retain, nonatomic) TNDRMiniStackContainerView *headerViewContainer; // @synthesize headerViewContainer=_headerViewContainer;
- (void)hideMiniStack;
- (void)hideSearchBarIfNecessary;
- (void)hideSearchOverlayAnimated:(BOOL)arg1;
@property(retain, nonatomic) NSIndexPath *indexPathToFollow; // @synthesize indexPathToFollow=_indexPathToFollow;
- (BOOL)isActivePanelView;
@property(nonatomic) BOOL isCurrentlyVisible; // @synthesize isCurrentlyVisible=_isCurrentlyVisible;
- (BOOL)isEditingModeAllowed;
@property(nonatomic, getter=isInSearchMode) BOOL inSearchMode; // @synthesize inSearchMode=_inSearchMode;
@property(nonatomic, getter=isMiniStackVisible) BOOL miniStackVisible; // @synthesize miniStackVisible=_miniStackVisible;
@property(nonatomic, getter=isPresentingMomentStack) BOOL presentingMomentStack; // @synthesize presentingMomentStack=_presentingMomentStack;
@property(nonatomic, getter=isReturningFromChat) BOOL returningFromChat; // @synthesize returningFromChat=_returningFromChat;
@property(nonatomic) struct CGRect keyboardFrame; // @synthesize keyboardFrame=_keyboardFrame;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (BOOL)match:(id)arg1 isIn:(id)arg2;
@property(retain, nonatomic) TNDRMatch *matchToPresentFromSearch; // @synthesize matchToPresentFromSearch=_matchToPresentFromSearch;
@property(retain, nonatomic) NSMutableArray *matches; // @synthesize matches=_matches;
@property(retain, nonatomic) TNDRMatchesToMomentsAnimationController *matchesToMomentsAnimationController; // @synthesize matchesToMomentsAnimationController=_matchesToMomentsAnimationController;
@property(retain, nonatomic) UIView *matchesUpdatingView; // @synthesize matchesUpdatingView=_matchesUpdatingView;
@property(retain, nonatomic) UITapGestureRecognizer *miniMomentStackTapGestureRecognizer; // @synthesize miniMomentStackTapGestureRecognizer=_miniMomentStackTapGestureRecognizer;
- (void)miniMomentStackTapped:(id)arg1;
@property(retain, nonatomic) NSTimer *miniMomentStackUpdateTimer; // @synthesize miniMomentStackUpdateTimer=_miniMomentStackUpdateTimer;
@property(retain, nonatomic) TNDRMiniStackView *miniStackView; // @synthesize miniStackView=_miniStackView;
@property(retain, nonatomic) TNDRMomentStackViewController *momentStackViewController; // @synthesize momentStackViewController=_momentStackViewController;
@property(retain, nonatomic) NSFetchedResultsController *momentsFetchedResultsController; // @synthesize momentsFetchedResultsController=_momentsFetchedResultsController;
@property(retain, nonatomic) TNDRNoMatchesView *noMatchesView; // @synthesize noMatchesView=_noMatchesView;
- (float)normalizedOffsetFor:(id)arg1;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)performSearchOnMatchesWithText:(id)arg1;
- (int)preferredStatusBarStyle;
- (void)presentChatForMatch:(id)arg1 withAvatarImage:(id)arg2;
- (void)presentProfileForMatch:(id)arg1 withAvatarImage:(id)arg2;
@property(retain, nonatomic) TNDRProfilePreviewViewController *profilePreviewForRequest; // @synthesize profilePreviewForRequest=_profilePreviewForRequest;
@property(retain, nonatomic) TNDRChatToProfileTransitioningDelegate *profileTransitioningDelegate; // @synthesize profileTransitioningDelegate=_profileTransitioningDelegate;
@property(retain, nonatomic) TNDRPullToRefreshView *pullToRefreshView; // @synthesize pullToRefreshView=_pullToRefreshView;
- (void)registerNotifications;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
@property(retain, nonatomic) UIView *searchBarBackground; // @synthesize searchBarBackground=_searchBarBackground;
- (void)searchBarCancelButtonClicked:(id)arg1;
@property(retain, nonatomic) UIView *searchBarContainer; // @synthesize searchBarContainer=_searchBarContainer;
- (struct CGRect)searchBarFrame:(BOOL)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)searchBarTextDidEndEditing:(id)arg1;
- (struct CGRect)searchOnlyTableHeaderFrame;
@property(retain, nonatomic) NSIndexPath *selectedIndexPath; // @synthesize selectedIndexPath=_selectedIndexPath;
@property(retain, nonatomic) NSMutableArray *selectedMatches; // @synthesize selectedMatches=_selectedMatches;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setSearchBarEnabled:(BOOL)arg1;
@property(retain, nonatomic) NSPredicate *sharedMomentsPredicate; // @synthesize sharedMomentsPredicate=_sharedMomentsPredicate;
@property(retain, nonatomic) UIView *tableFooterWhiteView; // @synthesize tableFooterWhiteView=_tableFooterWhiteView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(retain, nonatomic) UIImage *userImageToPresentFromSearch; // @synthesize userImageToPresentFromSearch=_userImageToPresentFromSearch;
- (void)setupMatchesData;
- (void)setupMomentData;
- (void)setupMomentsHeaderView;
- (void)setupObserversAndFlagsForNoMatches;
- (void)setupPlaceholderText;
- (void)setupPullToRefreshView;
- (void)setupSearchBar;
- (void)setupSearchOverlay;
- (void)setupTableHeaderView;
- (void)setupTableView;
- (void)showMiniStack;
- (void)showSearchOverlayAnimated:(BOOL)arg1;
- (id)sortDescriptors;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (float)topOffsetIncludeMomentsHeader:(BOOL)arg1;
- (void)transitionTo:(id)arg1 optionsDict:(id)arg2 animated:(BOOL)arg3 completion:(CDUnknownBlockType)arg4;
- (void)updateChatBadgeInNavBar;
- (void)updateListImageInNavBar;
- (void)updateMatchCellText:(id)arg1 match:(id)arg2;
- (void)updateMatchCellTextWithMatchDate:(id)arg1 match:(id)arg2;
- (void)updateMiniMomentStackForDataChanges;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)wantsToFollow:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) id <UIViewControllerAnimatedTransitioning> animationController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

