//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TTTAttributedLabel.h"

@class NSTextCheckingResult, UILongPressGestureRecognizer;

@interface TNDRAttributedLabel : TTTAttributedLabel
{
    NSTextCheckingResult *_linkToCopy;
    UILongPressGestureRecognizer *_linkTapLongPressGR;
    UILongPressGestureRecognizer *_longPressCopyGR;
}

- (void).cxx_destruct;
- (BOOL)canBecomeFirstResponder;
- (BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)commonInit;
- (void)copy:(id)arg1;
- (void)copyLink:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)handleLongPressForCopy:(id)arg1;
- (id)linkAtPoint:(struct CGPoint)arg1;
@property(retain, nonatomic) UILongPressGestureRecognizer *linkTapLongPressGR; // @synthesize linkTapLongPressGR=_linkTapLongPressGR;
@property(retain, nonatomic) NSTextCheckingResult *linkToCopy; // @synthesize linkToCopy=_linkToCopy;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressCopyGR; // @synthesize longPressCopyGR=_longPressCopyGR;

@end

