//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSArray, TNDRMatch;

@interface TNDRMomentLikeMergeOperation : NSOperation
{
    BOOL _isFinished;
    int _countFoundMomentLikes;
    int _countMissingMomentLikes;
    NSArray *_momentLikesToMerge;
    TNDRMatch *_lastMatch;
}

- (void).cxx_destruct;
- (void)cleanupBadMomentLikesInContext:(id)arg1;
@property(nonatomic) int countFoundMomentLikes; // @synthesize countFoundMomentLikes=_countFoundMomentLikes;
@property(nonatomic) int countMissingMomentLikes; // @synthesize countMissingMomentLikes=_countMissingMomentLikes;
- (id)initWithMomentLikesToMerge:(id)arg1;
- (BOOL)isFinished;
@property(retain, nonatomic) TNDRMatch *lastMatch; // @synthesize lastMatch=_lastMatch;
- (id)matchForLike:(id)arg1 inContext:(id)arg2;
- (id)matchToUseInNotification;
@property(retain, nonatomic) NSArray *momentLikesToMerge; // @synthesize momentLikesToMerge=_momentLikesToMerge;
- (id)retrieveIDFromServerLike:(id)arg1;
- (id)retrieveUserIDFromServerLike:(id)arg1;
- (void)setFinished:(BOOL)arg1;
- (void)start;

@end

