//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CLGeocoder, NSArray, NSMutableDictionary;

@interface TNDRPassportMapSearchLocationViewModel : NSObject
{
    NSArray *_mapSearchResults;
    CLGeocoder *_geocoder;
    NSMutableDictionary *_cacheMapSearchResults;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *cacheMapSearchResults; // @synthesize cacheMapSearchResults=_cacheMapSearchResults;
@property(retain, nonatomic) CLGeocoder *geocoder; // @synthesize geocoder=_geocoder;
- (id)init;
@property(readonly, nonatomic) NSArray *mapSearchResults; // @synthesize mapSearchResults=_mapSearchResults;
- (void)performSearch:(id)arg1;
- (void)performSearch:(id)arg1 remotelyIfNeeded:(BOOL)arg2;
@property(readonly, copy, nonatomic) NSArray *popularLocationsResults;
- (void)searchAppleMaps:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)searchAppleMapsWithLocation:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)searchLocallyForCachedResults:(id)arg1;

@end

