//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "NSFetchedResultsControllerDelegate.h"
#import "TNDR2ProfilePreviewDelegate.h"
#import "TNDRActionSheetDelegate.h"
#import "TNDRChatBubbleCellDelegate.h"
#import "TNDRMomentStackViewControllerDelegate.h"
#import "TNDRMomentViewerViewControllerDelegate.h"
#import "TNDRMyMomentViewerDelegate.h"
#import "TNDRNotificationWindowDelegate.h"
#import "TNDRURLNavigableProtocol.h"
#import "UIAlertViewDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITextFieldDelegate.h"
#import "UITextViewDelegate.h"
#import "UIViewControllerTransitioningDelegate.h"

@class NSArray, NSDateFormatter, NSFetchedResultsController, NSMutableArray, NSMutableDictionary, NSString, NSTimer, PSPDFTextView, TNDR2ChatPlaceholderView, TNDRActionSheet, TNDRAttributedLabel, TNDRChatToMomentsStackAnimationController, TNDRChatToProfileTransitioningDelegate<UIViewControllerTransitioningDelegate>, TNDRMatch, TNDRMiniStackView, TNDRMomentStackViewController, TNDRMomentViewerViewController, TNDRMyMomentViewerView, TNDRMyMomentsToMomentViewerAnimationController, TNDRProfilePreviewViewController, TNDRReportViewController, UIAlertView, UIButton, UICollectionView, UICollectionViewFlowLayout, UIImage, UIImageView, UINavigationBar, UIPanGestureRecognizer, UITapGestureRecognizer, UIToolbar, UIView;

@interface TNDRChatViewController : UIViewController <UICollectionViewDataSource, UICollectionViewDelegate, UIGestureRecognizerDelegate, NSFetchedResultsControllerDelegate, UITextViewDelegate, UIAlertViewDelegate, UIViewControllerTransitioningDelegate, TNDRActionSheetDelegate, TNDRChatBubbleCellDelegate, TNDR2ProfilePreviewDelegate, TNDRMyMomentViewerDelegate, TNDRMomentStackViewControllerDelegate, TNDRNotificationWindowDelegate, TNDRMomentViewerViewControllerDelegate, UITextFieldDelegate, TNDRURLNavigableProtocol>
{
    NSString *_chatCellIdentifier;
    NSString *_likeCellIdentifier;
    float _spacingBetweenBubbles;
    NSString *_defaultPlaceholderText;
    NSMutableDictionary *_calculatedHeightsDictionary;
    NSDateFormatter *_dateFormatter;
    UIPanGestureRecognizer *_timeRevealPanGestureRecognizer;
    struct CGPoint _panStartPoint;
    struct CGPoint _panCurPoint;
    float _curDiffX;
    struct CGRect _initialComposeViewFrame;
    struct CGRect _initialComposeViewTextFrame;
    struct CGRect _initialComposeTextViewBGFrame;
    float _calcWidthOfAreaLeftOfSend;
    NSMutableArray *_fetchedObjectChanges;
    NSTimer *_testContentSizeTimer;
    UIView *_screenshotView;
    BOOL _hadFirstResponder;
    BOOL _showsLoading;
    BOOL _readyForPresentation;
    BOOL _miniStackVisible;
    BOOL _resizingEnabled;
    BOOL _attemptingBlock;
    BOOL _reloadAfterResendingMessage;
    BOOL _shouldShowStatusBar;
    BOOL _shouldReloadForMoreMessages;
    BOOL _canOpenAvatar;
    BOOL _didPresentMomentStack;
    TNDRMatch *_match;
    UIView *_avatarAndNameView;
    float _offsetY;
    UIImage *_matchImage;
    id <TNDRChatViewControllerDelegate> _delegate;
    id <TNDRChatViewControllerReadyDelegate> _animationDelegate;
    TNDRMiniStackView *_miniStackView;
    UINavigationBar *_navigationBar;
    NSFetchedResultsController *_fetchedResultsController;
    NSArray *_dataItemsArray;
    UICollectionView *_collectionView;
    UICollectionViewFlowLayout *_standardFlowLayout;
    UIImageView *_keyboardImageView;
    UIView *_noMessagesView;
    UIToolbar *_composeView;
    UIButton *_sendButton;
    PSPDFTextView *_composeTextView;
    TNDR2ChatPlaceholderView *_composePlaceholder;
    UIButton *_cameraButton;
    UITapGestureRecognizer *_tapAvatarTitleGestureRecognizer;
    NSMutableArray *_insertedChatCells;
    NSMutableArray *_updatedChatCells;
    TNDRAttributedLabel *_textHeightLabel;
    unsigned int _totalCountMessages;
    int _offsetIntoMessages;
    unsigned int _currentNumMessagesToRetrieve;
    UIView *_loadingHeader;
    UIImageView *_loadingFlame;
    NSTimer *_reloadTimer;
    TNDRChatToProfileTransitioningDelegate<UIViewControllerTransitioningDelegate> *_profileTransitionDelegate;
    TNDRActionSheet *_moreActionSheet;
    UIAlertView *_hideAlertView;
    UIAlertView *_followAlertView;
    UITapGestureRecognizer *_miniMomentStackTapGestureRecognizer;
    NSFetchedResultsController *_momentsFetchedResultsController;
    TNDRMomentStackViewController *_momentStackViewController;
    TNDRChatToMomentsStackAnimationController *_chatToMomentsAnimationController;
    TNDRMyMomentViewerView *_momentViewer;
    TNDRProfilePreviewViewController *_profilePreviewVC;
    TNDRMyMomentsToMomentViewerAnimationController *_toMomentViewerAnimationController;
    TNDRMomentViewerViewController *_momentViewerViewController;
    TNDRReportViewController *_reportViewController;
    UIView *_chatViewScreenshotWithoutStack;
    struct CGRect _keyboardFrame;
}

+ (id)viewControllerNavigationKey;
- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 triggeredButtonWithId:(int)arg2;
- (void)adjustCellPositions:(float)arg1;
- (void)adjustCollectionContentInsetsForUpdatedMomentCount;
- (void)adjustCollectionViewFrame;
- (void)adjustCollectionViewInsetsForLoading;
- (void)adjustCollectionViewInsetsToBase;
- (void)adjustContentOffsetToBottom:(BOOL)arg1;
- (void)adjustNavigationBarFrame:(BOOL)arg1;
- (void)adjustPlaceholderAlignmentForCharacterDirection;
- (void)adjustSubviewFrames:(BOOL)arg1 animated:(BOOL)arg2;
- (void)adjustTableViewForComposeViewResize;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)animateCellInsertion:(id)arg1 forIndexPath:(id)arg2;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
@property(nonatomic) __weak id <TNDRChatViewControllerReadyDelegate> animationDelegate; // @synthesize animationDelegate=_animationDelegate;
@property(retain, nonatomic) UIView *avatarAndNameView; // @synthesize avatarAndNameView=_avatarAndNameView;
@property(retain, nonatomic) UIButton *cameraButton; // @synthesize cameraButton=_cameraButton;
@property(nonatomic) BOOL canOpenAvatar; // @synthesize canOpenAvatar=_canOpenAvatar;
- (BOOL)canScrollChatToBottom;
- (void)chatBubbleCellDidTapAvatar:(id)arg1;
- (void)chatBubbleCellDidTapError:(id)arg1;
@property(retain, nonatomic) TNDRChatToMomentsStackAnimationController *chatToMomentsAnimationController; // @synthesize chatToMomentsAnimationController=_chatToMomentsAnimationController;
@property(retain, nonatomic) UIView *chatViewScreenshotWithoutStack; // @synthesize chatViewScreenshotWithoutStack=_chatViewScreenshotWithoutStack;
- (void)checkAndResetComposeTextView;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
@property(retain, nonatomic) TNDR2ChatPlaceholderView *composePlaceholder; // @synthesize composePlaceholder=_composePlaceholder;
@property(retain, nonatomic) PSPDFTextView *composeTextView; // @synthesize composeTextView=_composeTextView;
@property(retain, nonatomic) UIToolbar *composeView; // @synthesize composeView=_composeView;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned int)arg4 newIndexPath:(id)arg5;
- (void)controller:(id)arg1 didChangeSection:(id)arg2 atIndex:(unsigned int)arg3 forChangeType:(unsigned int)arg4;
- (void)controllerDidChangeContent:(id)arg1;
@property(nonatomic) unsigned int currentNumMessagesToRetrieve; // @synthesize currentNumMessagesToRetrieve=_currentNumMessagesToRetrieve;
@property(retain, nonatomic) NSArray *dataItemsArray; // @synthesize dataItemsArray=_dataItemsArray;
- (void)dealloc;
@property(nonatomic) __weak id <TNDRChatViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didBlockMatchFromProfile;
- (void)didCloseMomentViewer;
- (void)didEnterBackground:(id)arg1;
@property(nonatomic) BOOL didPresentMomentStack; // @synthesize didPresentMomentStack=_didPresentMomentStack;
- (void)didReceiveMemoryWarning;
- (void)didRequestToDeleteMoment:(id)arg1;
- (void)didRequestToOpenChatFor:(id)arg1;
- (void)didTapMomentStackViewControllerDoneButton;
- (void)didTapProfileDoneButton;
- (void)fadeInCollectionView;
- (id)fetchRequestForAllMessagesOfMatch:(id)arg1;
- (id)fetchRequestForPreviousSetOfMessages;
@property(retain, nonatomic) NSFetchedResultsController *fetchedResultsController; // @synthesize fetchedResultsController=_fetchedResultsController;
@property(retain, nonatomic) UIAlertView *followAlertView; // @synthesize followAlertView=_followAlertView;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)handleBlockButtonTapped;
- (void)handleCVPanGestures:(id)arg1;
- (void)handleDidAuthenticateNotification:(id)arg1;
- (void)handleDoneButtonTapped:(id)arg1;
- (void)handleLoadOlderMessages:(id)arg1;
- (void)handleMoreButtonTapped:(id)arg1;
- (void)handlePanGestures:(id)arg1;
- (void)handleProgressNotificationReceived:(id)arg1;
- (void)handleReportButtonTapped;
- (void)handleRequestToShowStatusBar:(id)arg1;
- (void)handleStatusBarFrameChanged:(id)arg1;
- (float)heightForText:(id)arg1;
- (float)heightForTextAtIndexPath:(id)arg1;
@property(retain, nonatomic) UIAlertView *hideAlertView; // @synthesize hideAlertView=_hideAlertView;
- (void)hideAndRemoveScreenshot;
- (void)hideKeyboardWithoutAnimation;
- (void)hideMiniStack;
- (id)init;
- (id)initWithAnimationDelegate:(id)arg1;
- (void)initializeFetchOffsetAndLimit;
@property(retain, nonatomic) NSMutableArray *insertedChatCells; // @synthesize insertedChatCells=_insertedChatCells;
@property(nonatomic, getter=isAttemptingBlock) BOOL attemptingBlock; // @synthesize attemptingBlock=_attemptingBlock;
- (BOOL)isMessageLikeAtIndexPath:(id)arg1;
@property(nonatomic, getter=isMiniStackVisible) BOOL miniStackVisible; // @synthesize miniStackVisible=_miniStackVisible;
@property(nonatomic, getter=isReadyForPresentation) BOOL readyForPresentation; // @synthesize readyForPresentation=_readyForPresentation;
@property(nonatomic, getter=isResizingEnabled) BOOL resizingEnabled; // @synthesize resizingEnabled=_resizingEnabled;
- (void)keyboardDidChangeFrame:(id)arg1;
- (void)keyboardDidHide:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
@property(nonatomic) struct CGRect keyboardFrame; // @synthesize keyboardFrame=_keyboardFrame;
@property(retain, nonatomic) UIImageView *keyboardImageView; // @synthesize keyboardImageView=_keyboardImageView;
- (id)keyboardScreenSnapshot;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
@property(retain, nonatomic) UIImageView *loadingFlame; // @synthesize loadingFlame=_loadingFlame;
@property(retain, nonatomic) UIView *loadingHeader; // @synthesize loadingHeader=_loadingHeader;
- (void)markMessagesViewed;
- (id)maskImage:(id)arg1 withMask:(id)arg2;
@property(retain, nonatomic) TNDRMatch *match; // @synthesize match=_match;
@property(retain, nonatomic) UIImage *matchImage; // @synthesize matchImage=_matchImage;
- (id)messageAtIndexPath:(id)arg1;
@property(retain, nonatomic) UITapGestureRecognizer *miniMomentStackTapGestureRecognizer; // @synthesize miniMomentStackTapGestureRecognizer=_miniMomentStackTapGestureRecognizer;
- (void)miniMomentStackTapped:(id)arg1;
@property(retain, nonatomic) TNDRMiniStackView *miniStackView; // @synthesize miniStackView=_miniStackView;
@property(retain, nonatomic) TNDRMomentStackViewController *momentStackViewController; // @synthesize momentStackViewController=_momentStackViewController;
@property(retain, nonatomic) TNDRMyMomentViewerView *momentViewer; // @synthesize momentViewer=_momentViewer;
@property(retain, nonatomic) TNDRMomentViewerViewController *momentViewerViewController; // @synthesize momentViewerViewController=_momentViewerViewController;
@property(retain, nonatomic) NSFetchedResultsController *momentsFetchedResultsController; // @synthesize momentsFetchedResultsController=_momentsFetchedResultsController;
- (id)momentsPredicate;
@property(retain, nonatomic) TNDRActionSheet *moreActionSheet; // @synthesize moreActionSheet=_moreActionSheet;
@property(retain, nonatomic) UINavigationBar *navigationBar; // @synthesize navigationBar=_navigationBar;
@property(retain, nonatomic) UIView *noMessagesView; // @synthesize noMessagesView=_noMessagesView;
- (float)normalizedCellTranslation;
- (BOOL)notificationWindow:(id)arg1 shouldShowNotification:(id)arg2;
- (int)numberOfSectionsInCollectionView:(id)arg1;
@property(nonatomic) int offsetIntoMessages; // @synthesize offsetIntoMessages=_offsetIntoMessages;
@property(nonatomic) float offsetY; // @synthesize offsetY=_offsetY;
- (void)positionComposeView;
- (id)predicateForMatch:(id)arg1;
- (int)preferredStatusBarStyle;
- (void)prepareForPresentation;
- (void)presentMomentStackCompletion:(CDUnknownBlockType)arg1;
- (void)presentMomentViewerForMoment:(id)arg1;
- (id)processSayings:(id)arg1;
@property(retain, nonatomic) TNDRProfilePreviewViewController *profilePreviewVC; // @synthesize profilePreviewVC=_profilePreviewVC;
@property(retain, nonatomic) TNDRChatToProfileTransitioningDelegate<UIViewControllerTransitioningDelegate> *profileTransitionDelegate; // @synthesize profileTransitionDelegate=_profileTransitionDelegate;
- (void)redrawTextView;
- (void)registerKeyboardNotifications;
- (void)registerNotifications;
@property(retain, nonatomic) NSTimer *reloadTimer; // @synthesize reloadTimer=_reloadTimer;
- (void)removeNoMessagesViewIfNecessary;
- (void)removeRefreshHeaderFromCollectionView;
@property(retain, nonatomic) TNDRReportViewController *reportViewController; // @synthesize reportViewController=_reportViewController;
- (void)resetCellPositions;
- (void)resizeComposeView:(BOOL)arg1;
- (id)retrieveLikesForUser:(id)arg1;
- (void)scrollChatToBottomAnimated:(BOOL)arg1;
- (void)scrollChatToBottomInitial;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (BOOL)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewWillBeginDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)send:(id)arg1;
@property(retain, nonatomic) UIButton *sendButton; // @synthesize sendButton=_sendButton;
@property(nonatomic, getter=shouldReloadAfterResendingMessage) BOOL reloadAfterResendingMessage; // @synthesize reloadAfterResendingMessage=_reloadAfterResendingMessage;
@property(nonatomic) BOOL shouldReloadForMoreMessages; // @synthesize shouldReloadForMoreMessages=_shouldReloadForMoreMessages;
@property(nonatomic) BOOL shouldShowStatusBar; // @synthesize shouldShowStatusBar=_shouldShowStatusBar;
@property(nonatomic) BOOL showsLoading; // @synthesize showsLoading=_showsLoading;
@property(retain, nonatomic) UICollectionViewFlowLayout *standardFlowLayout; // @synthesize standardFlowLayout=_standardFlowLayout;
@property(retain, nonatomic) UITapGestureRecognizer *tapAvatarTitleGestureRecognizer; // @synthesize tapAvatarTitleGestureRecognizer=_tapAvatarTitleGestureRecognizer;
@property(retain, nonatomic) TNDRAttributedLabel *textHeightLabel; // @synthesize textHeightLabel=_textHeightLabel;
@property(retain, nonatomic) TNDRMyMomentsToMomentViewerAnimationController *toMomentViewerAnimationController; // @synthesize toMomentViewerAnimationController=_toMomentViewerAnimationController;
@property(nonatomic) unsigned int totalCountMessages; // @synthesize totalCountMessages=_totalCountMessages;
@property(retain, nonatomic) NSMutableArray *updatedChatCells; // @synthesize updatedChatCells=_updatedChatCells;
- (void)setup;
- (void)setupActionSheet;
- (void)setupCell:(id)arg1 forIndexPath:(id)arg2 andMessage:(id)arg3;
- (void)setupCollectionView;
- (void)setupComposeView;
- (void)setupDateFormatter;
- (void)setupGestureRecognizers;
- (void)setupLikeCell:(id)arg1 forIndexPath:(id)arg2 andMessage:(id)arg3;
- (void)setupMessagesData;
- (void)setupMomentData;
- (void)setupMomentsHeaderView;
- (void)setupNavigationBars;
- (void)setupNoMessagesView;
- (void)setupRefreshHeaderOnCollectionView;
- (void)setupTitleView;
- (BOOL)shouldShowTimestampForIndexPath:(id)arg1;
- (void)showMatchProfile;
- (void)showMiniStack;
- (void)showScreenshot;
- (struct CGSize)sizeForTextInComposeView;
- (unsigned int)startIndexPathForMoment:(id)arg1 inMoments:(id)arg2;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (unsigned int)totalNumberOfMessages;
- (void)transitionTo:(id)arg1 optionsDict:(id)arg2 animated:(BOOL)arg3 completion:(CDUnknownBlockType)arg4;
- (void)unregisterKeyboardNotifications;
- (void)unregisterNotifications;
- (void)updateFetchOffsetAndLimit;
- (void)updateFetchedResultsControllerToGetPreviousMessages;
- (void)updateMiniMomentStackForDataChanges;
- (void)updateStatusBarAppearance;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)wantsToFollow;
- (void)wantsToHide;
- (void)willEnterForeground:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

