//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_TNDRUser.h"

@class NSArray;

@interface TNDRUser : _TNDRUser
{
    BOOL _profileViewed;
}

+ (id)rewindableUser;
- (void)awakeFromInsert;
- (void)declineRecommendation:(CDUnknownBlockType)arg1;
- (void)declineRecommendationTrending:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (CDUnknownBlockType)dislikeCompletionBlockWithCompletion:(CDUnknownBlockType)arg1;
- (id)imageURLForWidth:(float)arg1;
- (id)imageURLForWidth:(float)arg1 useLargerImageIfAvailable:(BOOL)arg2;
@property(nonatomic, getter=isProfileViewed) BOOL profileViewed; // @synthesize profileViewed=_profileViewed;
- (id)largeMainImageURL;
- (CDUnknownBlockType)likeCompletionBlockWithCompletion:(CDUnknownBlockType)arg1;
- (void)likeRecommendation:(CDUnknownBlockType)arg1;
- (void)likeRecommendationTrending:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (void)rearrangePhotosForUser:(id)arg1 basedOnJSON:(id)arg2;
- (void)reportWithReason:(id)arg1 andMessage:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)resetForRewind;
- (id)smallMainImageURL;
@property(readonly, nonatomic) NSArray *sortedPhotos;
- (void)update:(CDUnknownBlockType)arg1;
- (void)updateCommonAttributes:(CDUnknownBlockType)arg1;

@end

