//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewLayout.h"

@class NSMutableDictionary, NSMutableSet;

@interface TNDRPassportStackLayout : UICollectionViewLayout
{
    float _scaleFactor;
    float _verticalDistanceBetweenCards;
    float _stackCenterVerticalOffset;
    NSMutableDictionary *_layoutAttributes;
    NSMutableSet *_insertedIndexPaths;
    NSMutableSet *_deletedIndexPaths;
    struct CGSize _cardSize;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGSize cardSize; // @synthesize cardSize=_cardSize;
- (struct CGSize)collectionViewContentSize;
@property(retain, nonatomic) NSMutableSet *deletedIndexPaths; // @synthesize deletedIndexPaths=_deletedIndexPaths;
- (void)finalizeCollectionViewUpdates;
- (id)init;
@property(retain, nonatomic) NSMutableSet *insertedIndexPaths; // @synthesize insertedIndexPaths=_insertedIndexPaths;
@property(retain, nonatomic) NSMutableDictionary *layoutAttributes; // @synthesize layoutAttributes=_layoutAttributes;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (void)prepareForCollectionViewUpdates:(id)arg1;
- (void)prepareLayout;
@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(nonatomic) float stackCenterVerticalOffset; // @synthesize stackCenterVerticalOffset=_stackCenterVerticalOffset;
@property(nonatomic) float verticalDistanceBetweenCards; // @synthesize verticalDistanceBetweenCards=_verticalDistanceBetweenCards;

@end

