//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface TNDRMoreInfoButton : UIButton
{
}

- (id)actionForLayer:(id)arg1 forKey:(id)arg2;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setHighlighted:(BOOL)arg1;
- (void)setup;

@end

