//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface TNDRChatActionButton : UIButton
{
    BOOL _destructiveAction;
}

+ (float)defaultWidth;
- (id)initWithOrigin:(struct CGPoint)arg1;
@property(nonatomic, getter=isDestructiveAction) BOOL destructiveAction; // @synthesize destructiveAction=_destructiveAction;
- (void)layoutSubviews;
- (void)setup;
- (void)tintColorDidChange;

@end

