//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableArray, NSString;

@interface TNDRURLNavigationInfo : NSObject
{
    int _dismissTimes;
    NSMutableArray *_componentsToNavigate;
    NSString *_query;
    NSDictionary *_optionsDict;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *componentsToNavigate; // @synthesize componentsToNavigate=_componentsToNavigate;
- (id)debugDescription;
- (id)description;
@property(nonatomic) int dismissTimes; // @synthesize dismissTimes=_dismissTimes;
- (id)init;
@property(retain, nonatomic) NSDictionary *optionsDict; // @synthesize optionsDict=_optionsDict;
@property(retain, nonatomic) NSString *query; // @synthesize query=_query;
- (void)setup;

@end

