//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSString, TNDRColorButton, UIColor, UIImage;

@interface TNDRColorPickerView : UIView
{
    id <TNDRCrayonColorPickerDelegate> _delegate;
    UIImage *_currentImage;
    UIColor *_selectedColor;
    NSArray *_colorButtons;
    NSArray *_colorsInHex;
    NSArray *_colorSwatchButtons;
    UIColor *_currentlySelectedColor;
    UIView *_blurredSuperview;
    NSArray *_buttonStartTranslations;
    TNDRColorButton *_selectedColorButton;
    NSString *_defaultColorHex;
    UIView *_overlayView;
    struct CGPoint _startPoint;
    struct CGAffineTransform _startScale;
}

+ (BOOL)isThisColor:(id)arg1 equalToThatColor:(id)arg2;
- (void).cxx_destruct;
- (void)adjustColorButtonToTop:(id)arg1;
- (void)adjustColorButtonsToGrid;
- (void)adjustColorButtonsToStartPoint;
- (void)animateColorButtonsToGrid;
@property(retain, nonatomic) UIView *blurredSuperview; // @synthesize blurredSuperview=_blurredSuperview;
@property(retain, nonatomic) NSArray *buttonStartTranslations; // @synthesize buttonStartTranslations=_buttonStartTranslations;
@property(retain, nonatomic) NSArray *colorButtons; // @synthesize colorButtons=_colorButtons;
@property(retain, nonatomic) NSArray *colorSwatchButtons; // @synthesize colorSwatchButtons=_colorSwatchButtons;
@property(retain, nonatomic) NSArray *colorsInHex; // @synthesize colorsInHex=_colorsInHex;
@property(retain, nonatomic) UIImage *currentImage; // @synthesize currentImage=_currentImage;
@property(retain, nonatomic) UIColor *currentlySelectedColor; // @synthesize currentlySelectedColor=_currentlySelectedColor;
- (void)deemphasizeUnpickedColors;
@property(retain, nonatomic) NSString *defaultColorHex; // @synthesize defaultColorHex=_defaultColorHex;
@property(nonatomic) __weak id <TNDRCrayonColorPickerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deselectAllOtherColors;
- (void)dismissCrayonPicker;
- (void)dismissCrayonPickerForCancel;
- (void)handleColorSelected:(id)arg1;
- (void)handleOverlayTap:(id)arg1;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)newColorButton;
@property(retain, nonatomic) UIView *overlayView; // @synthesize overlayView=_overlayView;
- (void)prepareForAnimation;
- (void)presentColorPicker;
- (void)presentInView:(id)arg1;
- (void)saveTranslationValueToArray:(struct CGPoint)arg1;
- (void)selectColorButtonWithColor:(id)arg1;
@property(retain, nonatomic) UIColor *selectedColor; // @synthesize selectedColor=_selectedColor;
@property(retain, nonatomic) TNDRColorButton *selectedColorButton; // @synthesize selectedColorButton=_selectedColorButton;
@property(nonatomic) struct CGPoint startPoint; // @synthesize startPoint=_startPoint;
@property(nonatomic) struct CGAffineTransform startScale; // @synthesize startScale=_startScale;
- (void)setup;
- (void)setupBlurredView;
- (void)setupLargeColorButtons;

@end

