//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSShadow, UIColor;

@interface TNDRGamepadBackgroundView : UIView
{
    unsigned int _gamepadType;
    UIColor *_gamepadBackgroundColor;
    NSShadow *_innerShadow;
    NSArray *_wells;
}

- (void).cxx_destruct;
- (id)defaultWellBackgroundColor;
- (void)drawRect:(struct CGRect)arg1;
@property(retain, nonatomic) UIColor *gamepadBackgroundColor; // @synthesize gamepadBackgroundColor=_gamepadBackgroundColor;
@property(readonly, nonatomic) unsigned int gamepadType; // @synthesize gamepadType=_gamepadType;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithType:(unsigned int)arg1;
@property(retain, nonatomic) NSShadow *innerShadow; // @synthesize innerShadow=_innerShadow;
- (id)path;
@property(retain, nonatomic) NSArray *wells; // @synthesize wells=_wells;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

