//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TNDRPassportUnderlinedView.h"

@class UILabel, UIView;

@interface TNDRPassportLocationStatsView : TNDRPassportUnderlinedView
{
    UILabel *_populationLabel;
    UILabel *_timeLabel;
    UIView *_labelContainer;
    UILabel *_populationDescriptionLabel;
    UILabel *_timeDescriptionLabel;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UIView *labelContainer; // @synthesize labelContainer=_labelContainer;
@property(retain, nonatomic) UILabel *populationDescriptionLabel; // @synthesize populationDescriptionLabel=_populationDescriptionLabel;
@property(retain, nonatomic) UILabel *populationLabel; // @synthesize populationLabel=_populationLabel;
@property(retain, nonatomic) UILabel *timeDescriptionLabel; // @synthesize timeDescriptionLabel=_timeDescriptionLabel;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
- (void)setupLayoutConstraints;
- (void)setupSubviews;

@end

