//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

#import "TTTAttributedLabel.h"
#import "UIGestureRecognizerDelegate.h"

@class NSArray, NSAttributedString, NSDataDetector, NSDictionary, NSString, NSTextCheckingResult, UIColor;

@interface TTTAttributedLabel : UILabel <TTTAttributedLabel, UIGestureRecognizerDelegate>
{
    BOOL _needsFramesetter;
    struct __CTFramesetter *_framesetter;
    struct __CTFramesetter *_highlightFramesetter;
    NSAttributedString *_attributedText;
    id <TTTAttributedLabelDelegate> _delegate;
    NSArray *_links;
    NSDictionary *_linkAttributes;
    NSDictionary *_activeLinkAttributes;
    NSDictionary *_inactiveLinkAttributes;
    float _shadowRadius;
    float _highlightedShadowRadius;
    UIColor *_highlightedShadowColor;
    float _kern;
    float _firstLineIndent;
    float _lineSpacing;
    float _minimumLineHeight;
    float _maximumLineHeight;
    float _lineHeightMultiple;
    int _verticalAlignment;
    NSString *_truncationTokenString;
    NSDictionary *_truncationTokenStringAttributes;
    NSAttributedString *_attributedTruncationToken;
    NSAttributedString *_inactiveAttributedText;
    NSAttributedString *_renderedAttributedText;
    NSDataDetector *_dataDetector;
    NSTextCheckingResult *_activeLink;
    NSArray *_accessibilityElements;
    unsigned long long _enabledTextCheckingTypes;
    struct CGSize _highlightedShadowOffset;
    struct UIEdgeInsets _linkBackgroundEdgeInset;
    struct UIEdgeInsets _textInsets;
}

+ (void)load;
+ (struct CGSize)sizeThatFitsAttributedString:(id)arg1 withConstraints:(struct CGSize)arg2 limitedToNumberOfLines:(unsigned int)arg3;
- (void).cxx_destruct;
- (id)accessibilityElementAtIndex:(int)arg1;
- (int)accessibilityElementCount;
@property(retain, nonatomic) NSArray *accessibilityElements; // @synthesize accessibilityElements=_accessibilityElements;
@property(retain, nonatomic) NSTextCheckingResult *activeLink; // @synthesize activeLink=_activeLink;
@property(retain, nonatomic) NSDictionary *activeLinkAttributes; // @synthesize activeLinkAttributes=_activeLinkAttributes;
- (void)addLinkToAddress:(id)arg1 withRange:(struct _NSRange)arg2;
- (void)addLinkToDate:(id)arg1 timeZone:(id)arg2 duration:(double)arg3 withRange:(struct _NSRange)arg4;
- (void)addLinkToDate:(id)arg1 withRange:(struct _NSRange)arg2;
- (void)addLinkToPhoneNumber:(id)arg1 withRange:(struct _NSRange)arg2;
- (void)addLinkToTransitInformation:(id)arg1 withRange:(struct _NSRange)arg2;
- (void)addLinkToURL:(id)arg1 withRange:(struct _NSRange)arg2;
- (void)addLinkWithTextCheckingResult:(id)arg1;
- (void)addLinkWithTextCheckingResult:(id)arg1 attributes:(id)arg2;
- (void)addLinksWithTextCheckingResults:(id)arg1 attributes:(id)arg2;
@property(copy, nonatomic) NSAttributedString *attributedText; // @synthesize attributedText=_attributedText;
@property(retain, nonatomic) NSAttributedString *attributedTruncationToken; // @synthesize attributedTruncationToken=_attributedTruncationToken;
- (struct CGRect)boundingRectForCharacterRange:(struct _NSRange)arg1;
- (BOOL)canBecomeFirstResponder;
- (BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (long)characterIndexAtPoint:(struct CGPoint)arg1;
- (void)commonInit;
- (BOOL)containslinkAtPoint:(struct CGPoint)arg1;
- (void)copy:(id)arg1;
@property(retain) NSDataDetector *dataDetector; // @synthesize dataDetector=_dataDetector;
@property(nonatomic) unsigned long long dataDetectorTypes;
- (void)dealloc;
@property(nonatomic) id <TTTAttributedLabelDelegate> delegate; // @synthesize delegate=_delegate;
- (void)drawBackground:(struct __CTFrame *)arg1 inRect:(struct CGRect)arg2 context:(struct CGContext *)arg3;
- (void)drawFramesetter:(struct __CTFramesetter *)arg1 attributedString:(id)arg2 textRange:(CDStruct_1ef3fb1f)arg3 inRect:(struct CGRect)arg4 context:(struct CGContext *)arg5;
- (void)drawStrike:(struct __CTFrame *)arg1 inRect:(struct CGRect)arg2 context:(struct CGContext *)arg3;
- (void)drawTextInRect:(struct CGRect)arg1;
@property(nonatomic) unsigned long long enabledTextCheckingTypes; // @synthesize enabledTextCheckingTypes=_enabledTextCheckingTypes;
- (void)encodeWithCoder:(id)arg1;
@property(nonatomic) float firstLineIndent; // @synthesize firstLineIndent=_firstLineIndent;
- (struct __CTFramesetter *)framesetter;
- (struct __CTFramesetter *)highlightFramesetter;
@property(retain, nonatomic) UIColor *highlightedShadowColor; // @synthesize highlightedShadowColor=_highlightedShadowColor;
@property(nonatomic) struct CGSize highlightedShadowOffset; // @synthesize highlightedShadowOffset=_highlightedShadowOffset;
@property(nonatomic) float highlightedShadowRadius; // @synthesize highlightedShadowRadius=_highlightedShadowRadius;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
@property(copy, nonatomic) NSAttributedString *inactiveAttributedText; // @synthesize inactiveAttributedText=_inactiveAttributedText;
@property(retain, nonatomic) NSDictionary *inactiveLinkAttributes; // @synthesize inactiveLinkAttributes=_inactiveLinkAttributes;
- (int)indexOfAccessibilityElement:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (struct CGSize)intrinsicContentSize;
- (BOOL)isAccessibilityElement;
@property(nonatomic) float kern; // @synthesize kern=_kern;
@property(nonatomic) float leading;
@property(nonatomic) float lineHeightMultiple; // @synthesize lineHeightMultiple=_lineHeightMultiple;
@property(nonatomic) float lineSpacing; // @synthesize lineSpacing=_lineSpacing;
- (id)linkAtCharacterIndex:(long)arg1;
- (id)linkAtPoint:(struct CGPoint)arg1;
@property(retain, nonatomic) NSDictionary *linkAttributes; // @synthesize linkAttributes=_linkAttributes;
@property(nonatomic) struct UIEdgeInsets linkBackgroundEdgeInset; // @synthesize linkBackgroundEdgeInset=_linkBackgroundEdgeInset;
@property(retain, nonatomic) NSArray *links; // @synthesize links=_links;
@property(nonatomic) float maximumLineHeight; // @synthesize maximumLineHeight=_maximumLineHeight;
@property(nonatomic) float minimumLineHeight; // @synthesize minimumLineHeight=_minimumLineHeight;
@property(copy, nonatomic) NSAttributedString *renderedAttributedText; // @synthesize renderedAttributedText=_renderedAttributedText;
- (void)setFramesetter:(struct __CTFramesetter *)arg1;
- (void)setHighlightFramesetter:(struct __CTFramesetter *)arg1;
- (void)setHighlighted:(BOOL)arg1;
- (void)setNeedsFramesetter;
@property(nonatomic) float shadowRadius; // @synthesize shadowRadius=_shadowRadius;
@property(copy, nonatomic) id text; // @dynamic text;
- (void)setText:(id)arg1 afterInheritingLabelAttributesAndConfiguringWithBlock:(CDUnknownBlockType)arg2;
- (void)setTextColor:(id)arg1;
@property(nonatomic) struct UIEdgeInsets textInsets; // @synthesize textInsets=_textInsets;
@property(retain, nonatomic) NSString *truncationTokenString; // @synthesize truncationTokenString=_truncationTokenString;
@property(retain, nonatomic) NSDictionary *truncationTokenStringAttributes; // @synthesize truncationTokenStringAttributes=_truncationTokenStringAttributes;
@property(nonatomic) int verticalAlignment; // @synthesize verticalAlignment=_verticalAlignment;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)textColor;
- (struct CGRect)textRectForBounds:(struct CGRect)arg1 limitedToNumberOfLines:(int)arg2;
- (void)tintColorDidChange;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

