//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSFormatter.h"

@class NSLocale;

@interface TTTAddressFormatter : NSFormatter
{
    NSLocale *_locale;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (BOOL)getObjectValue:(out id *)arg1 forString:(id)arg2 errorDescription:(out id *)arg3;
- (id)init;
- (id)initWithCoder:(id)arg1;
@property(retain, nonatomic) NSLocale *locale; // @synthesize locale=_locale;
- (id)stringForObjectValue:(id)arg1;
- (id)stringFromAddressWithStreet:(id)arg1 locality:(id)arg2 region:(id)arg3 postalCode:(id)arg4 country:(id)arg5;

@end

