//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (Adjustments)
+ (int)convertToDegreesFromFloat:(float)arg1;
+ (float)convertToFloatFromDegrees:(int)arg1;
- (float)brightnessValue;
- (id)colorWithBrightnessAt:(float)arg1;
- (id)colorWithSaturationAt:(float)arg1;
- (id)complimentaryColorAtSaturation:(float)arg1 andBrightness:(float)arg2;
- (id)darkenColor:(float)arg1;
- (id)darkerColor;
- (id)desaturateColor:(float)arg1;
- (BOOL)isBrightnessAbove:(float)arg1;
- (id)lightenColor:(float)arg1;
- (id)lighterColor;
- (id)saturateColor:(float)arg1;
- (float)saturationValue;
@end

