//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIFont.h"

@interface UIFont (TNDRFonts)
+ (id)tinderDialogHeaderDetailTextFont;
+ (id)tinderDialogHeaderTitleTextFont;
+ (id)tinderGameCardLightFont;
+ (id)tinderGameCardRegularFont;
+ (id)tinderIntroInfoButtonFont;
+ (id)tinderIntroPrivacyListMediumFont;
+ (id)tinderMatchFontItalic;
+ (id)tinderReportingDialogHeaderDetailTextFont;
+ (id)tinderReportingDialogHeaderTitleTextFont;
+ (id)tinderSettingsDefaultFont;
+ (id)tinderSettingsDefaultFontBold;
+ (id)tinderSettingsHeaderTitleFont;
+ (id)tinderSettingsHeaderValueFont;
+ (id)tinderSettingsNavBarEditFont;
@end

