//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (filterPresets)
+ (id)nameForFilter:(int)arg1;
- (struct histogram)OLDhistogramForImage:(id)arg1;
- (id)applyHistogram:(int)arg1;
- (struct histogram *)histogramForImage:(id)arg1;
- (int)histogramNumber:(int)arg1;
- (id)presetFilter:(int)arg1;
@end

