//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (PureLayout)
+ (int)al_attributeForALAttribute:(int)arg1;
+ (int)al_attributeForAxis:(int)arg1;
+ (int)al_attributeForDimension:(int)arg1;
+ (int)al_attributeForEdge:(int)arg1;
+ (int)al_constraintAxisForAxis:(int)arg1;
+ (void)autoRemoveConstraint:(id)arg1;
+ (void)autoRemoveConstraints:(id)arg1;
+ (void)autoSetPriority:(float)arg1 forConstraints:(CDUnknownBlockType)arg2;
+ (id)newAutoLayoutView;
- (void)al_addConstraintUsingGlobalPriority:(id)arg1;
- (id)al_alignToView:(id)arg1 withOption:(unsigned int)arg2 forAxis:(int)arg3;
- (id)al_commonSuperviewWithView:(id)arg1;
- (id)autoAlignAxis:(int)arg1 toSameAxisOfView:(id)arg2;
- (id)autoAlignAxis:(int)arg1 toSameAxisOfView:(id)arg2 withOffset:(float)arg3;
- (id)autoAlignAxisToSuperviewAxis:(int)arg1;
- (id)autoCenterInSuperview;
- (id)autoConstrainAttribute:(int)arg1 toAttribute:(int)arg2 ofView:(id)arg3;
- (id)autoConstrainAttribute:(int)arg1 toAttribute:(int)arg2 ofView:(id)arg3 withMultiplier:(float)arg4;
- (id)autoConstrainAttribute:(int)arg1 toAttribute:(int)arg2 ofView:(id)arg3 withMultiplier:(float)arg4 relation:(int)arg5;
- (id)autoConstrainAttribute:(int)arg1 toAttribute:(int)arg2 ofView:(id)arg3 withOffset:(float)arg4;
- (id)autoConstrainAttribute:(int)arg1 toAttribute:(int)arg2 ofView:(id)arg3 withOffset:(float)arg4 relation:(int)arg5;
- (id)autoMatchDimension:(int)arg1 toDimension:(int)arg2 ofView:(id)arg3;
- (id)autoMatchDimension:(int)arg1 toDimension:(int)arg2 ofView:(id)arg3 withMultiplier:(float)arg4;
- (id)autoMatchDimension:(int)arg1 toDimension:(int)arg2 ofView:(id)arg3 withMultiplier:(float)arg4 relation:(int)arg5;
- (id)autoMatchDimension:(int)arg1 toDimension:(int)arg2 ofView:(id)arg3 withOffset:(float)arg4;
- (id)autoMatchDimension:(int)arg1 toDimension:(int)arg2 ofView:(id)arg3 withOffset:(float)arg4 relation:(int)arg5;
- (id)autoPinEdge:(int)arg1 toEdge:(int)arg2 ofView:(id)arg3;
- (id)autoPinEdge:(int)arg1 toEdge:(int)arg2 ofView:(id)arg3 withOffset:(float)arg4;
- (id)autoPinEdge:(int)arg1 toEdge:(int)arg2 ofView:(id)arg3 withOffset:(float)arg4 relation:(int)arg5;
- (id)autoPinEdgeToSuperviewEdge:(int)arg1 withInset:(float)arg2;
- (id)autoPinEdgeToSuperviewEdge:(int)arg1 withInset:(float)arg2 relation:(int)arg3;
- (id)autoPinEdgesToSuperviewEdgesWithInsets:(struct UIEdgeInsets)arg1;
- (id)autoPinEdgesToSuperviewEdgesWithInsets:(struct UIEdgeInsets)arg1 excludingEdge:(int)arg2;
- (id)autoPinToBottomLayoutGuideOfViewController:(id)arg1 withInset:(float)arg2;
- (id)autoPinToTopLayoutGuideOfViewController:(id)arg1 withInset:(float)arg2;
- (void)autoRemoveConstraintsAffectingView;
- (void)autoRemoveConstraintsAffectingViewAndSubviews;
- (void)autoRemoveConstraintsAffectingViewAndSubviewsIncludingImplicitConstraints:(BOOL)arg1;
- (void)autoRemoveConstraintsAffectingViewIncludingImplicitConstraints:(BOOL)arg1;
- (void)autoSetContentCompressionResistancePriorityForAxis:(int)arg1;
- (void)autoSetContentHuggingPriorityForAxis:(int)arg1;
- (id)autoSetDimension:(int)arg1 toSize:(float)arg2;
- (id)autoSetDimension:(int)arg1 toSize:(float)arg2 relation:(int)arg3;
- (id)autoSetDimensionsToSize:(struct CGSize)arg1;
- (id)initForAutoLayout;
@end

