//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (tinderSnapshot)
+ (BOOL)deviceSupportsScreenshots;
+ (BOOL)isLessThaniPhone6;
- (id)imageViewWithView;
- (id)snapshotFromView;
- (id)snapshotFromViewAfterScreenUpdate:(BOOL)arg1;
- (id)snapshotImage;
@end

