//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSXMLParserDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSMutableString, NSString;

@interface XMLDictionaryParser : NSObject <NSXMLParserDelegate, NSCopying>
{
    BOOL _collapseTextNodes;
    BOOL _stripEmptyNodes;
    BOOL _trimWhiteSpace;
    BOOL _alwaysUseArrays;
    BOOL _preserveComments;
    BOOL _wrapRootNode;
    int _attributesMode;
    int _nodeNameMode;
    NSMutableDictionary *_root;
    NSMutableArray *_stack;
    NSMutableString *_text;
}

+ (id)XMLStringForNode:(id)arg1 withNodeName:(id)arg2;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)addText:(id)arg1;
@property(nonatomic) BOOL alwaysUseArrays; // @synthesize alwaysUseArrays=_alwaysUseArrays;
@property(nonatomic) int attributesMode; // @synthesize attributesMode=_attributesMode;
@property(nonatomic) BOOL collapseTextNodes; // @synthesize collapseTextNodes=_collapseTextNodes;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)dictionaryWithData:(id)arg1;
- (id)dictionaryWithFile:(id)arg1;
- (id)dictionaryWithParser:(id)arg1;
- (id)dictionaryWithString:(id)arg1;
- (void)endText;
- (id)init;
- (id)nameForNode:(id)arg1 inDictionary:(id)arg2;
@property(nonatomic) int nodeNameMode; // @synthesize nodeNameMode=_nodeNameMode;
- (void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4;
- (void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5;
- (void)parser:(id)arg1 foundCDATA:(id)arg2;
- (void)parser:(id)arg1 foundCharacters:(id)arg2;
- (void)parser:(id)arg1 foundComment:(id)arg2;
@property(nonatomic) BOOL preserveComments; // @synthesize preserveComments=_preserveComments;
@property(retain, nonatomic) NSMutableDictionary *root; // @synthesize root=_root;
@property(retain, nonatomic) NSMutableArray *stack; // @synthesize stack=_stack;
@property(nonatomic) BOOL stripEmptyNodes; // @synthesize stripEmptyNodes=_stripEmptyNodes;
@property(retain, nonatomic) NSMutableString *text; // @synthesize text=_text;
@property(nonatomic) BOOL trimWhiteSpace; // @synthesize trimWhiteSpace=_trimWhiteSpace;
@property(nonatomic) BOOL wrapRootNode; // @synthesize wrapRootNode=_wrapRootNode;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

